### PR TITLE
[GEOT-6642] Upgrade Oracle JDBC driver to 19.7.0.0

### PR DESCRIPTION
**Pull request by mprins**
A new version of the Oracle JDBC driver was released recently.
Update com.oracle.database.jdbc:ojdbc8 19.6.0.0 ➜ 19.7.0.0

No backports of this because #2832 was not backported due to API changes (users can always update the driver in their own application if they want)

see:
- https://osgeo-org.atlassian.net/browse/GEOT-6642

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by mprins** [comment]
that's odd...

Travis failing on:
```
[INFO] 
[ERROR] Failures: 
[ERROR]   OraclePrimaryKeyFinderOnlineTest>OnlineTestCase.run:112->JDBCPrimaryKeyFinderOnlineTest.testSequencedPrimaryKey:50->addFeature:47 actual fid: null does not match expected SEQTABLE.4(\..*)?
```
but that test was disabled in #3001 

gonna try locally

**Comment by aaime** [comment]
I know, something is clearly not working in the way it got disabled, other PRs are failing the same way... :-(

**Comment by mprins** [comment]
I think I see what's askew:

https://github.com/geotools/geotools/blob/b0981db3a1ad5aec3bb0f4f2bd8cf217edfc2b70/modules/plugin/jdbc/jdbc-oracle/pom.xml#L86

and 

https://github.com/geotools/geotools/blob/b0981db3a1ad5aec3bb0f4f2bd8cf217edfc2b70/modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OraclePrimaryKeyOnlineTest.java#L39

don't match. I'll add a fix to this PR

**Comment by mprins** [comment]
Wel... still failing but now because the assumption is treated as an error and not a skip condition

```
[ERROR] Errors: 
[ERROR]   OraclePrimaryKeyOnlineTest>OnlineTestCase.run:112->testSequencedPrimaryKey:39 » AssumptionViolated
```

**Comment by mprins** [comment]
@aaime  I changed the Assume check for a coded check/shortcut, I have done several iterations of assumptions but was unable to get it to "skip", the test kept failing with an Assumption Violated exception instead of reporting that sas a skipped test. (Assumptions are supposed to throw `org.junit.AssumptionViolatedException` and surefire is supposed to catch that and 

eg. other variations such as 
`assumeTrue("Travis-CI skip property is set", System.getProperty("travis-oracle-build") == null);`
or `assumeThat("Travis-CI skip property is set", System.getProperty("travis-oracle-build"), is(nullValue()));`
 also failed.
Quick try at upgrading plugin and dependencies didn't make a difference either :bomb:

**Comment by aaime** [comment]
Thank you @mprins , looks good!

**Pull request merged**
