### PR TITLE
Fix geot 5621

### PR DESCRIPTION
**Pull request by esuarezsantana**
Fix [GEOT-5621](https://osgeo-org.atlassian.net/browse/GEOT-5621).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [X] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [X] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [X] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [X] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [X] New unit tests have been added covering the changes
- [X] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [X] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Congrats on your first pull request! As noted in the checklist we are an OSGeo project and have a contributor license agreement to double check you (or your employer) is comfortable with contributing to open source.

While GeoServer is a GPL license (for distribution) we do require that a CLA be signed as we like to be able to contribute code to upstream projects such as JTS, GeoTools and others.

**Comment by esuarezsantana** [comment]
Do you think this PR needs to be squashed into one commit?

**Comment by aaime** [comment]
Our rules are clear. You don't need to squash it though, we can squash-merge it when it's ready.

**Comment by esuarezsantana** [comment]
I think that is ready for review and merge, as far as I'm concerned.

**Comment by aaime** [comment]
@esuarezsantana the remaining issue is that this module hasn't had a maintainer for a few years now... we should really be pushing it down into "unsupported", the main reason why it has not been done is that, even moving it down, takes some time and effort.

Also, its tests are the "online" kind and won't run unless one the configuration files in the home (e.g, something like ``$HOME/.geotools/db2.properties`` with connection params) and has each database ready to run the tests. Did you run the tests, and checked nothing (new?) fails?

Do you maybe understand the module enough, and have time enough, to step up as the new module maintainer?

**Comment by esuarezsantana** [comment]
@aaime Sorry for the late response.

The proposed change deals with the computation of the raster image, and it has nothing to do with the database connections. Anyway, what I did was to include the new test for every database file. Maybe I was just expecting the CI to test them for me. But no, I didn't test for every database. I just did it for the H2 database.

On the other hand, I don't know the module enough. Moreover, it has no relation with my job and I don't even consider myself a Java developer. I just found it to fit my data infrastructure, and when the bug was found, I did some eclipse stuff to try to get it fixed.

Sorry I can't help anymore.

**Comment by aaime** [comment]
I understand. We asked around for potential contributors (on the devel and users list) and found no one to step up.
As a results, we'll demote the module to unsupported. There is no reason not to merge the PR then, in unsupported modules "anything goes". Thanks for your contribution.

**Pull request merged**
