### PR TITLE
Resolve NullPointerException when GridCoverage is outside of view area

### PR DESCRIPTION
**Pull request by matchami**
For more info on the bug and test case see GEOT-5421

### CODE REVIEW

**Comment by aaime** [comment]
Needs a test, the pull needs to target master first

**Comment by matchami** [comment]
Test case can be found here: https://osgeo-org.atlassian.net/browse/GEOT-5421
Not a unit test as it is a UI issue

**Comment by matchami** [comment]
Hi Andrea,

The test is attached to the referenced JIRA ticket.  As it is a UI issue 
it is not testable (that we have discovered) by a unit test.

With regards to the target I am unfamiliar with git and simply followed 
the instructions on github as to how one should create a pull request.  
If you can provide me with better instructions I am happy to rectify this.

Thanks
Iain


On 3/06/2016 7:13 p.m., Andrea Aime wrote:
>
> Needs a test, the pull needs to target master first
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/geotools/geotools/pull/1204#issuecomment-223507625>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AChibCSVsQKu2ZCLZ3Uql7o99EGup6UDks5qH9QagaJpZM4ItIJi>.
>

-- 
Sent from my ZX80



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by aaime** [comment]
I'll see if I can write a test for you, looking at the code, it's hard to believe it's actually not possible to write one

**Comment by matchami** [comment]
Thanks Andrea.

You are quite right I just needed to spend a little more time 
understanding how StreamingRenderer worked.  I now understand this and 
can move the UI test to a unit test which I will add to the pull request 
shortly.

Thanks
Iain

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by matchami** [comment]
Test case added

**Comment by matchami** [comment]
Sorry, git newbie error.  Test case NOW added

**Comment by aaime** [comment]
Yep, I believe it's good, just a few minor things left to fix:

- The new test class lacks a copyright header
- The new test class it's not following coding conventions (should be indented with spaces, not tabs)
- The pull request must target master first, then we can backport it.

**Comment by matchami** [comment]
Thanks Andrea,
I have made the changes you requested and have created a new pull request that targets the master as I could not find a way to change this one.
Please let me know if you need anything else.
Iain

**Comment by jodygarnett** [comment]
Thanks @matchami and @bencaradocdavies for working through this (git can be fun).

**Comment by matchami** [comment]
Have created PR 1212 for this change in the master branch

**Comment by bencaradocdavies** [comment]
Cherry-picked onto 15.x: https://github.com/geotools/geotools/commit/f50659d2fd471f0da24905f042a8f500686f5a75

**Comment by bencaradocdavies** [comment]
@aaime is this fix suitable for backport to 14.x? It might be a useful fix for inclusion in 14.4.

**Pull request closed without merging**
