### PR TITLE
[GEOT-5438] Curve support not complete for curved polygons with multiple

### PR DESCRIPTION
**Pull request by fernandor777**
Fix the inner curve multiple holes support on Polygon type for Oracle JDBC data source due to an arithmetic bug in inner rings iteration.

https://osgeo-org.atlassian.net/browse/GEOT-5438

### CODE REVIEW

**Comment by aaime** [comment]
Hmm... something wrong happened here, the files seem to have been fully rewritten, likely a case of replacing newline endings.

**Comment by fernandor777** [comment]
Looks like original files use CRLF end line and my Git on windows is configured to replace all end line to LF only.  Rebulding the PR commit, thanks!

**Comment by aaime** [comment]
Seems ok to me

**Comment by aaime** [comment]
+1

**Pull request merged**
