### PR TITLE
[GEOT-5300] Upgrade to EJML 0.32

### PR DESCRIPTION
**Pull request by don-vip**
Fix for https://osgeo-org.atlassian.net/browse/GEOT-5300

Upgrade to EJML 0.32

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
This upgrade does not seem to alter any public GeoTools API. Are there any compatibility concerns with the upgrade?

**Comment by don-vip** [comment]
I don't know. One JOSM plugin wants to use latest version of library so I updated GeoTools. I just checked that all tests were OK before creating the PR.

**Comment by don-vip** [comment]
Most of the changes were done automatically by official script: https://github.com/lessthanoptimal/ejml/blob/master/convert_to_ejml31.py

**Comment by aaime** [comment]
Checked GeoServer, found no dependencies (so no issues there). Wondering if @jodygarnett or @jnh5y have any comment on the upgrade?

**Comment by jnh5y** [comment]
Looks good to me.  I don't know of any issues or conflicts.

**Comment by bencaradocdavies** [comment]
@don-vip thanks for the upgrade. After one month, this change will be eligible for backport to stable.

**Pull request merged**
