### PR TITLE
[GEOT-7208] Missing YSLD support for channel name expressions

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOT-7208](https://osgeo-org.atlassian.net/browse/GEOT-7208) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR allows YSLD styles to use raster channel name expressions, which was added for SLD styles a while ago.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by sikeoka** [comment]
@jodygarnett could you review this when you have time since you reviewed my last YSLD PR?

**Comment by sikeoka** [comment]
Any thoughts on this PR @aaime or @jodygarnett?

**Comment by sikeoka** [comment]
Any thoughts on my YSLD PRs @aaime or @jodygarnett?  It's getting close to a month with no feedback.

**Comment by aaime** [comment]
@jodygarnett is the module maintainer, you'll have to wait for his review.

**Comment by sikeoka** [comment]
Any thoughts on this PR @jodygarnett?

**Comment by sikeoka** [comment]
Any thoughts on this PR @jodygarnett?

**Comment by sikeoka** [comment]
@aaime I know you guys are busy but what are the chances of this making it into the GeoServer 2.22.0 release?  Should I just give up on this module after 45 days?  Both of my YSLD PRs are only 2-3 lines of non-test code changes.  Would it be possible to mention these PRs during your weekly meetings?

**Comment by aaime** [comment]
Modules need a maintainer to be supported... after 45 days one might thing the maintainer is not active, or is not receiving GitHub notifications. If you care about the module you could also step up to become its maintainer.
Anyways, pinging @jodygarnett through other channels as well, let's see.

**Comment by jodygarnett** [comment]
Hey! Thanks for brining this to my attention @aaime; I have indeed been busy run off my feet since foss4g.

Let me look at this now.

**Review by jodygarnett — APPROVED** [review]
Thanks for the nice clear contribution.

**Pull request merged**
