### PR TITLE
[GEOT-5487] Cropped coverage with longitudes in (0,360) can be render…

### PR DESCRIPTION
**Pull request by bencaradocdavies**
…ed black

https://osgeo-org.atlassian.net/browse/GEOT-5487

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
Ooh, Travis CI not happy. A gt-jdbc failure and a possible JVM crash in gt-xsd-wfs! I will re-run.

**Comment by bencaradocdavies** [comment]
OK, I think I have fixed the log flooding that was breaking Travis CI on master https://github.com/geotools/geotools/commit/12844adebde2e5820f7f97f21c2dbd5b95f087f8 so I have restarted the Travis CI build for this PR.

**Comment by bencaradocdavies** [comment]
The gt-jdbc failure is a Mockito error, which does not fail locally for me:
From: https://s3.amazonaws.com/archive.travis-ci.org/jobs/151988043/log.txt
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.146 sec <<< FAILURE! - in org.geotools.jdbc.JDBCTransactionStateTest
testSetTransactionNullWithExternalConnection(org.geotools.jdbc.JDBCTransactionStateTest)  Time elapsed: 0.012 sec  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.geotools.jdbc.JDBCTransactionStateTest.setupLogHandler(JDBCTransactionStateTest.java:64)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. although stubbed methods may return mocks, you cannot inline mock creation (mock()) call inside a thenReturn method (see issue 53)

	at org.geotools.jdbc.JDBCTransactionStateTest.setupLogHandler(JDBCTransactionStateTest.java:73)
```

**Comment by bencaradocdavies** [comment]
I cannot reproduce the gt-jdbc error locally, in Eclipse, or with Maven with OpenJDK or Oracle JDK 8u102, 8u92, or 8u31 (the last being that used on Travis CI). This one has be stumped. I have kicked the Travis CI build again.

**Comment by bencaradocdavies** [comment]
@aaime this is a change to your continuous map wrapping implementation in ```ProjectionHandler```; I would value your opinion. Kind regards, Ben.

**Comment by aaime** [comment]
Hi @bencaradocdavies I definitely want to have a look, but this week I'm totally overwhelmed (FOSS4G preps, very few people not vacationing in the company). I'll see what I can do, worst case I'll probably find some time to look into it during FOSS4G itself?

**Comment by bencaradocdavies** [comment]
@aaime no urgency, I just wanted to let you know that I will not be merging this one until you have had a chance to look at it. I know August is the holiday month in Italy (from my one visit in July 1998). Enjoy FOSS4G!

**Comment by bencaradocdavies** [comment]
@aaime I rebased this one to get a fresh Travis CI check.

**Comment by aaime** [comment]
Makes sense, merged. Backport as you see fit.

**Pull request merged**
