### PR TITLE
[GEOT-6800] Fix buffer underflow exception when reading shapefiles

### PR DESCRIPTION
**Pull request by tlbeale**
GEOT-6740 fixed a buffer underflow exception when reading shapefile
data - the problem was the code tried to read the M-value data
regardless of whether M data was present in the shapefile.

However, the fix was incomplete - it only checked there was one more
double value remaining. The code would actually try to read a lot more M
data than that. An example would be if the buffer contained a large
shape (e.g. a circle) that was followed by a much smaller shape (e.g. a
rectangle). In this case there's still more data remaining in the buffer,
but not enough to match the numPoints in the shape.

The fix is to check there as *at least* the expected amount of M-value
data still remaining in the buffer before trying to read it.

Test data files were updated so that they trigger the exception. Note
that the order of shapes can be important - we usually want a large
shape followed by a small shape.
- zpolygons.shp: added a circle followed by a rectangle
- zmultipoints.shp: added a large multipoint shape, followed by a
  single point.
- zlines.shp: added a line with a lot of points, followed by a short
  line.

Note the test data currently has both a polygonz.shp (single shape) and
zpolygons.shp (multiple shapes), and likewise for lines and
multipoints. This problem needed multiple shapes present in the
shapefile, so I've amended those files. I've also added them back to
the test case assertions, as the test code was no longer actually
using them.

<Include a few sentences describing the overall goals for this Pull Request>

# Checklist

Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not causing two modules to share the same Java packages (to avoid [Java 9+ split package](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed) issues)
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [x] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [x] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by aaime** [comment]
The fix looks legit, tests too. But cannot merge without a CLA signed and sent to OSGeo. Please let us know when you have done it.

**Comment by tlbeale** [comment]
OK, sure. I'm just getting our legal person to update the developers listed on the schedule for our corporate contributor's agreement so that I'm included. Hopefully it shouldn't be too far away.

**Comment by tlbeale** [comment]
Should be good to go now, CLA-wise.

**Comment by aaime** [comment]
@tlbeale could you send me the updated CLA by mail? I did not get any notification from OSGeo yet (it might take a few days)

**Comment by tlbeale** [comment]
Sure thing, I've mailed you the CLA now. Let me know if there are any problems with it

**Comment by aaime** [comment]
Got it. Merged. If you so desired, you can issue backports PRs for 25.x (just created) and 24.x. The 23.x branch does not have scheduled releases anymore (thought, unscheduled releases sometimes do happen, cannot say if 23.x will have one).

**Pull request merged**
