### PR TITLE
Remove entries when removing feature tables

### PR DESCRIPTION
**Pull request by jericks**
Solves issue #GEOT-4980.

### CODE REVIEW

**Comment by jodygarnett** [comment]
This looks okay to me, anyone else for a review?

**Comment by jdeolive** [comment]
Yup, looks good. Jared go ahead and merge. If you want to back port to 12.x that would be great as well. Thanks!

**Comment by jericks** [comment]
Thanks Jody and Justin.  I can back port, what is the preferred method?  Just cherry pick to 12.x and push or to send another pull request against 12.x (like https://github.com/geotools/geotools/pull/673).

**Comment by jdeolive** [comment]
I would say no pull request needed. Just go ahead and cherry-pick and push directly. What I usually do is reference this pull request from your cherry-picked commit (with git commit --amend) so that it shows up attached to this pull request.

**Pull request merged**
