### PR TITLE
[GEOT-6106] Upgrade postgresql JDBC driver to 42.2.5

### PR DESCRIPTION
**Pull request by bradh**
I did a full build of geoserver against the modified geotools, but I don't have an online test environment, and it really does need that kind of test.

@bencaradocdavies Can you run the tests?

### CODE REVIEW

**Comment by mprins** [comment]
You probably want to jump to 42.2.5 since that was released this week

**Comment by aaime** [comment]
Hi @bradh, I'm at a conference away from my development machine, but it's not hard to run online tests, roughly:

- Prepare a postgis database that is empty and a user that can do whatever on it (create/delete tables/indexes/views/sequences/anything else)
- Run tests once from the IDE, or from maven with -Ponline, they will skip, look in your home directory, you should find a .geotools/postgis.properties.example (or something like that)
- Change the filename to postgis.propeties, fill good values, and re-run
Not all tests may not pass, there are some checking brand new database creations, others might need an extension to be installed, but hopefully it should give you a good idea

**Comment by bradh** [comment]
I have updated this to 42.2.5. The online tests for postgis (well jdbc-postgis) ran with no errors or failures.

**Comment by bradh** [comment]
Have now got the right configuration - now `-Ponline` passes.

**Comment by aaime** [comment]
Merging on master, let's have a look at what the online test build says.

**Pull request merged**
