### PR TITLE
Complex Feature Parsing

### PR DESCRIPTION
**Pull request by NielsCharlier**
Continuation of https://github.com/geotools/geotools/pull/406, merged, updated, concerns addressed, squashed.

### CODE REVIEW

**Comment by NielsCharlier** [comment]
https://github.com/geoserver/geoserver/pull/1064 must also be merged or geoserver breaks

**Comment by bencaradocdavies** [comment]
Thank very much @NielsCharlier. I am reviewing now. There is an unrelated failure in GeoServer wms on openjdk7 on master, but the GeoServer app-schema online tests pass against postgis with your changes. When we have the GeoServer wms failure fixed, I will complete the review of this PR.

**Comment by bencaradocdavies** [comment]
@NielsCharlier, that looks great. I will merge as soon as I have completed a full build with oraclejdk7 (I am not waiting for the unrelated gs-wms openjdk failure to be fixed).

Thanks @aaime and @jodygarnett for your reviews on the original PR https://github.com/geotools/geotools/pull/406

@Adam-Brown @riniangreani I hope you are pleased to see that @NielsCharlier has brought this one home. @victortey @joshvote might be interested as well.

@Adam-Brown your original proposal has been faithfully migrated to the new wiki by @jodygarnett 
https://github.com/geotools/geotools/wiki/ComplexFeature-Parsing-and-Building-Support

**Comment by bencaradocdavies** [comment]
Full builds of gt/gs and gs app-schema online tests against postgis all pass with oraclejdk7 so I have merged both pull requests. Thanks again @NielsCharlier.

**Pull request merged**
