### PR TITLE
Reformatting the entire ImageMosaic module (master)

### PR DESCRIPTION
**Pull request by dvntucker**
Reformatting the entire non-test source in ImageMosaic. Done with Eclipse + formatter.xml.

### CODE REVIEW

**Comment by jodygarnett** [comment]
This seems as expected!

**Comment by aaime** [comment]
Works for me, please commit a full reformat of the mosaic module on all 3 active branches at the same time (so, also 15.x and 14.x) so that don't get crazy doing backports of bugfixes or minor new features

**Comment by dvntucker** [comment]
Ok. Should be incoming this morning.

**Comment by dvntucker** [comment]
PRs ready for 15.x and 14.x

https://github.com/geotools/geotools/pull/1259
https://github.com/geotools/geotools/pull/1260

**Pull request merged**
