### PR TITLE
[GEOT-7107] Remove duplicate entries in pom.xml

### PR DESCRIPTION
**Pull request by bradh**
[GEOT-7107](https://osgeo-org.atlassian.net/browse/GEOT-7107) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Minor top-level cleanup.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [X] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [N/A] New unit tests have been added covering the changes.
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by bradh** [comment]
@jodygarnett These look to be an unintended part of https://github.com/geotools/geotools/commit/bf9793d00e525a5e70a01e2d50217cc73b8d85c2 - can you verify?

**Review by mprins — APPROVED** [review]

**Comment by jodygarnett** [comment]
> @jodygarnett These look to be an unintended part of [bf9793d](https://github.com/geotools/geotools/commit/bf9793d00e525a5e70a01e2d50217cc73b8d85c2) - can you verify?

looks like rebase and a conflict resolution caused some duplication; goal is to organize those into headings and sort to make properties easier to locate.

**Comment by jodygarnett** [comment]
thanks for the cleanup.

**Comment by jodygarnett** [comment]
For non-functional changes like docs and build clean it is not usually necessary to create a ticket.

**Pull request merged**
