### PR TITLE
[GEOT-5482]: NetCDF Coverage's SampleDimension description - backport to 14.x

### PR DESCRIPTION
**Pull request by dromagnoli**

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
The Maven build in fact passed on Travis CI, and then something caused the Travis CI job to abort.

This fix looks small, straightforward, and suitable for 14.x.

**Comment by aaime** [comment]
Looking at the build, it fails on OSX, we have no champion to make that Travis build work, the others do build fine: https://travis-ci.org/geotools/geotools/builds/149712560

**Comment by dromagnoli** [comment]
Are we ok to merge it then? :)

**Comment by bencaradocdavies** [comment]
I thought OSX was a permitted failure? Why does Travis CI not permit it?

**Comment by aaime** [comment]
Looks like it got stable and I commented out that section:
https://github.com/geotools/geotools/blame/14.x/.travis.yml

Time to uncomment it againt?

**Comment by bencaradocdavies** [comment]
@dromagnoli I was waiting to give others a chance to comment. Sometimes it it nice to comment on PRs *before* they are merged.  ;-)

**Comment by dromagnoli** [comment]
@bencaradocdavies no rush on my side :-)
My previous comment was related to the fact that OSX frequently fails so my intention was asking if it was a blocker for the merge :)

Let's wait for other comments.

**Comment by bencaradocdavies** [comment]
Thanks @dromagnoli, looks good to me, and already merged on master and 2.9.x.

**Pull request merged**
