### PR TITLE
[GEOT-6819] lazy access to filterFactory

### PR DESCRIPTION
**Pull request by fgdrf**
[GEOT-6819](https://osgeo-org.atlassian.net/browse/GEOT-6819) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

to avoid deadlock at initialization

Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

<Include a few sentences describing the overall goals for this Pull Request>

# Checklist

Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not causing two modules to share the same Java packages (to avoid [Java 9+ split package](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed) issues)
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [x] There is an issue [GEOT-6819](https://osgeo-org.atlassian.net/browse/GEOT-6819) in jira describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by aaime** [comment]
Getting factories in static initializers is very common as the lookup of the factories is slow and does not scale.. there lots of other places where this is done. Could you have a look at solving the deadlock instead? This fix is specific to your case, but if you are having a concurrent setup somewhere, it's gonna pop up due to other classes, either down the road, or due to different timings when executing on other machines.

**Comment by fgdrf** [comment]
> 
> 
> Getting factories in static initializers is very common as the lookup of the factories is slow and does not scale.. there lots of other places where this is done. Could you have a look at solving the deadlock instead? This fix is specific to your case, but if you are having a concurrent setup somewhere, it's gonna pop up due to other classes, either down the road, or due to different timings when executing on other machines.

Not sure if I understood you correctly, are you asking for finding similiar patterns where static final fields are initialized using ` org.geotools.factory.CommonFactoryFinder`?

IMHO this fix solves this potential deadlock - and you are right for this specific case. However, just let's take a bite instead changing other classes in the same changeset. Would you agree?

**Comment by fgdrf** [comment]
@aaime Thanks for your quick response. Just a question regarding the failed Linux build. Is this a known issue for other PR's as well? IMO

```Error:  Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project geotools: Execution default-clean of goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean failed: Plugin org.apache.maven.plugins:maven-clean-plugin:3.1.0 or one of its dependencies could not be resolved: Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:2.0.4 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar: Connection reset -> [Help 1]```

seems to be a problem in the VM setup or caused by a network issue. How do we deal with it? re-trigger the checks?

**Comment by aaime** [comment]
There should not be any deadlock (in theory, I believe you found one). Can you write a test to show how it happens? A test is mandatory for PRs to be merged, anyways.

**Comment by fgdrf** [comment]
I'd like to add the thread-dump from udig-platform product here:
```
"LayerFactory" #102 daemon prio=5 os_prio=0 tid=0x000000001b681800 nid=0x3158 in Object.wait() [0x0000000028ead000]
   java.lang.Thread.State: RUNNABLE
	at org.geotools.filter.function.CategorizeFunction.<init>(CategorizeFunction.java:126)
	at org.geotools.filter.function.CategorizeFunction.<init>(CategorizeFunction.java:99)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.geotools.util.factory.FactoryRegistry.register(FactoryRegistry.java:962)
	at org.geotools.util.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:858)
	at org.geotools.util.factory.FactoryRegistry.scanForPluginsIfNeeded(FactoryRegistry.java:888)
	at org.geotools.util.factory.FactoryRegistry.getFactories(FactoryRegistry.java:251)
	- locked <0x00000000fd56c710> (a org.geotools.util.factory.FactoryCreator)
	at org.geotools.factory.CommonFactoryFinder.getFunctions(CommonFactoryFinder.java:134)
	- locked <0x00000000fd56c7a0> (a java.lang.Class for org.geotools.factory.CommonFactoryFinder)
	at org.geotools.filter.function.DefaultFunctionFactory.loadFunctions(DefaultFunctionFactory.java:143)
	at org.geotools.filter.function.DefaultFunctionFactory.functionCache(DefaultFunctionFactory.java:102)
	- locked <0x00000000fd56c828> (a org.geotools.filter.function.DefaultFunctionFactory)
	at org.geotools.filter.function.DefaultFunctionFactory.getFunctionNames(DefaultFunctionFactory.java:60)
	at org.geotools.filter.FunctionFinder.lookupFunctions(FunctionFinder.java:249)
	at org.geotools.filter.FunctionFinder.findFunctionInternal(FunctionFinder.java:222)
	- locked <0x00000000fcd21aa0> (a org.geotools.filter.FunctionFinder)
	at org.geotools.filter.FunctionFinder.findFunction(FunctionFinder.java:196)
	at org.geotools.filter.FunctionFinder.findFunction(FunctionFinder.java:153)
	at org.geotools.filter.FunctionFinder.findFunction(FunctionFinder.java:129)
	at org.geotools.filter.FilterFactoryImpl.function(FilterFactoryImpl.java:818)
	at org.geotools.feature.AttributeTypeBuilder.lengthRestriction(AttributeTypeBuilder.java:571)
	at org.geotools.feature.AttributeTypeBuilder.buildType(AttributeTypeBuilder.java:394)
	at org.geotools.feature.AttributeTypeBuilder.buildDescriptor(AttributeTypeBuilder.java:464)
	at org.geotools.data.shapefile.ShapefileFeatureSource.readAttributes(ShapefileFeatureSource.java:573)
	at org.geotools.data.shapefile.ShapefileFeatureSource.buildFeatureType(ShapefileFeatureSource.java:481)
	at org.geotools.data.shapefile.ShapefileFeatureStore.buildFeatureType(ShapefileFeatureStore.java:137)
	at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:327)
	- locked <0x00000000fce89e60> (a org.geotools.data.store.ContentState)
	at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:296)
	at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:105)
	at org.locationtech.udig.catalog.internal.shp.ShpGeoResourceImpl.style(ShpGeoResourceImpl.java:172)
	at org.locationtech.udig.catalog.internal.shp.ShpGeoResourceImpl.resolve(ShpGeoResourceImpl.java:153)
	at org.locationtech.udig.project.internal.impl.LayerResource.processResourceCachingStrategy(LayerResource.java:308)
	at org.locationtech.udig.project.internal.impl.LayerResource.resolve(LayerResource.java:173)
	- locked <0x00000000fcee9310> (a org.locationtech.udig.project.internal.impl.LayerResource)
	at org.locationtech.udig.style.sld.SLDContent.createDefaultStyle(SLDContent.java:220)
	at org.locationtech.udig.project.internal.SetDefaultStyleProcessor.process(SetDefaultStyleProcessor.java:45)
	at org.locationtech.udig.core.internal.ExtensionPointUtil.process(ExtensionPointUtil.java:77)
	at org.locationtech.udig.project.internal.SetDefaultStyleProcessor.run(SetDefaultStyleProcessor.java:53)
	at org.locationtech.udig.project.internal.impl.SetStyleInterceptor.run(SetStyleInterceptor.java:33)
	at org.locationtech.udig.project.internal.impl.LayerFactoryImpl.runLayerCreatedInterceptor(LayerFactoryImpl.java:430)
	at org.locationtech.udig.project.internal.impl.LayerFactoryImpl.createLayer(LayerFactoryImpl.java:409)

"Worker-3: Rendering" #67 daemon prio=5 os_prio=0 tid=0x00000000165a5000 nid=0xf14 waiting for monitor entry [0x000000002138e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:258)
	- waiting to lock <0x00000000fd56c7a0> (a java.lang.Class for org.geotools.factory.CommonFactoryFinder)
	at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:213)
	at org.geotools.factory.CommonFactoryFinder.getFilterFactory2(CommonFactoryFinder.java:299)
	at org.geotools.factory.CommonFactoryFinder.getFilterFactory2(CommonFactoryFinder.java:312)
	at org.geotools.filter.FilterAttributeExtractor.<clinit>(FilterAttributeExtractor.java:51)
	at org.locationtech.udig.render.internal.feature.basic.BasicFeatureRenderer.getExpandSizeFromStyle(BasicFeatureRenderer.java:271)
	at org.locationtech.udig.render.internal.feature.basic.BasicFeatureRenderer.getStyle(BasicFeatureRenderer.java:241)
	at org.locationtech.udig.render.internal.feature.basic.BasicFeatureRenderer.prepareDraw(BasicFeatureRenderer.java:160)
	at org.locationtech.udig.render.internal.feature.basic.BasicFeatureRenderer.render(BasicFeatureRenderer.java:349)
	at org.locationtech.udig.render.internal.feature.basic.BasicFeatureRenderer.render(BasicFeatureRenderer.java:312)
	at org.locationtech.udig.project.internal.render.impl.RenderJob.startRendering(RenderJob.java:134)
	at org.locationtech.udig.project.internal.render.impl.RenderJob.run(RenderJob.java:258)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
````

Scenario: two bundles are loading content in different threads the first one added a layer which caused the renderer to start, the second one tries to read SLD from a file. See lock 0x00000000fd56c7a0

IMHO, I cannot provide a Test-Case for this scenario. My understanding is that it should be avoided to initialize static fields with method calles that execute synchronized code.

An approach could be having a internal static class that holds the field. This class is not loaded from any classloader unless invoked in e.g. visit-method of FilterAttributeExtractor:

```
    private static final class FilterFactory2Holder {
        static final FilterFactory2 FF = CommonFactoryFinder.getFilterFactory2();
    }

[..]

                    if (name != null) {
                        attributeNames.add(name);
                        propertyNames.add(FilterFactory2Holder.FF.property(name));
                        foundLiteral = true;
                    }
[..]
```
This is thread-safe rathe than having a private static method to initialize FilterFactory2 lazily.

I've analyzed the geotools (22.1 tag which is currently used in uDig) where other final static initializations are used accessing CommonFactoryFinder, here is the list:
- org.geotools.arcsde.filter.ArcSdeSimplifyingFilterVisitor
- org.geotools.brewer.color.StyleGenerator
- org.geotools.brewer.styling.builder.AbstractSLDBuilder
- org.geotools.data.DataUtilities
- org.geotools.data.Join
- org.geotools.data.complex.filter.UnmappingFilterVisitor
- org.geotools.data.jdbc.FilterToSQL
- org.geotools.data.store.ReprojectingFeatureCollection
- org.geotools.data.transform.Definition
- org.geotools.data.transform.TransformFeatureSource
- org.geotools.data.transform.Transformer
- org.geotools.feature.visitor.SumAreaVisitor
- org.geotools.filter.FilterAttributeExtractor
- org.geotools.filter.FilterDOMParser
- org.geotools.filter.FunctionImpl
- org.geotools.filter.function.EqualAreaFunction
- org.geotools.filter.function.InterpolateFunction
- org.geotools.filter.function.RecodeFunction
- org.geotools.gce.imagemosaic.Utils
- org.geotools.gce.imagemosaic.catalog.GranuleCatalogStore
- org.geotools.process.vector.ClassifyByRangeProcess
- org.geotools.process.vector.FeatureClassStats
- org.geotools.renderer.lite.CompositingGroup
- org.geotools.renderer.lite.GraphicsAwareDpiRescaleStyleVisitor
- org.geotools.renderer.lite.RenderingTransformationHelper
- org.geotools.renderer.lite.StreamingRenderer
- org.geotools.renderer.lite.ZGroupLayerFactory
- org.geotools.renderer.style.ExpressionExtractor
- org.geotools.renderer.style.SLDStyleFactory
- org.geotools.styling.SLD
- org.geotools.styling.visitor.Measure
- org.geotools.swing.styling.JFontChooser
- org.geotools.swing.styling.JFontChooser
- org.geotools.swing.styling.JSimpleStyleDialog
- org.geotools.swing.tool.FeatureLayerHelper
- org.geotools.validation.xml.ArgHelper
- org.geotools.wfs.PropertyValueCollection
- org.geotools.xml.styling.SLDParser
- org.geotools.xml.styling.SLDTransformer
- org.geotools.xml.styling.SLDTransformer

Finally:
- Could anyone join and help providing a testcase for this. IMO it requires to have its own Classloader(s) to make sure CommonFactoryFinder haven't initialized already (in another test-case).
- would you accept Holder-Class aproach w/o any testcase?

**Comment by aaime** [comment]
"My understanding is that it should be avoided to initialize static fields with method calles that execute synchronized code."

I tried to Google that, you seem to cite it as a well known bad practice.... could not find anything about it. To me it just looks like any other deadlock, the synchronizaton seems to be incomplete and probably needs to be fixed?
I've found a page about [initialization on demand holder](https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom), but it's talking mostly about better scalability, lower contention, in the context of lazy loading, I cannot find it used as a cure for deadlocks. 

Looking at stack traces, one of the threads is still runnable (weird, it looks like it should be blocked too?), a deadlock normally requires two threads... are those really all the threads involved in the deadlock?

The holder approach can work, but I'm not sold on having to modify all those classes, do the same across GeoServer as well (79 cases of grabbing filter factory in a static initializer there), and having to remember to do that every time in the future we need a static instance of a filter factory.

Can you point me to an existing explanation (article, blog) talking about this kind of classloader driven deadlock?

About tests, they can be skipped only if you can argue it's impossible to write a test... so far I don't see why not. Did you try setting up a thread with an executor service and multiple threads doing "stuff" in it that would cause the deadlock to appear? It does not need to fail systematically, just sometimes, as long as after the fix it never fails. We have a number of tests like that already in the code base, [here is an example](https://github.com/geotools/geotools/blob/f66689b5305eaf381e21dc2feec8011138d4cb24/modules/library/main/src/test/java/org/geotools/filter/function/FunctionFactoryTest.java#L134).

**Comment by McNepp** [comment]
The Stacktrace that @fgdrf posted actually shows the deadlock condition quite well.
But maybe some further explanation is helpful:
Even though the Thread "LayerFactory" is displayed as RUNNABLE, it is actually not progressing. 
If you look into the indicated Source location at `org.geotools.filter.function.CategorizeFunction.<init>(CategorizeFunction.java:126)`, you'll see that it tries to initialize
an instance of `org.geotools.filter.FilterAttributeExtractor`. This requires the class to be loaded and initialized. However, the other Thread "Worker-3" is already doing exactly that.
Unfortunately, it is stuck on acquiring the static monitor from `org.geotools.factory.CommonFactoryFinder`, which in turn is held by "LayerFactory".
So, this is not a deadlock between two Java Monitors, but between one Java Monitor and an internal "Class Initialization Lock"!
For another, simplified example, please see 
https://stackoverflow.com/questions/53682182/class-initialization-deadlock-mechanism-explanation

**Comment by aaime** [comment]
@McNepp the explanation is useful, thank you, never saw anything like that before.

Replying "The Stacktrace that @fgdrf posted actually shows the deadlock condition quite well. But maybe some further explanation is helpful:" after I politely asked for help understanding it, is condescending, and a possible a violation of our code of conduct, please be mindful of your language in the future: https://github.com/geotools/geotools/blob/main/CODE_OF_CONDUCT.md

That said... is spreading a holder pattern in around a hundred classes (GT+GS) the only solution?

**Comment by McNepp** [comment]
> Replying "The Stacktrace that @fgdrf posted actually shows the deadlock condition quite well. But maybe some further explanation is helpful:" after I politely asked for help understanding it, is condescending, and a possible a violation of our code of conduct, please be mindful of your language in the future: https://github.com/geotools/geotools/blob/main/CODE_OF_CONDUCT.md

I am truly sorry that you might think of me as "condescending", which was, of course, not my intent at all. However, I am also sad that your overzealous reference to some "code of conduct" that I may have **violated** with my very first post on Github discourages me from write here again.

**Comment by fgdrf** [comment]
I'd prefer to focus on runtime-code rather than test-code. The problem I see is: if we accept this pull request, how can we deal with code changes in the future which might bring the back the static final initaltization 

`private static final FilterFactory filterFactory = CommonFactoryFinder.getFilterFactory(null);`

I wonder if a check (maybe a checkstyle check with [regexpr](https://checkstyle.sourceforge.io/config_regexp.html)) might help to report a warning with a hint in the message how to deal with it?

**Comment by fgdrf** [comment]
> That said... is spreading a holder pattern in around a hundred classes (GT+GS) the only solution?

I'd prefer to focus on code which is used at runtime rather than test-code. The problem I see is: if we accept that this pattern helps in this case, how can we deal with code changes in the future which might bring the current aproach back into codebase. 

I wonder if a check (maybe a checkstyle check with [regexpr](https://checkstyle.sourceforge.io/config_regexp.html)) might help to report a warning with a hint in the message how to deal with it?

**Comment by aaime** [comment]
@fgdrf I appreciate that you come from a different project with different rules. The GeoTools ones are stated in the PR checklist. That involves writing a test. I invite you to look at the last few hundred pull requests, please tell me how many were merged without a test (for the ones involved in app-schema you'll have to look for an integration test in GeoServer, which is still covered against regressions by the "integration build" here in GeoTools).

That does not mean the requirement for a test is an absolute, it can be discussed, but only after you tried and failed to write a test, and someone verified it's indeed impossible or too complicated to write.

Going to the kind of check you were suggesting, checkstyle does not seem the right tool, PMD would be more suitable I think. One can write custom tests that match a given xpath against an in-memory AST of the code. I've recently wrote one, it can be configured in our pmd ruleset, but I ended up contributing it back to the [PMD project](https://github.com/pmd/pmd/pull/3193/files#diff-70edb5554461fe03258d761ee7822c195542b50a283f2b24c463b74ce305f4fcR1834) instead.

Speaking about the fix, are you sure modifying all static accesses to the factories is the only working approach? There are over a hundred of them between GeoTools and GeoServer. I believe part of the issue is that the finder is synchronizing [against the class itself](https://github.com/geotools/geotools/blob/1fed12f88ab0c9d4ef92aa9cf73af8f94d5c1291/modules/library/main/src/main/java/org/geotools/factory/CommonFactoryFinder.java#L246)
Can it be done in a different way? Thinking out loud, would using a private synchronized method instead of explict synch make any difference (I doubt it but worth trying). How about using the holder class pattern to create the object used for synchronizations instead in CommonFactoryFinder, would that be any better? Having a test would ease significantly trying out alternatives (and as said, it's mandatory to have it, anyways).

**Pull request closed without merging**
