### PR TITLE
Run Oracle online tests on Travis-CI using Oracle XE

### PR DESCRIPTION
**Pull request by mprins**
This brings "online" testing of the Oracle JDBC module on Travis-CI using a dockerized Oracle XE.

This builds on top of #2832 because the master branch requires special setup with the old/ proprietary-download driver.

fixes https://osgeo-org.atlassian.net/browse/GEOT-6563

disabled `OracleAggregateFunctionOnlineTest#testStoreChecksVisitorLimits()` because it does't work.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by aaime** [comment]
I merged the Oracle driver update PR, hoping it was containing the same commit as this one, but now it's having a conflict. Should I revert the merge and go ahead with this one instead?

**Comment by mprins** [comment]
This PR contains the commits from #2832, but with additional changes..
I'll fix the conflicts

**Comment by aaime** [comment]
Lost track of this one. I see it's failing on an Oracle test:

```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.499 s <<< FAILURE! - in org.geotools.data.oracle.OraclePrimaryKeyFinderOnlineTest
[ERROR] testSequencedPrimaryKey(org.geotools.data.oracle.OraclePrimaryKeyFinderOnlineTest)  Time elapsed: 4.727 s  <<< FAILURE!
junit.framework.AssertionFailedError
```

**Comment by mprins** [comment]
I'll see if a rebase fixes that, pretty sure this test passed last time I committed, but rebased a few times.
I won't have a machine at hand that can run either docker or oracle until after the weekend.

**Comment by aaime** [comment]
Looks like the same test is still failing. You may already know, just noticed there were commits and pushes since we last talked.

**Comment by mprins** [comment]
so far I've not been able to reproduce the failure locally :unamused: 

travis failure is here:
https://github.com/geotools/geotools/blob/7644a4d0b4eabc0ac204e4f7d58a4786e9d17f44/modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCPrimaryKeyFinderOnlineTest.java#L95-L97

but locally I always get a pass..

added a commit with some diagnostic

**Comment by mprins** [comment]
:bomb: great so oracle now passed... mssql failed during apit install, so a restart in a while should fix that.

What to do with that last commit?

**Comment by jodygarnett** [comment]
I have restarted travis, the failure in mysql:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
526
```
Is that in anyway related to the changes you are making?

**Comment by mprins** [comment]
@jodygarnett Nope, generally it means ther eis a network disruption of some sort, I often see these in other projects running on Travis when eg. Maven is downloading all deps. and their mirror gets overloaded or on big downloads like in this case possibly the ms sql server installer

**Comment by aaime** [comment]
Uuuh green, let me merge this one right now!

**Pull request merged**
