### PR TITLE
Resolve NullPointerException when GridCoverage is outside of view area

### PR DESCRIPTION
**Pull request by matchami**
Superceeds 1204 (change target from 15.x to master)

### CODE REVIEW

**Comment by matchami** [comment]
This pull request superceeds 1204 which was targetting the branch instead of the master

**Comment by bencaradocdavies** [comment]
@matchami cross-branch merges such as this are not permitted in this project. Please create a new feature branch from the current master, cherry-pick your changes onto it, and make a new pull request:
http://docs.geotools.org/latest/developer/procedures/git.html#porting-changes-across-primary-branches

**Comment by matchami** [comment]
Hi Ben,
I was instructed to do this by Andrea Aime.  Please could you review the original 1204 and confirm that this is still the best option
thanks

**Comment by bencaradocdavies** [comment]
@matchami I have read #1204 and agree with the instructions given by @aaime. Your pull request does a great deal more: it attempts to merge the entire 15.x branch into master. I can assure you that this is not what @aaime meant in his instructions.

The clue that something is wrong is that this PR includes (1) unrelated work and (2) GitHub merge commits. A correct PR for this issue should contain only the changes that you are trying to make and no GitHub merge commits from other PRs.

Cross-branch merges such as this are not permitted in the GeoTools project because they complicate commit history and produce a tangle of unnecessary commits. Please create a new feature branch from the current master, cherry-pick your changes onto it, and make a new pull request, following the instructions in the developer manual:
http://docs.geotools.org/latest/developer/procedures/git.html#porting-changes-across-primary-branches

You can cherry-pick your original 5 commits onto your new feature branch, or even better, you can squash them into a single commit for clarity. Do you have a Jira issue? If so, please include the tag in the PR title, or even better, make the tag and title the same as Jira. Every commit should have the Jira tag. I recommend making all your changes in one commit.

**Comment by bencaradocdavies** [comment]
@matchami I found your Jira issue:

[GEOT-5421] NullPointerException when GridCoverage goes offscreen
https://osgeo-org.atlassian.net/browse/GEOT-5421

I use a nice trick @aaime once showed me: in Jira use Export / XML to get the nicely formatted title. I like to set my commit title to match this nicely formatted Jira title.

**Comment by matchami** [comment]
Thanks Ben, that's really helpful.  I am completely new to git (we use svn still) so I was a little at sea trying to understand all this.

**Comment by bencaradocdavies** [comment]
You are welcome, Ian. I also learned git through this project. Quite a mind-blowing experience, but very much worthwhile.

**Pull request closed without merging**
