### PR TITLE
FlatGeobuf: Upgrade deps

### PR DESCRIPTION
**Pull request by bjornharrtell**
# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Failures are due to a bytecode incompatiblity. Will need to be fixed in flatbuffers dependency.

**Comment by aaime** [comment]
So the code is compatible with Java 11, but not with Java 8, right? That is, for the moment, a no-go.

**Comment by bjornharrtell** [comment]
@aaime it's in the works just waiting for a patch release of flatbuffers (with fix https://github.com/google/flatbuffers/issues/6763)

**Comment by aaime** [comment]
We are just about to cut the new stable branch, how goes this one?

**Comment by bjornharrtell** [comment]
@aaime, unfortunately not yet done upstream because of vacations etc.

**Comment by aaime** [comment]
"Peace and love", we all deserve some rest :-D

**Comment by bjornharrtell** [comment]
This is now ready. I don't think the downstream integration build fail has anything to do with this.

**Comment by mprins** [comment]
> This is now ready. I don't think the downstream integration build fail has anything to do with this.

agree.

```
2021-09-04T15:54:37.8614225Z [ERROR] Failures: 
2021-09-04T15:54:37.8615682Z [ERROR]   GWCSettingsPageTest.testNewDefaultGridSet:334 expected:<[EPSG:4326x2]> but was:<[CanadianNAD83_LCC]>
```

also seen on other merged PR's like #3619

**Comment by aaime** [comment]
> > This is now ready. I don't think the downstream integration build fail has anything to do with this.
> 
> agree.
> 
> ```
> 2021-09-04T15:54:37.8614225Z [ERROR] Failures: 
> 2021-09-04T15:54:37.8615682Z [ERROR]   GWCSettingsPageTest.testNewDefaultGridSet:334 expected:<[EPSG:4326x2]> but was:<[CanadianNAD83_LCC]>
> ```
> 
> also seen on other merged PR's like #3619

Should be fine now, apologies!
https://github.com/geoserver/geoserver/pull/5242

**Pull request merged**
