### PR TITLE
[GEOT-6009] Make WMTS tests online 

### PR DESCRIPTION
**Pull request by ianturton**
[GEOT-6009](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6009) is fixed (sort of) by this PR. 

We need to revisit this with some more reliable WMTS servers to test against.

### CODE REVIEW

**Comment by tbarsballe** [comment]
Closing and re-opening in an attempt to fix the Travis CI failure.

**Comment by tbarsballe** [comment]
Looks like one of the files in this PR doesn't conform to our code formatting guidelines:

> [ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-wmts: Found 1 non-complying files, failing build

Please run `mvn clean install` locally, and recommit

**Comment by aaime** [comment]
Seems legit, but I did not know the old tests well. @etj do you have time for a quick look?

**Comment by ianturton** [comment]
Since we are seeing Jenkins failures related to these tests I'm going to merge now.

**Pull request merged**
