### PR TITLE
[GEOT-7473] Update or remove API diagrams

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-7473](https://osgeo-org.atlassian.net/browse/GEOT-7473) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  
This is a non functional change to documentation.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ x First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Looks like legit doc build failures:

```
2023-10-13T01:21:18.4884344Z      [echo] Running sphinx-build -D release=31-SNAPSHOT -q -W --keep-going -j auto -b html -d "/home/runner/work/geotools/geotools/docs/target/user/doctrees" . "/home/runner/work/geotools/geotools/docs/target/user/html"
2023-10-13T01:21:24.1086048Z      [exec] /home/runner/work/geotools/geotools/docs/user/tutorial/feature/csv2shp.rst:316: WARNING: image file not readable: tutorial/feature/images/Feature.png
2023-10-13T01:21:24.1089072Z      [exec] /home/runner/work/geotools/geotools/docs/user/library/main/datastore.rst:147: WARNING: image file not readable: images/DataAccess.png
2023-10-13T01:21:24.1091715Z      [exec] /home/runner/work/geotools/geotools/docs/user/library/main/datastore.rst:194: WARNING: image file not readable: images/SimpleFeatureSource.PNG
2023-10-13T01:21:24.1094454Z      [exec] /home/runner/work/geotools/geotools/docs/user/library/main/datastore.rst:359: WARNING: image file not readable: images/SimpleFeatureStore.PNG
2023-10-13T01:21:24.1097165Z      [exec] /home/runner/work/geotools/geotools/docs/user/library/main/datastore.rst:419: WARNING: image file not readable: images/SimpleFeatureLocking.PNG
```

Seems case sensitivity issue in file names (to be more precise, in the extensions)?

**Comment by jodygarnett** [comment]
This is technical debt from the API migration; I am a bit sad this activity was not "fully funded" and has left cleanup work behind.

I wonder if it is better to just remove outdated diagrams, this would be a good SoC student activity.

**Comment by jodygarnett** [comment]
Yeah I don’t know how to update diagrams without a geotools workshop planned

**Comment by aaime** [comment]
Every time you comment on an issue the stale bot resets and it busy more time for the PR. But why keep a stale PR open for so long, what's the point? Is should be clear the work at hand does not match your priorities and available time by now...

**Comment by jodygarnett** [comment]
So I am left with a value judgement; better to remove the diagrams (something I can do now) or leave in correct (but perhaps helpful guidance).

**Pull request closed without merging**
