### PR TITLE
[GEOT-7693] CenterLine process can leave gaps in the skeletonisation

### PR DESCRIPTION
**Pull request by SuperChrisliu**
fix bug: One edge is missing during the process of iterating over all triangle edges to generate the skeleton from a polygon.

Due to the lack of an edge, the generated Skeleton line is disconnected and incomplete.
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

### CODE REVIEW

**Comment by ianturton** [comment]
This needs a unit test,

**Comment by aaime** [comment]
Strickly speaking no, since this is an unsupported module... but it would be really nice if it has both a test and a Jira ticket, yes.

**Comment by ianturton** [comment]
or at least some more explanation of why this is a bug - though to be fair I can't recall why I used a loop from 1 to 1 less than the number of points.

**Comment by SuperChrisliu** [comment]
Skeleton and Polygon：


CentreLine and Polygon

**Comment by SuperChrisliu** [comment]
test polygon：

```

MULTIPOLYGON(((120.80169900000001 31.297886399999996,120.80097670000005 31.293265699999996,120.80282419999999 31.2928106,120.80286569999998 31.2928167,120.80291059999999 31.292809100000003,120.8029532 31.292789399999997,120.80323829999999 31.2925646,120.80400439999998 31.2933301,120.80462699999997 31.2931495,120.80569649999998 31.293003700000003,120.80648309999998 31.293342799999998,120.80674020000002 31.293341500000007,120.80708889999998 31.293267,120.80774670000002 31.293147600000008,120.80799629999997 31.2930084,120.80919109999999 31.2929037,120.80929960000003 31.292944299999995,120.80946230000002 31.292995199999993,120.80962819999999 31.293018799999995,120.80992409999998 31.2930027,120.81056489999999 31.292882199999998,120.8109192 31.2926822,120.8113853 31.292410100000012,120.81211360000002 31.292453900000005,120.81225130000003 31.292533499999998,120.8127673 31.2924733,120.81314280000001 31.292234999999994,120.81327999999998 31.291947699999998,120.8138513 31.291805200000002,120.81399980000003 31.2919241,120.8148881 31.291637999999995,120.81493510000001 31.291575300000005,120.81495409999998 31.291401799999996,120.81499039999997 31.291359600000003,120.81528639999999 31.291283999999994,120.81537910000004 31.2913713,120.815479 31.291427699999996,120.81561790000005 31.2914734,120.8158566 31.2914847,120.8165599 31.2914069,120.81737169999997 31.2912619,120.81742270000001 31.291223999999993,120.81744749999999 31.2911444,120.8178576 31.29102670000001,120.81801210000005 31.291153899999998,120.81839029999998 31.2909374,120.81832840000001 31.290828399999995,120.8185692 31.290703100000005,120.81890430000003 31.290300199999994,120.8204452 31.289993199999994,120.82045789999997 31.2901119,120.8204254 31.2902961,120.82032589999999 31.2903679,120.82033210000003 31.290591300000003,120.82038139999999 31.2906208,120.8204674 31.290629899999992,120.82056989999998 31.290597499999997,120.82083419999998 31.29042460000001,120.82158409999997 31.2902469,120.82216559999999 31.29031190000001,120.82275010000002 31.290299800000007,120.82468080000001 31.2896686,120.82585270000004 31.289314599999997,120.8269587 31.289144999999998,120.82821540000002 31.288717699999996,120.82836369999997 31.2882539,120.8283577 31.287648199999996,120.82947350000003 31.28571360000001,120.82924819999997 31.285172699999997,120.8293125 31.284915999999985,120.8293769 31.28400819999999,120.8295378 31.28402660000001,120.83005279999998 31.284925100000006,120.83207709999998 31.283917799999994,120.83383989999999 31.282978000000007,120.83386410000003 31.2829651,120.83496929999998 31.282741399999992,120.84086109999998 31.281549100000003,120.84370479999998 31.2820746,120.84410599999997 31.282172600000003,120.84492080000001 31.282274000000005,120.8447921 31.2844104,120.84456609999998 31.284562800000007,120.84450959999997 31.284862199999985,120.84454969999997 31.285079100000004,120.84485800000002 31.285648999999996,120.8451555 31.285833699999998,120.84712250000003 31.2868186,120.84762789999998 31.2866587,120.84777500000003 31.28811530000001,120.84712250000003 31.289165499999996,120.8470063 31.290118300000003,120.84768350000003 31.29186899999999,120.84974339999998 31.294362700000008,120.85043 31.29817650000001,120.85075199999999 31.300458099999997,120.85143089999997 31.3009892,120.85121760000003 31.301744400000004,120.85120059999996 31.302009100000014,120.85128900000005 31.302310200000008,120.85131570000003 31.302653999999997,120.85245489999998 31.3043168,120.85301020000006 31.304642900000008,120.85355199999997 31.304994299999994,120.85394320000003 31.305000499999995,120.85432369999997 31.304793,120.85452660000004 31.304867499999997,120.8544338 31.305152600000003,120.85422350000003 31.30547,120.8539738 31.305850099999994,120.85381039999999 31.3059353,120.85377289999997 31.306176,120.85388339999999 31.306374699999996,120.85421890000003 31.306704399999997,120.85457069999998 31.3069488,120.8548821 31.30731979999999,120.85636530000001 31.308657,120.85745010000004 31.3093457,120.8566183 31.310193100000003,120.85570090000002 31.31123680000001,120.85459609999997 31.310578899999996,120.8542631 31.3103388,120.8535898 31.3094775,120.85326760000002 31.309205799999994,120.85278479999997 31.308797800000008,120.85222509999998 31.3083705,120.85176590000003 31.308107799999995,120.85146150000003 31.308025800000003,120.85108960000004 31.308002099999992,120.85076699999999 31.308005500000007,120.84971670000002 31.30718839999999,120.8494219 31.306385099999996,120.8494297 31.306100000000004,120.84897099999999 31.305386000000006,120.84869790000003 31.30504370000001,120.84843759999998 31.3040718,120.84821070000002 31.303750899999994,120.84813790000004 31.30314569999999,120.84778590000005 31.302648300000005,120.84747970000001 31.302084699999998,120.8474312 31.301764599999995,120.84750950000003 31.301571499999998,120.8477472 31.301291099999993,120.84778099999997 31.30118180000001,120.84775690000002 31.301082999999995,120.84762070000001 31.3009943,120.8475899 31.300901699999997,120.84764820000002 31.299250599999986,120.84758260000004 31.299104700000004,120.84715490000002 31.298710300000007,120.84700150000003 31.29829729999999,120.8470007 31.298124299999998,120.84717000000002 31.2975563,120.8470606 31.296690800000004,120.84686890000003 31.296160899999993,120.84647670000001 31.295579500000002,120.84639480000004 31.294278500000004,120.84613479999997 31.293578900000007,120.84372880000005 31.290108999999994,120.84334489999999 31.289737799999994,120.84267000000001 31.2888041,120.84218550000001 31.288333299999998,120.84216210000001 31.288324400000004,120.8421361 31.2883274,120.84211400000002 31.28833640000001,120.84203000000002 31.288498399999995,120.84177150000001 31.2884416,120.84164460000001 31.2880911,120.84150470000002 31.287849099999985,120.84110089999997 31.2875456,120.8407026 31.287315799999995,120.8404162 31.287163200000006,120.83944069999997 31.2867597,120.8393518 31.28673410000001,120.8384635 31.2866301,120.83830909999996 31.2866245,120.83817110000004 31.286633799999997,120.83755900000003 31.2867532,120.8369262 31.286955399999993,120.83663350000002 31.287082099999992,120.83618459999998 31.2873758,120.83589240000002 31.287623299999996,120.83540419999996 31.287791399999996,120.83507100000001 31.28794819999999,120.83484350000005 31.2880844,120.83464169999998 31.288246500000007,120.8346079 31.2882186,120.83353119999998 31.2890839,120.83314279999995 31.289362700000005,120.83200849999999 31.29037990000001,120.8318971 31.290455499999993,120.8297489 31.292279800000006,120.82962610000004 31.292377999999996,120.82951439999997 31.292435999999995,120.82942360000001 31.292469399999995,120.8293109 31.292497200000003,120.8290925 31.29253649999999,120.82901620000001 31.292554099999997,120.82824090000004 31.292914600000003,120.8278552 31.2931527,120.82778020000003 31.293216800000003,120.82770020000002 31.293277199999988,120.82743089999998 31.2934342,120.82719760000003 31.293533100000012,120.827079 31.293602400000005,120.82699909999998 31.293673299999988,120.82693860000003 31.293741599999997,120.8268889 31.293796499999992,120.82682550000003 31.29382109999999,120.82674999999999 31.2938301,120.82668329999997 31.293840100000004,120.82663739999997 31.293863200000004,120.82660180000005 31.293891400000007,120.82646129999999 31.294070599999994,120.8264184 31.29411219999999,120.82635520000002 31.2941442,120.82593279999999 31.2942683,120.82576710000005 31.2943349,120.82569779999999 31.294373700000005,120.82540460000003 31.294476000000003,120.82500189999998 31.294604999999997,120.8249512 31.294626799999993,120.82487139999998 31.2946764,120.82482469999997 31.294714999999993,120.82479579999998 31.29474760000001,120.82473270000001 31.2947182,120.8246881 31.29471059999999,120.82462229999999 31.294716499999993,120.82454769999997 31.294735699999993,120.82445790000004 31.294723299999998,120.8244089 31.2947271,120.82428079999998 31.294770199999995,120.8242381 31.29475480000001,120.82418940000001 31.29474619999999,120.82411150000003 31.294747199999993,120.82403479999999 31.294764300000008,120.82395870000003 31.294797,120.82386059999997 31.29477869999999,120.82378609999998 31.294779400000003,120.82372159999998 31.294792499999993,120.82364540000002 31.294831299999995,120.8235811 31.294824700000003,120.82351860000001 31.2948282,120.82343470000005 31.294859500000012,120.82329699999997 31.294942600000006,120.82221439999996 31.29520499999999,120.82191790000002 31.29519259999999,120.82101689999998 31.295054399999994,120.820474 31.2949584,120.82012440000001 31.29489819999999,120.81988870000002 31.29487629999999,120.8196742 31.294852699999993,120.81939499999997 31.294810900000005,120.81923349999998 31.2947732,120.8190717 31.294722899999993,120.81894060000003 31.294670499999995,120.8188194 31.294614099999997,120.81857700000002 31.294425000000004,120.8184266 31.294358099999997,120.81831769999997 31.2943278,120.81823060000002 31.294307299999996,120.8181317 31.2942985,120.81760570000002 31.294300299999993,120.81755650000004 31.294315099999988,120.81746220000001 31.294359399999994,120.81712319999998 31.2945187,120.8166571 31.294737699999995,120.8162145 31.295023299999997,120.81570040000003 31.295390600000008,120.81555199999998 31.2955247,120.81506059999997 31.296063199999995,120.8140889 31.296120599999995,120.81407519999999 31.295934500000005,120.81402639999997 31.295707300000004,120.8139328 31.295535500000007,120.81385240000003 31.2955163,120.81375819999998 31.29552,120.81345099999997 31.295560399999985,120.81321100000001 31.295654199999994,120.81298809999997 31.2958187,120.81280970000005 31.296035999999994,120.81266900000001 31.296395400000005,120.81164070000003 31.296658400000002,120.81109090000001 31.29690490000001,120.80960759999998 31.297121099999995,120.80858130000003 31.297360100000002,120.80798730000002 31.2974579,120.8066338 31.297523200000004,120.80606319999997 31.297604999999994,120.80579719999999 31.297674300000008,120.8053312 31.297867499999995,120.80532689999998 31.2979249,120.80523340000003 31.297918199999994,120.80517559999998 31.298259000000005,120.80463900000004 31.298186800000003,120.80465579999998 31.298100399999992,120.80442670000002 31.29814040000001,120.80417060000003 31.298169999999995,120.80362639999997 31.298185599999996,120.80313770000001 31.298173999999992,120.8018221 31.298031699999992,120.80169900000001 31.297886399999996)))
```

**Comment by ianturton** [comment]
OK, can you add that as a unit test and fix the other broken tests

**Comment by aaime** [comment]
So many github actions are red... test failures in the process-geometry module, likely due to this change. Either the test introduced a regression, or the test expectations need to be amended:

```
2024-11-25T11:01:23.9517412Z [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.811 s <<< FAILURE! - in org.geotools.process.geometry.CenterLineTest
2024-11-25T11:01:23.9519745Z [ERROR] testGetCentreLine(org.geotools.process.geometry.CenterLineTest)  Time elapsed: 0.549 s  <<< FAILURE!
2024-11-25T11:01:23.9521245Z java.lang.AssertionError: equalsNorm:2
2024-11-25T11:01:23.9522162Z 	at org.junit.Assert.fail(Assert.java:89)
2024-11-25T11:01:23.9522902Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2024-11-25T11:01:23.9524040Z 	at org.geotools.process.geometry.CenterLineTest.testGetCentreLine(CenterLineTest.java:69)
2024-11-25T11:01:23.9525493Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-25T11:01:23.9527361Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-11-25T11:01:23.9529172Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-25T11:01:23.9530569Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-11-25T11:01:23.9531749Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-11-25T11:01:23.9533170Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-11-25T11:01:23.9534608Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-11-25T11:01:23.9536030Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-11-25T11:01:23.9537421Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-11-25T11:01:23.9538626Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-11-25T11:01:23.9539832Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2024-11-25T11:01:23.9541069Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2024-11-25T11:01:23.9542275Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2024-11-25T11:01:23.9543737Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2024-11-25T11:01:23.9544918Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2024-11-25T11:01:23.9545914Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2024-11-25T11:01:23.9547010Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2024-11-25T11:01:23.9548082Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2024-11-25T11:01:23.9549116Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2024-11-25T11:01:23.9550156Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-11-25T11:01:23.9551165Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2024-11-25T11:01:23.9552510Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2024-11-25T11:01:23.9554006Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2024-11-25T11:01:23.9555571Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2024-11-25T11:01:23.9557010Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2024-11-25T11:01:23.9559232Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2024-11-25T11:01:23.9561027Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2024-11-25T11:01:23.9562458Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2024-11-25T11:01:23.9563731Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2024-11-25T11:01:23.9564479Z 
2024-11-25T11:01:23.9565201Z [ERROR] testGetSkeleton(org.geotools.process.geometry.CenterLineTest)  Time elapsed: 0.231 s  <<< FAILURE!
2024-11-25T11:01:23.9566749Z java.lang.AssertionError: expectedSkel:2
2024-11-25T11:01:23.9567395Z 	at org.junit.Assert.fail(Assert.java:89)
2024-11-25T11:01:23.9568055Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2024-11-25T11:01:23.9569153Z 	at org.geotools.process.geometry.CenterLineTest.testGetSkeleton(CenterLineTest.java:78)
2024-11-25T11:01:23.9570715Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-25T11:01:23.9572228Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-11-25T11:01:23.9573967Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-25T11:01:23.9575349Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-11-25T11:01:23.9576734Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-11-25T11:01:23.9578193Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-11-25T11:01:23.9579627Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-11-25T11:01:23.9581035Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-11-25T11:01:23.9582405Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-11-25T11:01:23.9583580Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-11-25T11:01:23.9584764Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2024-11-25T11:01:23.9585926Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2024-11-25T11:01:23.9587080Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2024-11-25T11:01:23.9588520Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2024-11-25T11:01:23.9590747Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2024-11-25T11:01:23.9591998Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2024-11-25T11:01:23.9593058Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2024-11-25T11:01:23.9594127Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2024-11-25T11:01:23.9595131Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2024-11-25T11:01:23.9596146Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2024-11-25T11:01:23.9597112Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2024-11-25T11:01:23.9598250Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2024-11-25T11:01:23.9599714Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2024-11-25T11:01:23.9601262Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2024-11-25T11:01:23.9602709Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2024-11-25T11:01:23.9604314Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2024-11-25T11:01:23.9606017Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2024-11-25T11:01:23.9607457Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2024-11-25T11:01:23.9608743Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by SuperChrisliu** [comment]
I have fixed the broken tests

**Review by ianturton — APPROVED** [review]

**Comment by ianturton** [comment]
Thanks for this

**Pull request merged**
