### PR TITLE
[GEOT-7268] GeoTools can create GML output that is not valid XML

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOT-7268](https://osgeo-org.atlassian.net/browse/GEOT-7268) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR updates the TransformerBase and Encoder APIs to validate all element and attribute names and throw an exception if they contain any illegal or invalid XML characters.  The validation also blocks using the XHTML namespace which could allow injecting script without using those characters.  Additional GML unit tests are in https://github.com/geoserver/geoserver/pull/6364.
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Humm... the downstream failures are strange (and repeatable it seems, restarted and got the same result):

```
2022-11-21T14:26:05.0469643Z [ERROR] Tests run: 14, Failures: 9, Errors: 3, Skipped: 0, Time elapsed: 0.662 s <<< FAILURE! - in org.geoserver.wfs.GetCapabilitiesTest
2022-11-21T14:26:05.0549490Z [ERROR] testOutputFormatAllowed(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.424 s  <<< ERROR!
2022-11-21T14:26:05.0550201Z java.lang.NullPointerException
2022-11-21T14:26:05.0551190Z 	at org.geoserver.wfs.GetCapabilitiesTest.testOutputFormatAllowed(GetCapabilitiesTest.java:154)
2022-11-21T14:26:05.0552704Z 
2022-11-21T14:26:05.0555472Z [ERROR] testGet(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.014 s  <<< FAILURE!
2022-11-21T14:26:05.0556123Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0556906Z 	at org.geoserver.wfs.GetCapabilitiesTest.testGet(GetCapabilitiesTest.java:59)
2022-11-21T14:26:05.0562181Z 
2022-11-21T14:26:05.0564897Z [ERROR] testLayerQualified(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.013 s  <<< FAILURE!
2022-11-21T14:26:05.0565608Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0568585Z 	at org.geoserver.wfs.GetCapabilitiesTest.testLayerQualified(GetCapabilitiesTest.java:288)
2022-11-21T14:26:05.0586658Z 
2022-11-21T14:26:05.0589274Z [ERROR] testPost(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.085 s  <<< FAILURE!
2022-11-21T14:26:05.0589942Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0590569Z 	at org.geoserver.wfs.GetCapabilitiesTest.testPost(GetCapabilitiesTest.java:122)
2022-11-21T14:26:05.0596732Z 
2022-11-21T14:26:05.0599402Z [ERROR] testOutputFormats(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.012 s  <<< ERROR!
2022-11-21T14:26:05.0600165Z java.lang.NullPointerException
2022-11-21T14:26:05.0600714Z 	at org.geoserver.wfs.GetCapabilitiesTest.testOutputFormats(GetCapabilitiesTest.java:130)
2022-11-21T14:26:05.0605919Z 
2022-11-21T14:26:05.0609429Z [ERROR] testWorkspaceQualified(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.009 s  <<< FAILURE!
2022-11-21T14:26:05.0610118Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0610745Z 	at org.geoserver.wfs.GetCapabilitiesTest.testWorkspaceQualified(GetCapabilitiesTest.java:256)
2022-11-21T14:26:05.0613910Z 
2022-11-21T14:26:05.0616618Z [ERROR] testSkipMisconfiguredLayers(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.014 s  <<< FAILURE!
2022-11-21T14:26:05.0617227Z junit.framework.ComparisonFailure: expected:<[16]> but was:<[0]>
2022-11-21T14:26:05.0617840Z 	at org.geoserver.wfs.GetCapabilitiesTest.testSkipMisconfiguredLayers(GetCapabilitiesTest.java:85)
2022-11-21T14:26:05.0621895Z 
2022-11-21T14:26:05.0624524Z [ERROR] testNonAdvertisedLayer(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.009 s  <<< FAILURE!
2022-11-21T14:26:05.0625441Z junit.framework.AssertionFailedError: Expecting to find matches for Xpath //wfs:FeatureType[wfs:Name='cgf:MLines']
2022-11-21T14:26:05.0626106Z 	at org.geoserver.wfs.GetCapabilitiesTest.testNonAdvertisedLayer(GetCapabilitiesTest.java:323)
2022-11-21T14:26:05.0629375Z 
2022-11-21T14:26:05.0631860Z [ERROR] testSupportedSpatialOperators(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.008 s  <<< ERROR!
2022-11-21T14:26:05.0632417Z java.lang.NullPointerException
2022-11-21T14:26:05.0632980Z 	at org.geoserver.wfs.GetCapabilitiesTest.testSupportedSpatialOperators(GetCapabilitiesTest.java:188)
2022-11-21T14:26:05.0636656Z 
2022-11-21T14:26:05.0642225Z [ERROR] testNamespaceFilter(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.008 s  <<< FAILURE!
2022-11-21T14:26:05.0642726Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0643265Z 	at org.geoserver.wfs.GetCapabilitiesTest.testNamespaceFilter(GetCapabilitiesTest.java:94)
2022-11-21T14:26:05.0645147Z 
2022-11-21T14:26:05.0650417Z [ERROR] testTypeNames(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.008 s  <<< FAILURE!
2022-11-21T14:26:05.0650949Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0651460Z 	at org.geoserver.wfs.GetCapabilitiesTest.testTypeNames(GetCapabilitiesTest.java:232)
2022-11-21T14:26:05.0654122Z 
2022-11-21T14:26:05.0658840Z [ERROR] testTypeNameCount(org.geoserver.wfs.GetCapabilitiesTest)  Time elapsed: 0.01 s  <<< FAILURE!
2022-11-21T14:26:05.0659447Z org.junit.ComparisonFailure: expected:<[WFS_Capabilities]> but was:<[ServiceExceptionReport]>
2022-11-21T14:26:05.0659971Z 	at org.geoserver.wfs.GetCapabilitiesTest.testTypeNameCount(GetCapabilitiesTest.java:206)
````

The changes in the corresponding GeoServer PR do not seem to touch those classes. I'm going to restart the tests a third time just to be sure.

**Comment by sikeoka** [comment]
I added a workaround for the GS WFS module unit tests.  The GS WCS 2.0 module will need a separate PR to fix insecure code there before the downstream build can continue (https://github.com/geoserver/geoserver/pull/6371).

**Comment by sikeoka** [comment]
@aaime Could you retry the downstream build now that the WCS fix is merged?

**Comment by aaime** [comment]
LOL I was about to press the "re-run" button when I saw a notification of your comment. It's running.

**Pull request merged**
