### PR TITLE
[GEOT-5526] App-Schema: Native Encoding of Nested Filters

### PR DESCRIPTION
**Pull request by ridethepenguin**
Straightforward backport of #1319 to Geotools 15.x.

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
Thanks @ridethepenguin.

**Comment by bencaradocdavies** [comment]
@NielsCharlier and @riniangreani, I decided this is a safe enough backport to stable and maintenance because it is a performance bug-fix and @ridethepenguin has provided a means to disable the new behaviour (property file) if it does not work for someone.

**Comment by riniangreani** [comment]
Sounds good and thanks @bencaradocdavies @ridethepenguin

**Comment by ridethepenguin** [comment]
Great! Many thanks @bencaradocdavies for all your work, and also thanks to @riniangreani and @NielsCharlier for reviewing.

**Pull request merged**
