### PR TITLE
[GEOT-7033] GML: Adding BigDecimal to Boolean conversion

### PR DESCRIPTION
**Pull request by lislei**
[GEOT-7033](https://osgeo-org.atlassian.net/browse/GEOT-7033) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Exending existing to boolean mapping for GML in order to handle BigDecimal.

I'm currently migrating a WFS service to Geoserver 2.20 (from 2.7) and ran into a mapping issue. The exception presented was "java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Boolean".

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by lislei** [comment]
I'm picking up on your offer @jodygarnett. Hope you can review this. 

As mentioned on the mailing list, the code could be more relaxed. 
Unit testing makes sure the returned values are of expected type. The runtime check (cast) does not add any more value to it, or am I missing something?

**Comment by lislei** [comment]
Created a ticket GEOT-7033 on this

**Comment by aaime** [comment]
QA build failing:

``
 Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-main: Found 2 non-complying files, failing build -> [Help 1]
``

Get into the main module, and run, from the command line:

``mvn clean install -nsu -Dqa``

It will fix the formatting issue (actually any maven build does) but will also run ErrorProne, PMD, Spotbugs and Checkstyle on the changes (they all have to pass in order for this PR to be merged).

**Comment by lislei** [comment]
Resolved the issue that was displayed to me.
I'm having some issues getting `mvn clean install -nsu -Dqa` so not sure what it could be. 

Now it thows me an unrelated error:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] C:\projects\dev\gt\geotools-lislei\modules\library\cql\target\generated-sources\jjtree-javacc\org\geotools\filter\text\generated\parsers\JavaCharStream.java:[447,9] error: [ChainingConstructorIgnoresParameter] The called constructor accepts a parameter with the same name and type as one of its caller's parameters, but its caller doesn't pass that parameter to it.  It's likely that it was intended to.
    (see https://errorprone.info/bugpattern/ChainingConstructorIgnoresParameter)
  Did you mean 'this(new java.io.InputStreamReader(dstream), startline, startcolumn, buffersize);'?
```

**Comment by aaime** [comment]
That's [errorprone](https://errorprone.info/bugpattern/ChainingConstructorIgnoresParameter), but it should not be running on generated sources. Weird?

In any case, I suggest you to run the QA build only in the module you've modified. Btw, looks like there is still a formatting issue:

```
Error:  Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-main: Found 1 non-complying files, failing build -> [Help 1]
```

Please do run maven on the command line before pushing the PR, it will reformat the code to match the Google Java Formatting convention automatically.

**Comment by lislei** [comment]
Thanks @aaime, I wasn't paying attention to the formatting changes. I had my IDE/IntelliJ hide it from me :)

**Review by jodygarnett — APPROVED** [review]

**Pull request merged**
