### PR TITLE
GEOT-5828 fix NPE when fine logging on

### PR DESCRIPTION
**Pull request by ianturton**
NetCDF tests fail with NPE if run with fine logging turned on. 

[GEOT-5828](https://osgeo-org.atlassian.net/browse/GEOT-5828)

### CODE REVIEW

**Comment by dromagnoli** [comment]
Hi @ianturton.
Not sure I have understood correctly. Are you unable to login on JIRA and create a ticket for that OR did you create it but you are unable to retrieve the number?

Please, let me know. 
I can create a JIRA for that and give you the reference if needed.

**Comment by ianturton** [comment]
I can't login to atlasian currently - please do create a ticket if you can

**Comment by dromagnoli** [comment]
Sure: GEOT-5828
https://osgeo-org.atlassian.net/browse/GEOT-5828

**Comment by dromagnoli** [comment]
Thanks for the fix.

**Pull request merged**
