### PR TITLE
[GEOT-6191] Converter factory for converting SQL Large Objects

### PR DESCRIPTION
**Pull request by stefanuhrig**
The factory provides conversions from java.sql.Blob to byte[] and from
java.sql.Clob to java.lang.String.

Existing generic SQL Large Object converter factories have been removed.

### CODE REVIEW

**Comment by stefanuhrig** [comment]
As discussed in https://github.com/geotools/geotools/pull/2055, I've created a generic SQL Large Object converter factory.

**Comment by aaime** [comment]
@stefanuhrig looks good to me, but there are conflicts (I suppose caused by the JDK11 compatibility work), would you have time to look into it?

**Comment by stefanuhrig** [comment]
@aaime I've resolved the conflicts and pushed the change again.

**Comment by tbarsballe** [comment]
This seems to be missing an associated [JIRA Issue](https://osgeo-org.atlassian.net/issues/) as per [CONTRIBUTING.md](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md), but otherwise looks ready to merge. If you could add a JIRA issue for this change that would be great.

**Comment by stefanuhrig** [comment]
@tbarsballe I've created JIRA issue [GEOT-6191](https://osgeo-org.atlassian.net/browse/GEOT-6191). I hope I did it right, it was the first JIRA issue I've opened for GeoTools.

**Comment by tbarsballe** [comment]
Perfect, thanks. Looks great (thanks for updating the commit message too)

**Pull request merged**
