### PR TITLE
Fix for ImageWorker

### PR DESCRIPTION
**Pull request by irisiflimsi**
A lot of my data is raster data with alpha-channel. About 2% fail when serving them through the tile server at some resolutions.  I can't produce a small, self-contained example, unfortunately. But I have tracked it down and it seems the alpha-channel is rendered separately from the rest of the image and is "allergic" to 0-size tile-width. This is the way I fixed it in 21.1 (verified in my environment). If necessary, I can give you the stack trace from the logs, the AWT class doesn't like 0.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

I wasn't able to create a Jira issue, because the Attlassian license limit was reached, or so it said. The issue was discussed on the mailing list a few weeks ago, Jody Garnett was involved. If you need a signed contribution agreement, I can forward that, but I consider the issue minor enough not to do so at this point in time.

### CODE REVIEW

**Review by dromagnoli — APPROVED** [review]
Looks good to me

**Comment by aaime** [comment]
We need the issue in JIra and the commit message referring to it, before merge. You can force-push to update the PR.

**Comment by irisiflimsi** [comment]
This mail wasn't addressed to me, but just to be clear: I can't do anything about it, I can't access your Jira.

Michael

**Comment by aaime** [comment]
Yes, all comments to a PR are delivered to the PR author, and other participants, by mail.

Anyone should be able to create a Jira ticket, it just requires an account (which can also be freely created).
Did you create the account and it still does not work? Or did you have difficulties creating an account on Jira?
See also: https://osgeo-org.atlassian.net/jira/dashboards/last-visited

**Comment by irisiflimsi** [comment]
See the mail for details. I have an account, which I can use to access atlassian "root", I can see anonymous information on your board but nothing reserved for authenticated members - or so it feels.

**Comment by aaime** [comment]
For this time only, I've created the ticket in Jira and fixed the commit message to follow, by using squash-merge.
Next time please try to create a separate account, OSGeo is a different organization than the Atlassian root, so it's the likely cause (I don't remember getting report of similar issues).

The commit has been merged on main, will be part of the release in March 2022. If you want it to show up earlier, you can create backport PRS to 26.x and 25.x. Please cherry-pick the commit as merged 6ccf156, as it has the right commit message, allowing to cross-reference the commit to Jira.

**Pull request merged**
