### PR TITLE
[GEOT-6975] Update dependencies of (unsupported) Elasticsearch plugin

### PR DESCRIPTION
**Pull request by mprins**
[GEOT-6975](https://osgeo-org.atlassian.net/browse/GEOT-6975) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Updates:

```
org.elasticsearch.client:elasticsearch-rest-client ... 7.10.2 -> 7.14.0
org.locationtech.spatial4j:spatial4j ....................... 0.6 -> 0.8
com.github.davidmoten:geo .............................. 0.7.4 -> 0.7.7
com.google.guava:guava ......................... 30.1-jre -> 30.1.1-jre
joda-time:joda-time ................................. 2.10.1 -> 2.10.10
org.testcontainers:elasticsearch ..................... 1.15.1 -> 1.16.0
```

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by mprins** [comment]
running into trouble with online tests, typical error message:
```
[ERROR] org.geotools.data.elasticsearch.ElasticTemporalFilterIT.testTEquals  Time elapsed: 0.187 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/joda/time/format/DateTimeParser
	at org.geotools.elasticsearch/org.geotools.data.elasticsearch.ElasticTemporalFilterIT.testTEquals(ElasticTemporalFilterIT.java:199)
Caused by: java.lang.ClassNotFoundException: org.joda.time.format.DateTimeParser
	at org.geotools.elasticsearch/org.geotools.data.elasticsearch.ElasticTemporalFilterIT.testTEquals(ElasticTemporalFilterIT.java:199)

```

however the Joda dependency is declared as a runtime dependency in the pom

perhaps @sjudeng can shed some light? 

BTW. I think this module breaks the "No split packages" rule as  it includes both `org.geotools.*.elastic search` as well as `org.joda.time.format` (which also exists in the Joda dependency) and may be the explanation of the problem.

**Comment by mprins** [comment]
FWIW running the online tests `mvn clean install -Dall -pl :gt-elasticsearch -Ponline` on our `main` branch I'm seeing the same failures.

**Comment by aaime** [comment]
Not having an online build (PR check) for it might have caused an unwanted regression? Or maybe it was already like that.
About the split package... maybe? Are you running Java 8 or Java 11 for the tests?

**Comment by mprins** [comment]
Running tests on Java 11

**Comment by mprins** [comment]
When running `mvn clean install -Dall -pl :gt-elasticsearch -Ponline` with Java 8 all tests pass on both the `main` branch as well as this PR's branch; so the above failure seems related to Java 11 and not these updates.

My quick conclusion is this module causes classloader issues on Java 11, but that is not what this PR is about, I've opened https://osgeo-org.atlassian.net/browse/GEOT-6977 for that.

**Pull request merged**
