### PR TITLE
[GEOT-7234] Implement #getOptimizedBounds(...) in SQLServerDialect

### PR DESCRIPTION
**Pull request by mprins**
[GEOT-7234](https://osgeo-org.atlassian.net/browse/GEOT-7234) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Query the (first) spatial index defined on a column to get the bounds, the option to use the fast-track is enabled using the `estimatedExtentsEnabled` feature flag.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by jodygarnett** [comment]
This is a draft from last year, and predates the API change. Is it something you wish to pursue?

**Comment by mprins** [comment]
@jodygarnett  I will, when I get the time, however looking into a different approach that avoids the possible table scan and queries the spatial index directly

**Comment by jodygarnett** [comment]
Wishing you well on this activity @mprins

**Comment by mprins** [comment]
@jodygarnett This is ready for review

**Comment by aaime** [comment]
Looks good to me!

**Pull request merged**
