### PR TITLE
Add AttributeDescriptor to descriptors list to fix filtering of geopackages

### PR DESCRIPTION
**Pull request by jericks**
Fix for https://osgeo-org.atlassian.net/browse/GEOT-6107

### CODE REVIEW

**Comment by aaime** [comment]
Looks ok but has a formatting error:

```
[ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-geopkg: Found 1 non-complying files, failing build -> [Help 1]
```

Fixing it is easy, just run the maven build in the GeoPackage build, the build will reformat according to rules.

**Comment by jericks** [comment]
Done!

**Comment by jericks** [comment]
Thanks Andrea!  Is it possible to backport this to the 20.x branch?  If so, should I create another PR against 20.x?

Cheers,
Jared

**Comment by aaime** [comment]
Hi Jared, yes, please make one, I'm overwhelmed with other stuff at the moment.

**Comment by jericks** [comment]
Done!

https://github.com/geotools/geotools/pull/2034

Thanks for guiding me through this!

Cheers,
Jared

**Comment by NielsCharlier** [comment]
See this now, thanks for the fix.

**Pull request merged**
