### PR TITLE
[GEOT-7555] Use dateFormatter of GeoJSONWriter instead of the default one

### PR DESCRIPTION
**Pull request by initialdmg**
[GEOT-7555](https://osgeo-org.atlassian.net/browse/GEOT-7555) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Module: `gt-geojson-core`.

[[GEOT-7555](https://osgeo-org.atlassian.net/browse/GEOT-7555)] This is a small fix to `GeoJSONWriter`, to format `Date` using private member variable date formatter.
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by Arjen10** [comment]
you may not have signed the [contribution license](https://docs.geotools.org/latest/developer/procedures/contribution_license.html), so GeoTools maintenance team may not merge this pr. even though this PR is valid...

**Comment by ianturton** [comment]
Or maybe there is no Jira issue listed. This probably doesn't need a cla.
As far as I could see on my phone there was no explanation for the change

**Comment by aaime** [comment]
It's also missing a test. 
Should be easy to write one, e.g., do something that would alter the date formatting, like setting a different date pattern, and ensure the encoding result matches is.

**Comment by initialdmg** [comment]
Test case in which date pattern is altered added.

According to [CONTRIBUTING.md](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md) , **trivial change** does not need to sign the Code Contribution License, so i ignored that in the checklist.

**Comment by aaime** [comment]
Better, now please make sure to have a Jira ticket and refer it from the commit message.

**Review by mprins — APPROVED** [review]

**Comment by mprins** [comment]
please run `mvn spotless:apply` before commit to fix formatting
```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.20.0:check (default) on project gt-geojson-core: The following files had format violations:
Error:      src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
Error:          @@ -35,7 +35,6 @@
Error:           import·java.util.Date;
Error:           import·java.util.List;
Error:           import·java.util.Locale;
Error:          -
Error:           import·org.apache.commons.lang3.time.DateFormatUtils;
Error:           import·org.geotools.TestData;
Error:           import·org.geotools.api.feature.simple.SimpleFeature;
Error:  Run 'mvn spotless:apply' to fix these violations.
```

**Comment by aaime** [comment]
Looks good, thanks! Merging and scheduling for backport.

**Pull request merged**
