### PR TITLE
Add mbstyle to 'all' profile

### PR DESCRIPTION
**Pull request by tbarsballe**
Required for https://github.com/geoserver/geoserver/pull/2492

### CODE REVIEW

**Comment by bradh** [comment]
The failure:
```
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.381 sec <<< FAILURE! - in org.geotools.mbstyle.SymbolMBLayerTest
testIconPadding(org.geotools.mbstyle.SymbolMBLayerTest)  Time elapsed: 0.212 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[30].0> but was:<[15].0>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.geotools.mbstyle.SymbolMBLayerTest.testIconPadding(SymbolMBLayerTest.java:158)
```

**Comment by bradh** [comment]
The failure:
```
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.381 sec <<< FAILURE! - in org.geotools.mbstyle.SymbolMBLayerTest
testIconPadding(org.geotools.mbstyle.SymbolMBLayerTest)  Time elapsed: 0.212 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[30].0> but was:<[15].0>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.geotools.mbstyle.SymbolMBLayerTest.testIconPadding(SymbolMBLayerTest.java:158)
```

**Comment by tbarsballe** [comment]
Should be fixed now, see https://github.com/geotools/geotools/pull/1687

I've restarted the CI build.

**Comment by tbarsballe** [comment]
Now seeing a bunch of test failures along the lines of `Images are visibly different, found 2486 different pixels, against a threshold of 50`.

However, all the tests run fine locally for me, so I think this is OS-specific (or maybe jdk-specific).

Investigating...

**Comment by tbarsballe** [comment]
Update: Looks like MBStyle has some visualization tests that are OS-dependant.
Initially seemed to just be a font issue, but now seems more complicated than that.

May have to revisit this layer.

**Comment by tbarsballe** [comment]
After the latest MBStyle changes, this _finally_ passes CI.

**Comment by bencaradocdavies** [comment]
I am seeing five gt-mbstyle test failures with OpenJDK 1.8.0_144 that are I think caused by this change:
```
Failed tests: 
  VisualTransformerTest.mbSymbolLayerIconAndTextLinePlacementVisualTest:435->testVisualizeStyleWithLineFeatures:713 Images are visibly different, found 63 different pixels, against a threshold of 50
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
  VisualTransformerTest.mbSymbolLayerTextVisualTest:375->testVisualizeStyleWithPointFeatures:687 Images are visibly different, found 318 different pixels, against a threshold of 50
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
  VisualTransformerTest.mbSymbolLayerTextTransformVisualTest:414->testVisualizeStyleWithLineFeatures:713 Images are visibly different, found 93 different pixels, against a threshold of 50
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
  VisualTransformerTest.mbSymbolLayerTextLinePlacementVisualTest:404->testVisualizeStyleWithLineFeatures:713 Images are visibly different, found 370 different pixels, against a threshold of 50
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
  VisualTransformerTest.mbSymbolLayerIconAndTextPointPlacementVisualTest:445->testVisualizeStyleWithPointFeatures:687 Images are visibly different, found 228 different pixels, against a threshold of 50
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
```

**Comment by bencaradocdavies** [comment]
The `VisualTransformerTest` failures are not seen with Oracle JDK.

**Comment by bencaradocdavies** [comment]
The fonts are clearly different. I do not think this is the goldfish problem mentioned in https://github.com/geotools/geotools/pull/1699 . I also see mention of non-Vera fonts in font loading failures:
```
Sep 20, 2017 5:49:16 PM org.geotools.image.ImageWorker <clinit>
INFO: Warp/affine reduction enabled: true
Sep 20, 2017 5:49:17 PM org.geotools.renderer.style.FontCache loadFromUrl
INFO: Bad file name in SLDStyleFactoryOpen Sans Regular
java.io.FileNotFoundException: Open Sans Regular (No such file or directory)
Sep 20, 2017 5:49:17 PM org.geotools.renderer.style.FontCache loadFromUrl
INFO: null input stream, could not load the font
Sep 20, 2017 5:49:17 PM org.geotools.renderer.style.FontCache loadFromUrl
INFO: Bad file name in SLDStyleFactoryArial Unicode MS Regular
java.io.FileNotFoundException: Arial Unicode MS Regular (No such file or directory)
Sep 20, 2017 5:49:17 PM org.geotools.renderer.style.FontCache loadFromUrl
INFO: null input stream, could not load the font
Sep 20, 2017 5:49:17 PM org.geotools.renderer.style.FontCache loadFromUrl
INFO: Bad file name in SLDStyleFactoryOther Test Font
java.io.FileNotFoundException: Other Test Font (No such file or directory)
```

**Comment by bencaradocdavies** [comment]
I think the non-Vera font mentions are not important. Vera seems to be loaded but not used for some reason.

**Comment by tbarsballe** [comment]
Huh, I thought that had finally been fixed; looks like there is still one more complication.
@johngschulz and @jodygarnett - You ended up solving this for Oracle JDK, any idea why it would fail on OpenJDK?

**Comment by bencaradocdavies** [comment]
@tbarsballe @johngschulz @jodygarnett closer inspection shows the letter forms are in fact the same so Vera is being used as intended. The difference appears to be in the antialiasing.

**Comment by bencaradocdavies** [comment]
@tbarsballe @johngschulz @jodygarnett gt-render tests address font antialiasing differences by using a tolerance of about 1200 pixels when testing rendering of text on 300x300 images. I think the workaround here should be to increase the tolerance so that the tests pass on both Oracle JDK and OpenJDK. I will make a PR.

**Comment by johngschulz** [comment]
Ah, I had Oracle JDK on Mac OS and Ubuntu to test across platforms, the issue we found was the need for the font to be registered for the unit-tests.  I didn't take the opportunity to test Open JDK tolerances - I can test with Open JDK and see what happens.

**Comment by bencaradocdavies** [comment]
Thanks @johngschulz it would be good to have confirmation. There are also other possible platform causes such as freetype version that can break text-based rending tests. I have created [a Jira issue](https://osgeo-org.atlassian.net/browse/GEOT-5829) and will submit a pull request.

**Comment by bencaradocdavies** [comment]
I have submitted [a pull request](https://github.com/geotools/geotools/pull/1707) that increases the tolerance for these tests from 50 to 900 (1% of pixels).

**Pull request merged**
