### PR TITLE
[GEOT-7266] WMTSCapabilities throws NPE for missing title

### PR DESCRIPTION
**Pull request by InteractiveScape**
[GEOT-7266](https://osgeo-org.atlassian.net/browse/GEOT-7266) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
A test is required to consider the PR for merge (the change itself seems ok, @roarbra what do you think?)

**Comment by roarbra** [comment]
The specification states that a title is mandatory, and that in absence the client can choose to use the identifier. So this solution seems good.

I also would say that there should be a test.

**Comment by roarbra** [comment]
I created an [issue](https://osgeo-org.atlassian.net/browse/GEOT-7266) for this PR.

**Comment by roarbra** [comment]
@InteractiveScape I've fixed a test for this PR, but I would need write-access to your repository.

**Comment by jodygarnett** [comment]
> @InteractiveScape I've fixed a test for this PR, but I would need write-access to your repository.

@roarbra you may be able to issue a PR against their repository. If you wish to make a new PR with the test case we can close this one as incomplete.

**Comment by dnavre** [comment]
Please merge this, this produces the following exception when working with Geoserver.
```
Caused by: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.geotools.ows.wmts.model.WMTSCapabilities.parseLayer(WMTSCapabilities.java:333)
	at org.geotools.ows.wmts.model.WMTSCapabilities.<init>(WMTSCapabilities.java:106)
	at org.geotools.ows.wmts.response.WMTSGetCapabilitiesResponse.<init>(WMTSGetCapabilitiesResponse.java:95)
	at org.geotools.ows.wmts.WMTSSpecification$GetCapsRequest.createResponse(WMTSSpecification.java:415)
	at org.geotools.ows.wmts.WMTSSpecification$GetCapsRequest.createResponse(WMTSSpecification.java:387)
	at org.geotools.data.ows.AbstractOpenWebService.internalIssueRequest(AbstractOpenWebService.java:461)
	at org.geotools.data.ows.AbstractOpenWebService.issueRequest(AbstractOpenWebService.java:489)
	at org.geotools.data.ows.AbstractOpenWebService.negotiateVersion(AbstractOpenWebService.java:287)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:124)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:97)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:88)
	at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:77)
	at org.geotools.ows.wmts.WebMapTileServer.<init>(WebMapTileServer.java:151)
```

**Comment by aaime** [comment]
The PR does not satisfy the minimum requirements reported in the checklist above. If you are interested in getting the code change merged, please work on adding a unit/integration test for it.

**Comment by roarbra** [comment]
@aaime I've made a new PR with unit test.

**Pull request closed without merging**
