### PR TITLE
[GEOT-5441] Nested rings in curves don't parse correctly in GML3

### PR DESCRIPTION
**Pull request by mtoonen**
Somehow github didn't detect the changes I made in the old PR (https://github.com/geotools/geotools/pull/1216), so here is a new PR.

The ticket: https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5441?filter=allopenissues

In RingTypeBinding there was a LineString being returned. My reasoning was that, since it is a ring, it should return a (Linear)Ring. So, when the only member is a LineString, create a LinearRing of it's coordinates, and return that. After that, the tests pass.

### CODE REVIEW

**Comment by jodygarnett** [comment]
This looks okay, has test cases, no headers but we relaxed that requirement.

The previous one got held up on whitespace changes so I will be careful and merge locally.

**Comment by mtoonen** [comment]
Thanks!
The corporation for which I work (B3Partners B.V.) have signed a Copyright Assignment Agreement in june 2012. It's different from the one in  CONTRIBUTING.md, so I will sent a new one.

**Comment by jodygarnett** [comment]
Thanks you for being so professional @mtoonen - let us know when something is sent in!

**Comment by mtoonen** [comment]
Last week I received a confirmation that my agreement was received.

**Comment by aaime** [comment]
Manually merged to fix formatting issues, squash commits, and make the commit message refer to the ticket.

**Comment by aaime** [comment]
Backported to 15.x as well

**Comment by mtoonen** [comment]
Thanks for this!

**Pull request closed without merging**
