### PR TITLE
[GEOT-7051] ContourProcess doesn't extract GridCoverage2D NoData properties

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOT-7051](https://osgeo-org.atlassian.net/browse/GEOT-7051) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR updates ContourProcess to extract the NoData property from the input GridCoverage2D.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
The downstreams build failure that was there is the one that's caused by your other NetCDF change, see the revert PRs for discussion.

**Comment by aaime** [comment]
Hum, the build failures are in the docs, something we have seen in GeoServer recently, a bit in Sphinx became more strict (some might say more helpful) and started returning warnings, which the builds treats as failures:

```
2022-01-18T15:44:09.5081174Z      [exec] /home/runner/work/geotools/geotools/docs/user/library/coverage/netCDF.rst:12:hardcoded link 'https://docs.geoserver.org/latest/en/user/extensions/netcdf/netcdf.html#notes-on-supported-netcdfs' could be replaced by an extlink (try using ':geoserver:`extensions/netcdf/netcdf.html#notes-on-supported-netcdfs`' instead)
```

See also: https://github.com/geoserver/geoserver/pull/5593

**Comment by sikeoka** [comment]
The build finally passed.

**Comment by aaime** [comment]
Nice. Squash-merged on main.

**Pull request merged**
