### PR TITLE
GEOT-6371 gt-complex: app-schema and CSW not compatible

### PR DESCRIPTION
**Pull request by NielsCharlier**

### CODE REVIEW

**Comment by aaime** [comment]
Lacks a test.

**Comment by NielsCharlier** [comment]
not sure how to test it? problem only occurs when you run geoserver with both gs-csw (geoserver extension) and gt-app-schema (geotools extension). the fix is in geotools

**Comment by aaime** [comment]
The change seems to fix a data sharing issue, two subsequent instantiation of the FeatureTypeRegistry should not step on each other toes, and add/replace types that were added by the other one, or not? If so, that's what the bug is about in GeoTools, and also what should be tested.

**Comment by NielsCharlier** [comment]
@aaime sorry for the late response. a unit test has been added

thanks for reviewing

**Comment by aaime** [comment]
Looks ok to me, merging.

**Comment by aaime** [comment]
Squash-merged, if you need to backport you can cherry-pick a single commit.

**Pull request merged**
