### PR TITLE
[GEOT-6101] Upgrade SOLR to 7.4.0

### PR DESCRIPTION
**Pull request by bradh**
Adds suppression for zookeeper dep, and also for an arcsde dep that is clearly bogus.

### CODE REVIEW

**Comment by nmco** [comment]
Ah! I will try to run the test today, I have assigned the review to me.

**Comment by bradh** [comment]
@nmco Thanks Nuno. I had missed that there were merge conflicts (because of the pgsql dep upgrade), should now be resolved.

**Comment by tbarsballe** [comment]
@nmco - Did you ever get a change to run the online tests?

**Comment by nmco** [comment]
Doing it.

**Comment by nmco** [comment]
Online tests with Apache Solr 6.6.1 are successful, i.e. we have backward compatibility. Running the online tests with Apache Solr 7.4.0 make them failing. I added a commit to this PR fixing the online tests _plumbing_ for Apache Solr 7.4.0:

* be aware that JTS ``jts-core-1.15.0.jar`` needs to be added to Solr installation
* some default types like double, tlongs, tdates, etc ... where removed

After my _plumbing_ fixing some tests are still failing, looks like they are related with the way we are extracting the properties from the schema description we get from Solr. @bradh can you have a look at this ?

Instructions in how to run the online tests are available here:
https://github.com/geotools/geotools/blob/master/modules/unsupported/solr/README.rst

**Comment by bradh** [comment]
Will park this for now.

**Pull request closed without merging**
