### PR TITLE
Geopackage spatial index support

### PR DESCRIPTION
**Pull request by aaime**

### CODE REVIEW

**Comment by aaime** [comment]
Btw, I've tried to code this one with IntelliJ and noticed it's doing whitespace changes without me asking for them... how do I stop the sucker from doing so? ;-)

**Comment by jratike80** [comment]
What I understand looks good. There is some evedence that using JOIN in the SQL could be faster than sub-query but I have not verified that.

I would add to this comment that current GeoPackage standard allows only one geometry field in a table or view.
    // This implementation only supports figuring a bbox in case there is a single
    // indexed spatial attribute (could be extended to use multiple spatial attributes if need be)

Reference: standard version 1.2
Requirement 30
A feature table SHALL have only one geometry column.

**Comment by aaime** [comment]
Hi @jratike80 thanks for the feedback. Adding the spatial filter as a join is hard, we'd have to redesign filter encoding, currently it works under the assumption that it can be fully encoded inside the WHERE clause.

**Comment by aaime** [comment]
Wondering if @ianturton has a minute to look at this pull request? :-)

**Comment by aaime** [comment]
I'm merging this one so that it gets in the RC, not having a spatial index at all is problematic...

**Pull request merged**
