### PR TITLE
[GEOT-5527] PostgreSQL 9.6 breaks ASC_OR_DESC for index

### PR DESCRIPTION
**Pull request by bencaradocdavies**
https://osgeo-org.atlassian.net/browse/GEOT-5527

This pull request targets 15.x.

### CODE REVIEW

**Comment by aaime** [comment]
Unsure about this one, it's just a bugfix release, but out of our control... is there a risk to catch regressions in the driver with a last minute change?

**Comment by mprins** [comment]
Considering that PostgreSQL 9.6 is to be released yet and early adopters can just upgrade the driver themselves I'd go for 15.3 (even though downgrading the driver in case of a regression is just as easy)

**Comment by bencaradocdavies** [comment]
I am comfortable waiting for 15.3. It is prudent to do so as 15.x will soon be the maintenance branch and the manual workaround is easy. I have merged https://github.com/geotools/geotools/pull/1324 for master which lets development integration testing continue even on very up-to-date platforms. This PR can wait until after 15.2 is released

**Comment by jodygarnett** [comment]
This is held up on the code freeze

**Pull request merged**
