### PR TITLE
[GEOT-7665] PointStacker envBBOX has wrong value

### PR DESCRIPTION
**Pull request by NicoGuilhem**
[GEOT-7665](https://osgeo-org.atlassian.net/browse/GEOT-7665) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by NicoGuilhem** [comment]
tested with geoserver by overriding geotools "gt-process-feature.jar" in WEB-INF/lib, my use case is fixed.

**Review by aaime — CHANGES_REQUESTED** [review]
Looks good, two minor issues reported below

**Comment by NicoGuilhem** [comment]
@aaime , thanks for your review, i pushed new version with the changes you suggested.

**Comment by aaime** [comment]
The two failures are unrelated, code not affected by these changes and due to docker daemon limit (this is new btw, haven't seen it before):

```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Pull request merged**
