### PR TITLE
Fixed Jira issue GEOT-5687 - GeoJSON/GeometryCollection parsing issue

### PR DESCRIPTION
**Pull request by gsrhodes**
Fixed GeoJSON parsing problem for a GeometryCollection when a geometry in "geometries" has it's "type" value listed after "coordinates". See https://osgeo-org.atlassian.net/browse/GEOT-5687

### CODE REVIEW

**Comment by aaime** [comment]
This parsing is getting convoluted... @jdeolive any chance you could have a look at this one?

**Comment by jdeolive** [comment]
I agree, the way I originally designed this parser has a huge flaw in that parsing is order dependant. It means having to maintain a mess of state trying to manage things out of order. I would love to get a change to rewrite so that it doesn't have to do this but can still stream, but another conversation.

That said I looked over the patch and it looks ok to me.

**Comment by josepena0409** [comment]
I believe this will benefit a project I'm working on, could this be pulled into master please.

**Comment by gsrhodes** [comment]
What is the next step to get this merged? I created the pull request, but I am not a committer.

**Comment by jdeolive** [comment]
I'll go ahead and merge.

**Comment by gsrhodes** [comment]
Thank you! I appreciate that.

**Comment by jdeolive** [comment]
No worries! Thanks for the contribution!

**Comment by josepena0409** [comment]
Thank you all.

**Pull request merged**
