### PR TITLE
What can we do about situations like this?

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by jnh5y** [comment]
@aaime thoughts about what to do on the unchecked branch for situations like this where a type has been commented out? 

In the case of the protected method, it seems fairly ok-ish to go ahead with the change.  I'm wondering if we'll break other projects in the other case.

**Comment by aaime** [comment]
Often the case is the opposite: the code is old enough that the dev wanted to use generics, but we were still using a version of Java that did not support them, so they did add them as comments. I would uncomment them, and if it's publicly visible, add a note in the migration guide.

**Comment by jnh5y** [comment]
@aaime awesome.  If the pattern of removing comments like that is one that is worth following, I may just roll through the warnings looking for those.  (I'm thinking of doing that since I'd have some confidence of being able to make the change and know that it is ok, etc.)

Separately, with that kind of thing in mind, I wonder if it'd be worth implementing a JAI wrapper so that the Suppressions for JAI would be located in one place?  (Also, if the RPE/JAI replacement ever gets sorted, one would just replace/update that little bit of wrapping code?)

**Comment by aaime** [comment]
I'm pretty skeptical about wrapping JAI, but maybe do an example that shows better what you'd do?

**Comment by jnh5y** [comment]
Sounds good.  I'll save that idea for later, and if I can get to it, I'll produce an example.  Seems like knocking out the commented types is an easier and profitable change.

**Comment by aaime** [comment]
Closing, this one seemed mostly like a conversation, rather than something actually meant to be merged.

**Pull request closed without merging**
