### PR TITLE
[GEOT-5230] Update GeoPackage gpkg_contents DDL to match (revised) standard

### PR DESCRIPTION
**Pull request by bradh**
https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5230

### CODE REVIEW

**Comment by aaime** [comment]
Hum, not sure if anyone is looking after the geopackage module these days? If no one speaks up I'll merge this pull request (simply trusting Brad's changes, I won't check them against the spec).

**Comment by jodygarnett** [comment]
This is a tricky update as I am not quite sure what to make of it, I am used to a test case (I suppose to verify the correct table structure is created?)

Should there by any upgrade option, to migrate projects from old to new structure?

**Comment by bradh** [comment]
There are no existing tests for the rest of the database structure, so I didn't see the need to add any.

The OGC committee appears to have just made this as a "correction" (Corrigendum, not version upgrade) to the spec.

**Comment by jodygarnett** [comment]
Thanks for the clarification, merging.

**Comment by tbarsballe** [comment]
Backported to 14.x

**Pull request merged**
