### PR TITLE
[GEOT-5378] (14.x) Add check for functions deprecated in PostGIS 2.1.0

### PR DESCRIPTION
**Pull request by srstclair**
14.x backport for https://github.com/geotools/geotools/pull/1133

### CODE REVIEW

**Comment by aaime** [comment]
@srstclair and @bencaradocdavies  I saw quite a bit of back and forth about build failures on the pull request made on master, is this one up to date and ready to be merged? Or is this one not related at all?

**Comment by bencaradocdavies** [comment]
@aaime this change revealed a defect in the GeoServer app-schema online tests (reference data set postgis setup SQL leaked search_path settings); I fixed this in GeoServer. I have no objection to this GeoTools change. I do not intend to backport the GeoServer app-schema online test fix as we only run them on master. I think this fix is good to merge.

**Comment by bencaradocdavies** [comment]
Should the copyright headers be updated?

**Comment by srstclair** [comment]
Thanks @bencaradocdavies. I should have updated the PostGISDialect copyright header here, but it has been recently updated to 2016 in other PRs so should be good.

**Comment by bencaradocdavies** [comment]
@srstclair yes, @aaime would not have merged your PR on master without the correct header.

**Comment by tbarsballe** [comment]
@bencaradocdavies - are we fine to merge this? Seems the copyright header is up to date, everything else seems in order.

**Pull request merged**
