### PR TITLE
[GEOT-6540] Upgrade to latest jgridshift, avoid JCA dependencies

### PR DESCRIPTION
**Pull request by aaime**
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by aaime** [comment]
Valid compile failure downstream in GeoServer:

```
2020-03-29T08:21:10.9211830Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project gs-main: Compilation failure: Compilation failure: 
2020-03-29T08:21:10.9218331Z [ERROR] /home/runner/geoserver/src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java:[17,25] package javax.persistence does not exist
2020-03-29T08:21:10.9221610Z [ERROR] /home/runner/geoserver/src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java:[36,6] cannot find symbol
2020-03-29T08:21:10.9223132Z [ERROR]   symbol:   class Transient
2020-03-29T08:21:10.9225260Z [ERROR]   location: class org.geoserver.catalog.impl.WMSLayerInfoImpl
2020-03-29T08:21:10.9228342Z [ERROR] /home/runner/geoserver/src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java:[44,6] cannot find symbol
2020-03-29T08:21:10.9230011Z [ERROR]   symbol:   class Transient
2020-03-29T08:21:10.9232011Z [ERROR]   location: class org.geoserver.catalog.impl.WMSLayerInfoImpl
```

@imranrajjad why is this class using javax.persistence annotations, when GeoServer (I believe) has no use of it? Seems like they were added by mistake, maybe confused for something else? Want to know the rationale of it.

https://github.com/geoserver/geoserver/blob/master/src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java#L36

**Comment by soc** [comment]
Perhaps they meant the keyword `transient` instead of the annotation `@Transient`?

**Comment by aaime** [comment]
The annotations seemed un-necessary, removed. https://github.com/geoserver/geoserver/pull/4161

**Comment by aaime** [comment]
Merged. I don't have plans to backport this change, no personal need for it, but if anyone else is interested, you're welcomed to create the backport PRs.

**Pull request merged**
