### PR TITLE
[GEOT-5555] Coding style fixed

### PR DESCRIPTION
**Pull request by CozC**
The last pull request was not complying with GeoTools coding style.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Thanks; due to the amount of time that has passed since this pull request was created there are now conflicts that need to be resolved as outlined above.

Checking the bug link - GEOT-5555 PointStacker needs to have an option to compute cluster position based on the position of clustered points

I feel like something strange has happened to this pull request, it now contains 60 commits.

Options:
- Can you rebase against master? This will prompt you to resolve conflicts as part of the rebase process.
- Can you make a new branch from master, and then cherry pick just your commits across? This will ask you to resolve conflicts; but may be two awkward given the amount of time that has passed
- Finally you can copy the affected PointStacker classes, make a new branch from master, and then compare what we have now to your fix applying any changes necessary. You will lose commit history but it may be faster than the above.

**Comment by jodygarnett** [comment]
Please note as per our CONTIRBUTING.md instructions all fixes/improvements must be supplied against master (and then backported).

**Comment by jodygarnett** [comment]
Can I assume this is a continuation of https://github.com/geotools/geotools/pull/1384 ?

**Comment by CozC** [comment]
Yes it is the same as 1384.

Initially I sent it to the master, and then sent it to 16.x.

So the story is,

I did a mistake by sending it to 16.x, I did not read carefully the  
contributing note (at that time).
The PR on master, at that time (#1372), failed on travis (no error was  
sent, at least not obvious one) so I decided to sent it to 16.x(I was  
doing anyway work only on 16.x version so It seemed logical)

The conclusion
I will take into consideration all you options and then send it again.

Thank you.

On Thu, 09 Feb 2017 01:16:53 +0200, Jody Garnett  
<notifications@github.com> wrote:

>
> Can I assume this is a continuation of #1384 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Cosmin Cioranu

**Comment by aaime** [comment]
Closing this one, waiting for a new, clean pull request from you. However, mind, the contribution guide states to avoid reformats (because they make searching history much harder), if all you did is going into that direction, the pull request might be rejected anyways. At some point we should probably have a discussion about reformatting everything in a single shot and then adding a build check against mis-formatted code...

**Pull request closed without merging**
