### PR TITLE
[GEOT-6266] Generating GeoPackage fails when layer name has spaces or dashes

### PR DESCRIPTION
**Pull request by mikesname**
[GEOT-6266](https://osgeo-org.atlassian.net/browse/GEOT-6266) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This resolves an issue where entry names containing characters like hyphens and spaces (carried over from GeoServer layer names) caused a crash when exporting a GeoPackage.

In making these changes I noticed a small issue with `getTileBound`, which is that it returns 0 even if the requested zoom level does not exist (as opposed to, say, -1). I haven't changed anything behaviour-wise but just added a couple of assertions to test the code path and make the expected result clearer.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Review by ianturton — APPROVED** [review]
LGTM - @aaime do we need a contributor agreement for this?

**Comment by aaime** [comment]
@ianturton it's a judgment call... definitely not a typo fix or a one-liner, but still confined in a single file. Is that small enough to waive the CLA? Maybe. Possibly. :laughing:

**Comment by mikesname** [comment]
@ianturton @aaime I'll send one shortly, it's no problem

**Comment by mikesname** [comment]
Okay, I've sent the contributor agreement.

Also, is it okay to force push a change to the commit message because I've noticed it doesn't actually match the JIRA title?

**Comment by aaime** [comment]
Yes sir, use of force authorized.

**Pull request merged**
