### PR TITLE
spelling: availaible -> available

### PR DESCRIPTION
**Pull request by schwehr**

### CODE REVIEW

**Comment by schwehr** [comment]
Thanks!  I tried to start with something simple

**Comment by bencaradocdavies** [comment]
@schwehr this PR introduces a new build failure in gt-imageio-ext-gdal because it does not conform to the Google AOSP style:
https://api.travis-ci.org/v3/job/383453188/log.txt
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-plugin:1.9.5:check-local-modification (exec1) on project gt-imageio-ext-gdal: The build will stop as there is local modifications -> [Help 1]
```
The easiest way to fix this is to trigger an automatic reformat by building GeoTools:
```
mvn -o -T1C -Dall -PskipTests clean install
```
You can ignore the Travis CI gt-render failure as it was pre-existing.

**Comment by schwehr** [comment]
I failed to get `mvn -o -T1C -Dall -PskipTests clean install` to work.  I will keep trying when I get some more time.  I'm essentially new to the world of java outside of `bazel`.

**Comment by bencaradocdavies** [comment]
@schwehr sorry, my mistake, that should be:
```
mvn -T1C -Dall -DskipTests clean install
```
Note `-D` not `-P` for skipTests (it is a property not a profile). But if you have not got Maven to run, I can run it locally to reformat it for you.

**Comment by bencaradocdavies** [comment]
Manually merged on master preserving authorship and date as: https://github.com/geotools/geotools/commit/eb2ca81be108c62cfd617d0a8afa3c6b89ef91a1

The formatter removed the break at the end of this line. @schwehr this was the only thing wrong with your PR:
https://github.com/geotools/geotools/pull/1904/files#diff-42c8cc0eafe98584db80f5526a226069R63

**Comment by schwehr** [comment]
Thanks!  I've got a newborn, so my time is pretty chopped up.

**Comment by bencaradocdavies** [comment]
Congratulations @schwehr! Thanks again for the fix.

**Pull request closed without merging**
