### PR TITLE
[GEOT-5666] Avoid parsing the LookAt as the placemark geometry.

### PR DESCRIPTION
**Pull request by bradh**
From https://osgeo-org.atlassian.net/browse/GEOT-5666  - fix LookAt coordinate order and avoid parsing LookAt as the placemark geometry.

### CODE REVIEW

**Comment by bradh** [comment]
From https://osgeo-org.atlassian.net/browse/GEOT-5666

**Comment by aaime** [comment]
Hi Brad, I think it looks good, I just have a doubt about coordinate order (I wasn't the original author of this module).

What CRS is attached to the geometry definitions? Is it ``DefaultGeographicCRS.WGS84`` or ``CRS.decode("EPSG:4326", true)`` then it's good to force ordinates in eart/north order.
If instead it's CRS.decode("EPSG:4326") then it depends on how GeoTools is configured.
Long story short, some check to get a match between the returned geometry CRS order and the ordinates order should be made.

Looking around it seems the CRS is simply not defined in FeatureTypes, if that's indeed the case I'd be inclined to move forward as you did, with no reference in memory probably one should follow the native order of the format.

Wondering if @jdeolive has any hint/info to share? :-)

**Comment by bradh** [comment]
For the coordinate order, I don't see a specified CRS. I decided to go with consistency with the coordinate order we use for the placemark geometry (e.g. https://github.com/geotools/geotools/blob/master/modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/v22/KMLParsingTest.java#L44).

Would you like to see a Jira ticket / follow-up PR to be explicit about the CRS?

**Comment by aaime** [comment]
@bradh the follow up ticket might be a good idea

**Comment by bradh** [comment]
Added ticket as https://osgeo-org.atlassian.net/browse/GEOT-5922

**Pull request merged**
