### PR TITLE
GEOT-4984 add INSTANCE parameter and GEOT-4476 allow use of JTDS driver

### PR DESCRIPTION
**Pull request by ianturton**
Allows users with more than one DB on their machine to use the instance parameter to pick the right one.

With dbtype parameter jtds-sqlserver selects the JTDS driver which we can distribute.

### CODE REVIEW

**Comment by aaime** [comment]
We were talking about this one during the meeting, and since there has been no movement, we were considering merging it on master after the freeze ends?

**Comment by ianturton** [comment]
Hopefully I'll get a chance to add some docs by then, client is out of money so this back to my spare time

**Comment by aaime** [comment]
Freeze is over, I guess it's safe to merge, but right now it conflicts with all the test class name changes...

**Comment by ianturton** [comment]
I'll try to bring it up to date with those changes (I was afraid that would break),

**Pull request merged**
