### PR TITLE
Mimic default ImagingListenerImpl behavior to rethrow RuntimeExceptions

### PR DESCRIPTION
**Pull request by jodygarnett**
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>

### CODE REVIEW

**Comment by aaime** [comment]
So the original JAI logic was, at the beginning of the ``errorOccurred`` method:

```
        // Silent the RuntimeException occuring in any OperationRegistry
        // and rethrown all the other RuntimeExceptions.
        if (thrown instanceof RuntimeException &&
            !(where instanceof OperationRegistry))
            throw (RuntimeException)thrown;
```

Hum... yep, the updated implementation seems to be a match. +1

**Comment by aaime** [comment]
@jodygarnett given the other PR on the same topic that got merged already, what will you do with this one?

**Comment by jodygarnett** [comment]
Trying to find the other PR

**Comment by jodygarnett** [comment]
Checking against [LoggingImagingListener.java] their is slight improved functionality in this PR, should rebase this PR.

**Comment by aaime** [comment]
And... will it get done, or best to close this PR? :-D

**Comment by jodygarnett** [comment]
I will try and fix this then

**Comment by aaime** [comment]
@jodygarnett it's been more than a month since your last message, the PR accumulated a conflict in the meantime. If there is no short term interest in getting it merged, can we close it, it's alway possible to reopen later when you get time, no issue.

**Comment by aaime** [comment]
No further feedback in the last month, closing. Not a judgment on the PR, just noticing it's not going anywhere, please reopen with a non conflicting version later?

**Pull request closed without merging**
