### PR TITLE
[GEOT-5748] Improvements to App-Schema's connection usage

### PR DESCRIPTION
**Pull request by ridethepenguin**
https://osgeo-org.atlassian.net/browse/GEOT-5748

Backport to GeoTools 16.x (maintenance).

### CODE REVIEW

**Comment by ridethepenguin** [comment]
Online tests are included in [this GeoServer PR](https://github.com/geoserver/geoserver/pull/2464).

**Comment by bencaradocdavies** [comment]
The Travis CI build timed out so I have restarted it.

**Comment by bencaradocdavies** [comment]
Going to close and reopen to pick up the new Travis CI settings.  :-)

**Comment by bencaradocdavies** [comment]
The new build is running with Trusty. Just restarting a build reruns it with the old settings. This one should be building in parallel with `-T1C`.

**Comment by bencaradocdavies** [comment]
Going to close and reopen this PR so Travis CI can pick up its new settings and run with -T4. See mailing list. -T1C runs with 32 threads and risks exhausting memory.

**Comment by bencaradocdavies** [comment]
I must have tried restarting Travis CI at least six times. I do not know why this fails when 16.x passes on Travis CI. I will try one more close-open cycle.

**Comment by bencaradocdavies** [comment]
Travis build crashes with what looks like a four-way JVM segfault:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project gt-geopkg: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /home/travis/build/geotools/geotools/modules/plugin/geopkg && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx256M -Dorg.geotools.test.extensive=false -Dorg.geotools.test.interactive=false -Dorg.geotools.image.test.skip=false -Dorg.geotools.image.test.interactive=false -Djava.awt.headless=true -Dsun.java2d.d3d=true -Djava.io.tmpdir=/tmp -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -jar /home/travis/build/geotools/geotools/modules/plugin/geopkg/target/surefire/surefirebooter2420221713725391283.jar /home/travis/build/geotools/geotools/modules/plugin/geopkg/target/surefire/surefire8575052132179172655tmp /home/travis/build/geotools/geotools/modules/plugin/geopkg/target/surefire/surefire_702027513062812394728tmp
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project gt-xsd-wfs: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /home/travis/build/geotools/geotools/modules/extension/xsd/xsd-wfs && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx256M -Dorg.geotools.test.extensive=false -Dorg.geotools.test.interactive=false -Dorg.geotools.image.test.skip=false -Dorg.geotools.image.test.interactive=false -Djava.awt.headless=true -Dsun.java2d.d3d=true -Djava.io.tmpdir=/tmp -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -jar /home/travis/build/geotools/geotools/modules/extension/xsd/xsd-wfs/target/surefire/surefirebooter3982689390219696699.jar /home/travis/build/geotools/geotools/modules/extension/xsd/xsd-wfs/target/surefire/surefire1657093137495275086tmp /home/travis/build/geotools/geotools/modules/extension/xsd/xsd-wfs/target/surefire/surefire_682452000401356394711tmp
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project gt-render: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /home/travis/build/geotools/geotools/modules/library/render && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx256M -Dorg.geotools.test.extensive=false -Dorg.geotools.test.interactive=false -Dorg.geotools.image.test.skip=false -Dorg.geotools.image.test.interactive=false -Djava.awt.headless=true -Dsun.java2d.d3d=true -Djava.io.tmpdir=/tmp -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -jar /home/travis/build/geotools/geotools/modules/library/render/target/surefire/surefirebooter6706498759120036895.jar /home/travis/build/geotools/geotools/modules/library/render/target/surefire/surefire3063914071798309293tmp /home/travis/build/geotools/geotools/modules/library/render/target/surefire/surefire_716388995564455020454tmp
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project gt-netcdf: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /home/travis/build/geotools/geotools/modules/plugin/coverage-multidim/netcdf && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx256M -Dorg.geotools.test.extensive=false -Dorg.geotools.test.interactive=false -Dorg.geotools.image.test.skip=false -Dorg.geotools.image.test.interactive=false -Djava.awt.headless=true -Dsun.java2d.d3d=true -Djava.io.tmpdir=/tmp -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -jar /home/travis/build/geotools/geotools/modules/plugin/coverage-multidim/netcdf/target/surefire/surefirebooter5420743240488519957.jar /home/travis/build/geotools/geotools/modules/plugin/coverage-multidim/netcdf/target/surefire/surefire7694576548380736346tmp /home/travis/build/geotools/geotools/modules/plugin/coverage-multidim/netcdf/target/surefire/surefire_691462140312998052970tmp
```

**Comment by bencaradocdavies** [comment]
I cannot reproduce the crash locally. I have created a [debug-travis-crash branch](https://github.com/geotools/geotools/tree/debug-travis-crash) to see if I can reproduce. This is made from a local merge of your pull request branch onto 16.x.

**Comment by bencaradocdavies** [comment]
The only suspicious output from Maven on Travis is: `Final Memory: 539M/2133M` which suggests a ridiculous waste of memory in the `/etc/mavenrc`. Travis bug reports have much complaining problems configuring `MAVEN_OPTS`.

**Comment by bencaradocdavies** [comment]
Cannot reproduce. [Travis build passes fine on the `debug-travis-crash` branch](https://travis-ci.org/geotools/geotools/builds/254288702).

**Comment by bencaradocdavies** [comment]
[The 16.x build passed on Travis](https://travis-ci.org/geotools/geotools/builds/254291304). I need a drink.

**Pull request merged**
