### PR TITLE
[GEOT-6172] Replace jar-collector with assembly for bin download  to reliably includes required jars

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-6172](https://osgeo-org.atlassian.net/browse/GEOT-6172) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Use markdown-page-generator-plugin to generate html files for release (License have been updated and converted to markdown as necessary, with license notice clearly marked as such).

# Checklist

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not causing two modules to share the same Java packages (to avoid [Java 9+ split package](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed) issues)
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [x] There is an issue in https://osgeo-org.atlassian.net/browse/GEOT-6172
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [x] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by jodygarnett** [comment]
The logs are being a bit too verbose presently, may carve off a release folder.

I am assuming the jar collector only used to stage binaries in the root target for assembly, and could be removed now that assemblies can be constructed from dependencies.

**Comment by aaime** [comment]
@jodygarnett removing the jar collectors would be a pretty good net improvement

**Comment by aaime** [comment]
I'm not familiar with this plugin. Do you have an example of how the generated HTML pages look like, and where they end up as part of the release packages?

**Comment by jodygarnett** [comment]
I have been using this plugin for a bit, and finally made some pull requests to it over the weekend (to mark it thread safe and cut down on some logging). 

I configured the plugin with our svg logo inline for the header, and some osgeo text in the footer. It looks quite nice.

**Comment by jodygarnett** [comment]
I am melting my brain with dependencySets (lots to maintain) vs moduleSets (easier to maintain but only can collect stuff as part of a full build).

**Comment by jodygarnett** [comment]
Okay I got two things to work:
- moduleSets should be the easiest to maintain, but cannot be built in isolation (requires a complete `mvn package assembly:single` ) because maven is insane
- dependencySet approach works, and works in isolation, but ends up with a lot of duplication (pom.xml lists dependencies and then assembly says where they go)

**Comment by aaime** [comment]
Do we even use the assembly plugin outside of a full release build? I don't think we do?

**Comment by jodygarnett** [comment]
@ianturton you are the developer most likely to enjoy this change. I have confirmed that the result can be used to run the Quickstart; see README.html generated by this change.

**Comment by jodygarnett** [comment]
@ianturton if you like this we can squash + merge and backport

**Review by ianturton — APPROVED** [review]
lgtm

**Pull request merged**
