### PR TITLE
Upgrade flatgeobuf 3.4.0 -> 3.10.1

### PR DESCRIPTION
**Pull request by groldan**
Upgrade flatgeobuf 3.4.0 -> 3.10.1, follow up to https://github.com/geoserver/geoserver/pull/4819

# Checklist

Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [ ] The changes are not causing two modules to share the same Java packages (to avoid [Java 9+ split package](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed) issues)
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by groldan** [comment]
merged cause the build was broken in `main` anyways

**Comment by aaime** [comment]
Confused, the builds checks are green, with the exception of QA that's still running:

image

image

**Comment by groldan** [comment]
Hi Andrea, it's all green now. You mean confused cause I merged before all checks passed? I may have missed that one, or thought it won't matter cause the community module was broken and the QA build doesn't check it, dunno for sure, in any case we're safe I guess.

**Comment by aaime** [comment]
I meant that comment about "cause the build was broken in main anyways". It did not seem broken?

**Comment by groldan** [comment]
I see, and yet it was somehow:

```bash
$ git checkout 4e79285fe5
HEAD is now at 4e79285fe5 [GEOT-6832] WFS-NG doesn't apply acrgis strategy for versions that are not 2.0.0 (#3385)
$ mvn dependency:tree -f modules/unsupported/flatgeobuf |grep org.wololo:flatgeobuf
[INFO] +- org.wololo:flatgeobuf:jar:3.4.0:compile

$ mvn clean install -f modules/unsupported/flatgeobuf
....
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ gt-flatgeobuf ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /data2/groldan/git/geotools/master/modules/unsupported/flatgeobuf/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /data2/groldan/git/geotools/master/modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatgeobufWriter.java:[38,42] method serialize in class org.wololo.flatgeobuf.geotools.FeatureConversions cannot be applied to given types;
  required: org.opengis.feature.simple.SimpleFeature,org.wololo.flatgeobuf.geotools.HeaderMeta,java.io.OutputStream,com.google.flatbuffers.FlatBufferBuilder
  found: org.opengis.feature.simple.SimpleFeature,org.wololo.flatgeobuf.geotools.HeaderMeta
  reason: actual and formal argument lists differ in length
[ERROR] /data2/groldan/git/geotools/master/modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatgeobufWriter.java:[43,49] method serialize in class org.wololo.flatgeobuf.geotools.FeatureTypeConversions cannot be applied to given types;
  required: org.opengis.feature.simple.SimpleFeatureType,long,java.io.OutputStream,com.google.flatbuffers.FlatBufferBuilder
  found: org.opengis.feature.simple.SimpleFeatureType,int,java.io.OutputStream
  reason: actual and formal argument lists differ in length
```

**Comment by groldan** [comment]
Which turns out to be due to my local copy of the jar, since they didn't had a snapshot version set at the master branche's pom.xml, but `3.0.4`... my bad

**Pull request merged**
