### PR TITLE
[GEOT-6050] Upgrade HSQLDB to 2.4.1

### PR DESCRIPTION
**Pull request by bencaradocdavies**
https://osgeo-org.atlassian.net/browse/GEOT-6050

### CODE REVIEW

**Comment by aaime** [comment]
I think it looks good, but I have a suggestion.

Let's say we have two GeoTools applications running off the gt-epsg-hsql database, one gets upgraded, the other does not. What happens? Is the old format preserved, or hsql updates the on disk format? 
I believe it would be safer to bump the version number to 8.6.0.1, here: https://github.com/geotools/geotools/blob/dd12933f34f06d30dc09b1382106903c57b42afb/modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactory.java#L77
This would give the newer version a different path, with no chance of conflict.

**Comment by bencaradocdavies** [comment]
Sure, updated commit force-pushed. Can we also change the capitalisation of the path from `/tmp/Geotools` to `/tmp/GeoTools`. This has always bugged me. We still need the `VERSION` bump for the reasons you described above on case insensitive filesystems.

**Comment by bencaradocdavies** [comment]
Oh my. I did it to myself. I broke the test I added a few days ago.  :-(

**Comment by bencaradocdavies** [comment]
Once more, with feeling.

**Comment by aaime** [comment]
Yep, looking good and merging

**Comment by bencaradocdavies** [comment]
Thanks @aaime.

**Comment by bencaradocdavies** [comment]
If this change reduces the number of `CoverageViewTest` failures, it should be backported. I will run some test builds.

**Pull request merged**
