### PR TITLE
[GEOT-7518, GEOT-7519] Fix i18n in legend rules

### PR DESCRIPTION
**Pull request by vuilleumierc**
[GEOS-11249](https://osgeo-org.atlassian.net/browse/GEOS-11249) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR aims at resolving two issues with the i18n of legend titles (and abstracts) in SLD:

### [GEOT-7519](https://osgeo-org.atlassian.net/browse/GEOT-7519)
The i18n does not work anymore since the org.opengis refactor as GeoServer now uses the StyleBuilder (https://github.com/geoserver/geoserver/blob/c2f437acb46d5fd4a487be8c6a44a76cc9428934/src/main/src/main/java/org/geoserver/catalog/ResourcePool.java#L2216). I thought it made sense to use InternationalString for rule title and abstract in the RuleBuilder (as elsewhere)
### [GEOT-7518](https://osgeo-org.atlassian.net/browse/GEOT-7518)
This is an old issue and the author proposed a patch but it seems it was not merged in the end. We encountered the same problem: when posting a SLD to GeoServer REST API, the namespace `sld:` is added everywhere, as a result the i18n of legends is lost when using the REST API.

Thanks in advance for your review / comments

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Looks good, but cannot be merged right now, it's not following the checklist properly. "There is an issue in *GeoTools Jira*" means we need two tickets in the GeoTools project, not in the GeoServer one.

Create two there as well, name them in the commit messages, and then link the GeoServer ones as dependent.
This way, when we release GeoTools, we have a proper changelog for direct GeoTools users too.

**Comment by vuilleumierc** [comment]
Thanks, I created the issues and edited the commit messages. Is it OK to keep the branch name, or should create a new one and open a new PR?

**Comment by aaime** [comment]
Don't worry about the branch name, it's of no consequence to the project. Given we try to merge with "rebase and merge" I doubt it shows up anywhere in the Geotools project history anyways.

**Comment by aaime** [comment]
Merged and scheduled for backport on 30.x

**Pull request merged**
