### PR TITLE
[GEOT-7639] JTS 1.20.0 update

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-7639](https://osgeo-org.atlassian.net/browse/GEOT-7639) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

See release notes: https://github.com/locationtech/jts/releases/tag/1.20.0

This should be coordinated with wider ecosystem:

* geowebcache: https://github.com/GeoWebCache/geowebcache/pull/1317
* geoserver: https://github.com/geoserver/geoserver/pull/7888
* jai-ext: https://github.com/geosolutions-it/jai-ext/pull/301

This is a draft PR based on building 1.20.0-SNAPSHOT locally used to explore  what changes are visible in GeoTools.

* [x] Build http://github.com/locationtech/jts 1.20.0-SNAPSHOT locally
* [x] geotools build -Dall
* [x] geowebcache build
* [x] geoserver build  -Prelease,communityRelease -DskipTests
* [x] geoserver build  -Prelease
* [x] waiting on 1.20.0 release (@dr-jts is looking at a system property for RelateNG)

I am not sure if the changes reflected warrant a note in the documentation update instructions?
 

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by jodygarnett** [comment]
Based on my testing I would like to give JTS crew a 👍🏻 to release!

- Martin is looking at introducing a system property to toggle between "RelateOp" and "RelateNG" implementations this week
- There is a PR for WKBReader / WKBReader to test https://github.com/locationtech/jts/pull/734

**Comment by mprins** [comment]
Hopefully this will be part of GeoTools 32?

**Comment by jodygarnett** [comment]
> Hopefully this will be part of GeoTools 32?

It seems likely. Going to release JTS 1.20.0 this week (and update this PR). JTS 1.20.0 will be announced on September 4th.

We do not have resources to make a GeoTools 32-RC next week, so this will be part of GeoTools 32.0 on September 18th.

**Comment by jodygarnett** [comment]
Leaving this in Draft until September 4th when JTS 1.20.0 is reviewed by eclipse (to see if I signed all the jars) and released.

**Comment by jodygarnett** [comment]
https://github.com/locationtech/jts/releases/tag/1.20.0 is now announced.

I think we need matching PRs for GWC and GeoServer

**Comment by jodygarnett** [comment]
rerunning downstream integration build

**Pull request merged**
