### PR TITLE
[GEOT-5231] OracleSQLDialect doesn't override both encodeColumnName

### PR DESCRIPTION
**Pull request by nmco**

### CODE REVIEW

**Comment by aaime** [comment]
@ianturton you opened the ticket, opinions?

**Comment by ianturton** [comment]
I don't think that will help, I'll try to build a test to check the actual bug and see if this fixes it.

**Comment by aaime** [comment]
Hi @ianturton any progress on tests?

**Comment by aaime** [comment]
This one has gone stale... anyone offended if I just close it?

**Comment by nmco** [comment]
As far I'm concerned you can close it. But unless I miss something I think it solves the original issue.

**Comment by jodygarnett** [comment]
@nmco as you can see it is hard to ask a volunteer to write a test (very few people have a toy oracle environment to work against). If you are in a position to confirm your fix with a test case please consider doing so.

**Comment by nmco** [comment]
I will write a test for this a test it against an oracle instance (I will work on this this weekend).

**Comment by tbarsballe** [comment]
@nmco - Any update on that test case?

**Comment by bencaradocdavies** [comment]
@nmco have you had a change to write that unit test?

**Comment by ianturton** [comment]
[see PR 1183](https://github.com/geotools/geotools/pull/1183) for latest version of this

**Pull request closed without merging**
