### PR TITLE
[GEOT-5697] fix encoding the filter Not( is null ) as XML

### PR DESCRIPTION
**Pull request by mprins**
- [x] Add a failing testcase to illustrate [GEOT-5697](https://osgeo-org.atlassian.net/browse/GEOT-5697)
  - [x] Add a fix

### CODE REVIEW

**Comment by mprins** [comment]
I Would like to have feedback the correctness of this, it took me some time to get a grasp of the way the testing works, and still not 100% convinced...

Will prepare backports if this is OK.

**Comment by aaime** [comment]
@mprins, I'm just as surprised as you by the diff :-)
@jdeolive do you have time for a quick look?

**Comment by jdeolive** [comment]
@mprins @aaime Change looks good to me.

**Comment by mprins** [comment]
Anything I can do to get this merged? it would be nice to have this fixed in 17.2 (having missed the 16.4 release)

**Pull request merged**
