### PR TITLE
GEOT-4992: fixing maven profile to skip image comparison tests

### PR DESCRIPTION
**Pull request by dromagnoli**

### CODE REVIEW

**Comment by jodygarnett** [comment]
So why default to skipping tests?

**Comment by simboss** [comment]
exact same question here.

**Comment by aaime** [comment]
As far as I can see, the default value for the property is false, and there is the skip.image.tests profile that can turn it to true when enabled. What am I missing?

**Comment by dromagnoli** [comment]
I confirm Andrea's feedback: The property is false by default (NO SKIP). You may skip tests by setting the skip.image.tests profile.

**Pull request merged**
