### PR TITLE
[GEOT-5717] - MongoDB support optional milliseconds in ISO8601 date/time string

### PR DESCRIPTION
**Pull request by newmanw**
JIRA issue:

https://osgeo-org.atlassian.net/browse/GEOT-5717

### CODE REVIEW

**Comment by jodygarnett** [comment]
Thanks @newmanw (can I confirm you filled in the CLA as per the CONTRIBUTING.md instructions? TLDR - need to be okay donating source code to OSGeo).

@nmco are you able to review?

**Comment by newmanw** [comment]
@jodygarnett sorry for the delay, just sent the CLA.

**Comment by tbarsballe** [comment]
In the interim, this wound up with merge conflicts. If you can fix these conflicts, this should be ready to merge.

**Comment by newmanw** [comment]
@tbarsballe, Thanks this should be ready to go.  Their is one test failing although I am not sure it is related.

**Comment by tbarsballe** [comment]
The test failure in NetCDF gridcoverage is probably not related. I've restarted the CI build, we'll see if it works this time around

**Comment by tbarsballe** [comment]
Looks like it passed. Merged; thanks for the contribution.

**Pull request merged**
