### PR TITLE
[GEOT-5561][GEOT-5564] Add an SLD vendor option to underline labels (16.x)

### PR DESCRIPTION
**Pull request by nmco**
Backport of this pull requests:
- https://github.com/geotools/geotools/pull/1371
- https://github.com/geotools/geotools/pull/1375

Associated GeoServer pull request:
- https://github.com/geoserver/geoserver/pull/1997

Mailing list discussion:
- http://osgeo-org.1560.x6.nabble.com/Backporting-the-SLD-underline-text-vendor-option-td5296554.html#a5296627

Associated issues:
- https://osgeo-org.atlassian.net/browse/GEOT-5561
- https://osgeo-org.atlassian.net/browse/GEOT-5564

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
@nmco I do not think this PR includes the https://github.com/geotools/geotools/pull/1375 changes.

**Comment by nmco** [comment]
You are correct @bencaradocdavies, not sure what happen maybe I forgot the push after adding the second commit. Thanks for the warning.

**Comment by nmco** [comment]
The build fails in the ``JDBC DataStore Support`` module:
```
ests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.079 sec <<< FAILURE! - in org.geotools.jdbc.JDBCTransactionStateTest
testSetTransactionNullWithExternalConnection(org.geotools.jdbc.JDBCTransactionStateTest)  Time elapsed: 0.01 sec  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.geotools.jdbc.JDBCTransactionStateTest.setupLogHandler(JDBCTransactionStateTest.java:64)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. although stubbed methods may return mocks, you cannot inline mock creation (mock()) call inside a thenReturn method (see issue 53)

	at org.geotools.jdbc.JDBCTransactionStateTest.setupLogHandler(JDBCTransactionStateTest.java:73)
```

Locally I'm not able to reproduce this problem. This seems to be unrelated to this PR.

**Comment by aaime** [comment]
Yeah, it has been failing on Travis for a while now, I also cannot reproduce locally and while there are some discussions on the net about it, I cannot quite figure out how they relate to this case. I'm just a bit dubious that the handler is passed to the logger before its behavior definition is complete, but as far as I can see, the code in addHandler just calls getClass on it.

**Pull request merged**
