### PR TITLE
[GEOT-6875] Add JDBC Informix Datasource

### PR DESCRIPTION
**Pull request by GeorgeDewar**
[GEOT-6875](https://osgeo-org.atlassian.net/browse/GEOT-6875) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR adds a DataSource plugin for Informix, with the main intention of allowing GeoServer to work with an Informix database. Land Information New Zealand have been using this in Production for more than a year but would like to contribute it back to the community.

**Please note:** This is my first substantial contribution to GeoTools and there is a chance I have got something wrong either technically or process-wise; my apologies if so.

**Also note:** I haven't added a GitHub action for online tests. Should it be added in this PR, or in a subsequent PR, or not at all?

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
I did not check the PR yes, but I can give you some quick feedback:
* Do not change the shared tests, override them in your DB specific subclasses instead
* A Github PR check is most welcomed (and actually becoming a requirement), up to you to decide if doing it in this PR or in a subsequent one, provided it's done soon
* New modules normally start in "unsupported" and then graduate to supporting land via a formal proposal showing they satisfy [all the requirements in this page](https://docs.geotools.org/latest/developer/procedures/supported.html). I don't see a need for you to go step by step, maybe send a mail to GeoTools devel with your proposal and proof that the module is ready to go straight in supported land? Mind, this is just my personal view, whether this is allowed or not, it's a Project Management Committee decision.

**Comment by GeorgeDewar** [comment]
Thanks Andrea - that's very helpful. I will undo the change to the shared tests and have sent a message to the mailing list regarding the status of the module.

**Comment by mprins** [comment]
You could add something similar to https://github.com/geotools/geotools/blob/main/.github/workflows/db2_online.yml  but using eg. `ibmcom/informix-developer-database:14.10.FC7W1DE` for online testing, see also https://hub.docker.com/r/ibmcom/informix-developer-database

**Comment by GeorgeDewar** [comment]
@aaime I have updated the tests to not modify the base classes at all, and also marked the JDBC driver JAR as "provided" to ensure there are no licensing issues. I'll leave a little more time for responses on the mailing list but if I don't hear more, I think I'll move the module to unsupported.

**Comment by aaime** [comment]
@GeorgeDewar all devs have full-time jobs so don't treat lack of feedback as lack of interest, it's really lack of time. Patience is of the essence.

**Comment by GeorgeDewar** [comment]
@aaime as discussed on the mail group, I've made the driver no longer "provided", and added reference to the licence agreement in the docs. Regarding commits, since the PR is now up I thought it best to leave the commit history in place and only squash once it's approved, so that the history can be understood while it's being reviewed. Let me know if you prefer it always to show as a single commit.

**Comment by aaime** [comment]
@GeorgeDewar sorry for the delay, if you paid attention to the GeoServer blog you might have noticed we were a tad busy. 
Merged.

**Comment by GeorgeDewar** [comment]
Thank you very much @aaime

**Pull request merged**
