### PR TITLE
Trying out GitHub actions for Windows builds

### PR DESCRIPTION
**Pull request by aaime**
AppVeyor appears to be unreliable, let's see how GitHub own Windows CI supports fares?

### CODE REVIEW

**Comment by aaime** [comment]
@groldan I'm trying out GitHub Windows CI as an alternative to AppVeyor. The build failed in the test you recently re-enabled, from the logs:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.289 s <<< FAILURE! - in org.geotools.util.URLsTest
[ERROR] testUrlToFileWindowsShareFile(org.geotools.util.URLsTest)  Time elapsed: 0 s  <<< ERROR!
java.net.MalformedURLException: Illegal character found in host: '/'
	at org.geotools.util.URLsTest.testUrlToFileWindowsShareFile(URLsTest.java:122)

[ERROR] testUrlToFile(org.geotools.util.URLsTest)  Time elapsed: 2.289 s  <<< ERROR!
java.net.MalformedURLException: Illegal character found in host: '/'
	at org.geotools.util.URLsTest.testUrlToFile(URLsTest.java:91)
```

Will try on a Windows laptop later, wondering if it rings any bell to you?

**Comment by aaime** [comment]
Modified the test based on the conversation on geoserver-users. Works fine on my windows laptop + latest JDK 8, let's see if it works fine here too.

**Comment by aaime** [comment]
The GitHub Windows CI build passed, @jodygarnett what do you think? Good to merge?

**Comment by jodygarnett** [comment]
> https://www.appveyor.com/docs/windows-images-software/#java

This shows running "JDK 1.8 Update 221 (x64) (C:\Program Files\Java\jdk1.8.0".

**Pull request merged**
