### PR TITLE
[GEOT-5375] Add a group by visitor (backport 14.x)

### PR DESCRIPTION
**Pull request by nmco**
Issue: https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5375

### CODE REVIEW

**Comment by aaime** [comment]
We have a one month cooldown rule for new feature backports. When did this one land on master?

**Comment by aaime** [comment]
The commit on master is a month old as far as I can see, you should now ask on gt-devel if it's ok to backport.

**Comment by nmco** [comment]
Ooops I dint' see your first comment (sorry I missed one month cooldown rule on docs), I will ask on the mailing list if is ok to backport. Thank you for the reminder :)

**Comment by jodygarnett** [comment]
Thanks for asking on geotools-devel, happy to have this work backported to 14.x.

(and thanks for include docs in the backport)

**Pull request merged**
