### PR TITLE
[GEOT-7616] Postgis_Data_ref_set.sql updates for modern PostGIS releases

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-7616](https://osgeo-org.atlassian.net/browse/GEOT-7616) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Update Postgis_Data_ref_set.sql failure (due to use of public.ndims). This file is managed in the GeoTools library for use with integration tests in GeoServer.

This artifact `refdataset-1.0` was recovered from repo.osgeo.org history to be managed along side other app-schema resources (which have their own distinct release and version cycle from the main GeoTools library). I tried to document this a bit so feedback is welcome.

When this PR is merged I will use `mvn deploy` locally to published `refdataset-1.0` as version 1.0.8 for use in integration testing.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by jodygarnett** [comment]
The downstream https://github.com/geoserver/geoserver/pull/7772 contains fixes showing me that the `Postgis_Data_ref_set.sql` can now be used again. 

When this is merged I can run `mvn deploy` to publish the updated jar.

**Comment by aaime** [comment]
I can't help with the app-schema portion of this PR, but I'll note there is a bunch of un-related documentation changes. I'll be happy to review those in a separate PR, they don't belong in this one anyways.

**Comment by jodygarnett** [comment]
The doc changes describe what I am doing here (bundling data for distribution out of band with geotools release cycle - not something I was aware was a thing)

**Comment by aaime** [comment]
Hum... I started looking yesterday and gave up after seeing changes to these two:
docs/developer/conventions/code/qa.rst
docs/developer/conventions/code/style.rst

The rest seems indeed related to the PR

**Comment by jodygarnett** [comment]
Yeah it was test date that was in error so I wanted to find out where it came from.

as the doc changes are non functional they should be fine

**Comment by jodygarnett** [comment]
@nmco can I merge this ahead of 2.26.0 release?

**Comment by nmco** [comment]
Hi @jodygarnett +1 looks good to me, thx.

**Comment by jodygarnett** [comment]
This has a follow up PR https://github.com/geotools/geotools/pull/4892 updating deploy instructions

**Pull request merged**
