### PR TITLE
[GEOT-5995] Move MongoDB unsuported module to plugins

### PR DESCRIPTION
**Pull request by nmco**
Associated issue:
https://osgeo-org.atlassian.net/browse/GEOT-5995

Mailing list discussion:
http://osgeo-org.1560.x6.nabble.com/Promoting-MongoDB-as-an-extension-supported-plugin-td5358353.html

### CODE REVIEW

**Comment by aaime** [comment]
@jodygarnett what do you mean by double check? You're "requesting a change" but don't specify what needs to be changed. Some work on your communication would be appreciated, it's often not clear/actionable.

**Comment by dromagnoli** [comment]
I think that he was referring to the userguide index.html page listing the mongodb plugin in the unsupported module section. That page should be probably updated switching the plugin to the proper section.

**Comment by nmco** [comment]
Ah! True indeed didn't notice that one, thank you @dromagnoli !

**Comment by nmco** [comment]
PR updated, thanks all for the feedback.

**Comment by aaime** [comment]
Reformat impending, hopefully @nmco has addressed @jodygarnett feedback, merging

**Pull request merged**
