### PR TITLE
[GEOT-0000] Make ErrorProne run on Windows

### PR DESCRIPTION
**Pull request by bestrauss**
[GEOT-0000](https://osgeo-org.atlassian.net/browse/GEOT-0000) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

 Changes to file `pom.xml` to make `ErrorProne` run on Windows, where file names, including `${project.build.directory}`, contain backslashes.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by bradh** [comment]
Can you please create the Jira ticket and update?

Alternatively, you could remove that part from the commit message and PR - less desirable.

**Comment by bradh** [comment]
@bestrauss Note that I'm not adverse the change - its good to see Windows development getting some attention.

**Comment by bestrauss** [comment]
This PR is comissioned by Andrea Aime.
When I renamed the branch, the PR got closed automatically. So I created a new one.

**Comment by bradh** [comment]
np. You probably didn't need to rename the branch, just force push an edited commit message and update the PR. Your approach works too though.

**Pull request closed without merging**
