### PR TITLE
GEOT-5261 Delete record from geometry_columns when featureType removed

### PR DESCRIPTION
**Pull request by oscarfonts**
See https://osgeo-org.atlassian.net/browse/GEOT-5261

### CODE REVIEW

**Comment by jodygarnett** [comment]
Thanks @oscarfonts - my initial review is fine (need to update headers but you can do that).

**Comment by oscarfonts** [comment]
Headers updated.
Thanks @jodygarnett for the review.

**Comment by oscarfonts** [comment]
Realized that there is some code overlap with PR #1020. Please accept this one before I fix the other, so I have the chance to sort out the potential merge conflicts before they get to you. Thx again!

**Comment by bradh** [comment]
Did a local build and test, inspected the code and tests.

Looks good.

Recommend it be merged.

**Pull request merged**
