### PR TITLE
[GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore

### PR DESCRIPTION
**Pull request by bestrauss**
[GEOT-7491](https://osgeo-org.atlassian.net/browse/GEOT-7491) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Use `GeometryFactory` of the `ShapeFileDataStore` if there is one and the `Query` has none.
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Review by ianturton — APPROVED** [review]

**Review by mprins — COMMENTED** [review]
the imports will need to be fixed for 28.x and 29.x branches 
- https://github.com/geotools/geotools/pull/4554
- https://github.com/geotools/geotools/pull/4553

due to the API changes and package refactoring

**Comment by bestrauss** [comment]
@mprins 
Thank you.

I'm nor sure whether I am expected to deal with the backports. Since I use Windows OS, backports of https://github.com/geotools/geotools/pull/4479 to 29.x and 28.x would help me in the process.

**Comment by mprins** [comment]
I'll see what I can do, note that 28.x is EOL, so releases of that are unlikely

**Comment by aaime** [comment]
Just out of curiosity, what is the relationship with Windows OS? "Since I use Windows OS, backports.... ".
Is GeoTools 30.x having issues on Windows?

**Comment by bestrauss** [comment]
@aaime
See https://github.com/geotools/geotools/pull/4479. `ErrorProne` does not work correctly in case `File.separatorChar == '\\'`, which is given on Windows OS. A workaround has been merged recently, but no backports to 29.x and 28.x.

**Comment by aaime** [comment]
I've added backport labels to that PR, let's see if the bot manages to create backports PRs for it. Otherwise feel free to issue backport PRs yourself.

**Pull request merged**
