### PR TITLE
GEOT-6721 Fixed CylindricalEqualArea.getParameterValues doesn't set s…

### PR DESCRIPTION
**Pull request by turingtestfail**
Fixed CylindricalEqualArea.getParameterValues doesn't set standard_parallel_1

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [ x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x ] PR for bug fixes and small new features are presented as a single commit
- [X ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ X] New unit tests have been added covering the changes
- [X ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- X[ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by aaime** [comment]
Looks good to me, apparently there is a merge conflict to be resolved:

image

Seems easy, we just switched not to have wildcard imports (part of the coding convention that we adopted, it's just that we did not have a way to enforce it before, @ianturton did the work to remove the wildcard imports and add a PMD rule for it a few days ago).

**Comment by turingtestfail** [comment]
Conflict resolved.

Thanks,
Joseph Miller

**Comment by aaime** [comment]
Looks like change was pushed done without a local build, the code is not formatting according to conventions:

```
[ERROR] Found 1 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn fmt:format"
[ERROR] Non complying file: /home/travis/build/geotools/geotools/modules/library/referencing/src/test/java/org/geotools/referencing/wkt/ParserTest.java
```

Easy fix, just run a ``mvn install`` in the modules you've modified and it will reformat the code for you.

**Comment by turingtestfail** [comment]
Uggh, Intellij must have reformatted something.  Fixed.

Thanks,
Joseph Miller

**Comment by aaime** [comment]
Merged. Backport if you/as you see fit.

**Pull request merged**
