### PR TITLE
fix possible NPE issue during MySQLVersion56 check

### PR DESCRIPTION
**Pull request by nprigour**
Signed-off-by: Nikolaos Pringouris <nprigour@gmail.com>

### CODE REVIEW

**Comment by nprigour** [comment]
good to be back-ported to version 19.x also

**Comment by aaime** [comment]
Looks like an obvious fix, did you stumble into it by reading code or did it actually happen?
If the latter, please open a ticket and describe how, for the release notes, then refer to the ticket from the commit message.

**Comment by nprigour** [comment]
Indeed it is obvious and to be honest it was introduced by me while updating mysql plugin to work with the latest mysql versions.
Actually I fall on it by change but it may occur while i.e. trying to create a mysql DataStore against a Mysql DB that is down or unreachable.

**Comment by aaime** [comment]
Roger, merging on master only then (based on the lack of tests)

**Comment by nprigour** [comment]
would it be possible to backport this to 19.x?

**Comment by aaime** [comment]
I already made an exception to the test rules by merging on master, under the consideration that is a developer series that will not see a release for some time. If you want backports please add tests :-)

**Comment by nprigour** [comment]
But how is it possible to add a test case for such an obvious error?
I can i.e. add a test that attempts to open a connection to an unreachable (non existent)  Datasource and assert that no exception is thrown from the final block. Would that be enough to accept the fix for backporting?

**Comment by aaime** [comment]
Yes, check that you're not getting a NPE :-)

**Comment by nprigour** [comment]
OK I will try to implement such a test the following days. Should I reopen this or do it in a seperate pull request?

**Comment by aaime** [comment]
Euh, this one got merged, a new PR with the test is probably best.

**Pull request merged**
