### PR TITLE
[GEOT-5406] Ignore NetCDF grid_mapping_name that is present but unsup…

### PR DESCRIPTION
**Pull request by bencaradocdavies**
…ported

The current behaviour of ```NetCDFProjection``` when encountering an unsupported NetCDF ```grid_mapping_name``` is to throw a ```NullPointerException```. This fix changes its behaviour to instead log a message and return null, consistent with the behaviour earlier in the method for a missing ```grid_mapping_name```.

https://osgeo-org.atlassian.net/browse/GEOT-5406

### CODE REVIEW

**Comment by simboss** [comment]
Obvious fix, I would add a test ;)

**Comment by bencaradocdavies** [comment]
@simboss test added; always worthwhile. :-)

**Comment by bencaradocdavies** [comment]
Added even more testing goodness.

**Comment by simboss** [comment]
I would go ahead and merge this.

Would you be so kind to backport this to 14.x?

**Comment by bencaradocdavies** [comment]
Sure. Cherry-picked onto 14.x in https://github.com/geotools/geotools/commit/b87246b11bd53e02abeb48722860a4cd9b55e508

**Pull request merged**
