### PR TITLE
[GEOT-6495] Elasticsearch community module

### PR DESCRIPTION
**Pull request by sjudeng**
Elasticsearch community module from https://github.com/ngageoint/elasticgeo

https://osgeo-org.atlassian.net/browse/GEOT-6495

Working on:

- [x] CLA signed, note software grant contains some public domain work
- [x] Any tests/QA checks that fail in CI

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [x] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by sjudeng** [comment]
The Elasticsearch module tests use Docker, which works in Travis but not AppVeyor. Should I add a flag that skips them under AppVeyor or is another approach recommended?

**Comment by aaime** [comment]
Hi @sjudeng tests using docker involve possibly large downloads and are surely slower to run that unit tests, please mark them as online so that they don't run by default. We normally make it so that these tests don't run unless -Ponline is setup. 
Having a docker setup is still going to help setup a dedicated build on the server, and we could look into having a dedicated GitHub action for it too.

**Comment by sjudeng** [comment]
Thanks @aaime, I updated to move the Docker tests under the online profile as suggested. Those tests were passing under Linux and OSX through Travis and GitHub CI, with build time around two minutes, so it would be good to eventually get them running automatically as well at least in those environments.

**Comment by aaime** [comment]
So for this PR what we need now is the CLAs right?

**Comment by sjudeng** [comment]
@aaime Yes, waiting on CLAs from other contributors. I have an update I can post on the dev list since we have a related discussion started there.

**Comment by aaime** [comment]
@sjudeng has the situation clarified enough for you to move on?

**Comment by sjudeng** [comment]
@aaime Yes I think it might be ready to proceed but I have a question out on the dev list to confirm.

**Comment by jodygarnett** [comment]
Making the CLA as signed, thanks for grinding through the use of public domain (always a pain).

**Comment by aaime** [comment]
@jodygarnett so can this one be merged?

**Comment by sjudeng** [comment]
I updated to further squash commits down as much as I could while still preserving author attribution. Also prefixed all commit messages with `gt-elasticsearch` for clarity though let me know if that's not preferred and I can remove.

@aaime It looks like at least the CLA issue is resolved based on the comments above, in https://github.com/geotools/geotools/pull/2749#issue-362409542 and on the mailing list. I'm not aware of any other blockers. Thanks to you and @jodygarnett for all your time and assistance in getting us to this point.

**Comment by aaime** [comment]
@jodygarnett I'll let you do the honors, the discussion about licensing left me pretty confused, cannot take responsibility for merging this one.

**Comment by jodygarnett** [comment]
Docs are under data, not unsupported, going to make that fix after merge.

**Pull request merged**
