### PR TITLE
[GEOS-7768] Filter function "greaterEqualThan" is not properly working

### PR DESCRIPTION
**Pull request by matchami**
gt/gte/lt/lte methods in StaticGeometry modified to delegate to FilterFactory2 as suggested by Andrea.  Have also tidied up code formatting.  Actual changes are lines 44-52 and 700-727

### CODE REVIEW

**Comment by aaime** [comment]
The diff is not readable bcause the entire file got reformatted. The contribution instructions specifically warn against that:
https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md

> Please make sure you're following the coding conventions, and otherwise avoid any reformats to the existing code, as they make it harder to review your changes.

**Comment by matchami** [comment]
Hi Andrea,

Try this:  git diff -w master filterfix -- modules/library/main/src/main/java/org/geotools/filter/function/StaticGeometry.java

with regard to the decision to tidy up the formatting, my apologies I genuinely mis-remembered the instructions on this.  I think I confused the bit saying please DO put in missing copyright statements with the bit saying please DON'T fix formatting.  I mistakenly thought that bringing old code up to the coding standards would be a good thing and I think as I was pulled up on code formatting a previous pull request I was overly conscious that it was there!  I will not make that mistake again.  In this case, do you genuinely want me to put the non-compliant code formatting back in and resubmit the pull request?  It seems like a bit of a backwards step ??? but I can do that if you want?

Thanks
Iain

**Comment by matchami** [comment]
BTW  you should also note that the paragraph you have quoted from the code contribution guidelines actually supports my changes: "and OTHERWISE avoid any reformats to the existing code."  The implication here (which is why I was confused) is that reformats to implement coding standards are desired.  

I do realise that the follow sentence suggests a separate commit for these changes - which clearly I did not get right.

Thanks

**Comment by aaime** [comment]
Reformats are not welcomed, they are tolerated if and only if:

- They are done in a separate commit (can be in the same pull request) to allow reviewing the actual changes directly on GitHub (I don't know how you can think we're not aware that desktop and command line tools can ignore spaces, it just takes more time and the first quick check never goes to those lenghts)
- They are backported to all active branches (to avoid conflicts)

The commit guidelines are often written by non native English speakers, if they are not clear enough feel free to clarify them in a separate pull request.

**Comment by aaime** [comment]
Btw, if you are interested in how the pull request get reviewed, there is a guide here that can help a bit:
https://github.com/geoserver/geoserver/wiki/Pull-request-review-guide
It's for GeoServer, but most of it applies to GeoTools as well.

**Comment by matchami** [comment]
Thanks Andrea , that's really helpful.  Also I will submit a proposed
change to the contribution guide as you suggest.

Cheers
Iain

**Pull request closed without merging**
