### PR TITLE
[GEOT-7598] Update PMD to version 7.2

### PR DESCRIPTION
**Pull request by aaime**
[GEOT-7598](https://osgeo-org.atlassian.net/browse/GEOT-7598) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Pairs with:
 
* https://github.com/GeoWebCache/geowebcache/pull/1279
* https://github.com/geoserver/geoserver/pull/7577

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by mprins** [comment]
@aaime The "Creating annotations for /home/runner/work/geotools/geotools/modules/plugin/iau-wkt/target/pmd.xml" messages are perhaps a result of a GH permissions problem because you are working from a personal repo/branch and the action provided in the PR is trying to write (comments) in a different target repo, whereas in https://github.com/geoserver/geoserver/pull/7577 the PR branch is in the target repo

**Comment by aaime** [comment]
@mprins good point but then... does it mean the annotations will fail for everyone making PRs from their fork?
That would not be workable, all QA builds would fail and devs would stop checking their results....

**Comment by mprins** [comment]
actually, I think GH normally runs the workflow from the main (target) branch, unless a PR changes the workflow

**Comment by aaime** [comment]
Dropping this one for now, want to prioritize Palantir and then try to use OpenRewrite to automate some of the fixes.

**Pull request closed without merging**
