### PR TITLE
tmerc: adjust coefficient from 1574 to 1575

### PR DESCRIPTION
**Pull request by don-vip**
See https://github.com/OSGeo/proj.4/issues/174 which refers to the original paper the code is based on.

### CODE REVIEW

**Comment by aaime** [comment]
A test for any bug fix or feature is required (can be skipped for community modules, but this is core) ;-)

**Comment by aaime** [comment]
See also: https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md (github links it every time one opens a pull request, but in a way that's easy to miss)

**Comment by don-vip** [comment]
@aaime thanks for your reply. I tried to implement a test based on the existing **CassiniSoldnerTest** and [EPSG guidance](http://www.epsg.org/Portals/0/373-07-2.pdf) but it fails right away, I don't understand why?

```java
package org.geotools.referencing.operation.projection;

import static org.geotools.referencing.operation.projection.MapProjection.AbstractProvider.*;
import static org.junit.Assert.*;

import org.geotools.referencing.ReferencingFactoryFinder;
import org.junit.Test;
import org.opengis.parameter.ParameterDescriptor;
import org.opengis.parameter.ParameterValue;
import org.opengis.parameter.ParameterValueGroup;
import org.opengis.referencing.operation.MathTransform;
import org.opengis.referencing.operation.MathTransformFactory;

/**
 * Unit tests of {@link TransverseMercator}.
 *
 * @source $URL$
 */
public class TransverseMercatorTest {

    /**
     * Tests the example provided by the EPSG guidance.
     * See "OGP Surveying and Positioning Guidance Note number 7, part 2 – April 2018", pages 53-57
     */
    @Test
    public void testEpsgExample() throws Exception {
        MathTransformFactory mtFactory = ReferencingFactoryFinder.getMathTransformFactory(null);
        final ParameterValueGroup parameters = mtFactory.getDefaultParameters("Transverse_Mercator");

        // build the transformation using the guidance provided values
        parameter(SEMI_MAJOR, parameters).setValue(6377563.396);
        parameter(SEMI_MINOR, parameters).setValue(6356256.910);
        parameter(LATITUDE_OF_ORIGIN, parameters).setValue(dmsToDegree(49, 0, 0));
        parameter(CENTRAL_MERIDIAN, parameters).setValue(-dmsToDegree(2, 0, 0));
        parameter(SCALE_FACTOR, parameters).setValue(0.9996012717);
        parameter(FALSE_EASTING, parameters).setValue(400000.00);
        parameter(FALSE_NORTHING, parameters).setValue(-100000.00);
        MathTransform transform = mtFactory.createParameterizedTransform(parameters);

        // results as provided by the EPSG guidance
        final double[] point = new double[] { dmsToDegree(50, 30, 0), dmsToDegree(0, 30, 0) };
        final double[] expected = new double[] { 577274.99, 69740.50 };

        // check forward transform
        final double[] forward = new double[2];
        transform.transform(point, 0, forward, 0, 1);
        assertEquals(expected[0], forward[0], 1e-1);
        assertEquals(expected[1], forward[1], 1e-1);

        // check inverse transform
        final double[] inverse = new double[2];
        transform.inverse().transform(expected, 0, inverse, 0, 1);
        assertEquals(point[0], inverse[0], 1e-4);
        assertEquals(inverse[1], inverse[1], 1e-4);
    }
    
    /**
     * Extracts the {@link ParameterValue} for a certain {@link ParameterDescriptor}
     */
    ParameterValue<?> parameter(ParameterDescriptor<?> param, ParameterValueGroup group) {
        return group.parameter(param.getName().getCode());
    }
    
    /**
     * Converts a DMS value into degrees
     */
    double dmsToDegree(double degrees, double minutes, double seconds) {
        return degrees + (minutes + seconds / 60) / 60;
    }
}
```

```
org.geotools.referencing.operation.projection.ProjectionException: Le résultat de la projection pourrait se trouver à 45 046,126 mètres de la position attendue. Êtes-vous certain que les coordonnées sont dans la région de validité de cette projection cartographique? Le point est situé à 52°05.7'E du méridien central et à 48°29.1'S de la latitude d'origine. La projection est "Transverse_Mercator".
	at org.geotools.referencing.operation.projection.MapProjection.checkReciprocal(MapProjection.java:708)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:903)
	at org.geotools.referencing.operation.projection.MapProjection.transform(MapProjection.java:938)
	at org.geotools.referencing.operation.projection.TransverseMercatorTest.testEpsgExample(TransverseMercatorTest.java:46)
```

**Comment by aaime** [comment]
@don-vip I'm guessing here, but it seems you are giving lat/lon ordinates, while the machinery expects lon/lat.

**Comment by don-vip** [comment]
A dumb error indeed, thanks!

**Comment by aaime** [comment]
Now that looks good. Is there a Jira ticket we can use for the release notes?

**Comment by aaime** [comment]
Manually merged to add one missing copyright header, squash commits and fix commit message referring to the ticket: https://github.com/geotools/geotools/commit/ac076c78fa8e8566fada82c4b6bf955a21f72b2f

**Comment by don-vip** [comment]
@aaime thank you! Sorry for the copyright header, I thought it was not required for unit tests as the other ones don't have one (I copied CassiniSoldnerTest). Are you going to add copyright headers to all files during the mass source code reformat?

**Pull request closed without merging**
