### PR TITLE
GEOT-5382: imagemosaic with multiple resolutions may throw exceptions

### PR DESCRIPTION
**Pull request by NielsCharlier**

### CODE REVIEW

**Comment by NielsCharlier** [comment]
Build is okay, can this be merged @simboss  ?

**Comment by simboss** [comment]
I am about to merge.

Will you also backport right?

**Comment by simboss** [comment]
Knock, knock, backport to the other active branches?

**Comment by NielsCharlier** [comment]
https://github.com/geotools/geotools/pull/1155

**Pull request merged**
