### PR TITLE
[GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN

### PR DESCRIPTION
**Pull request by aaime**
[GEOT-7488](https://osgeo-org.atlassian.net/browse/GEOT-7488) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Add support for reporting NaN as NODATA

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Reminder to self, this change needs a corresponding small fix in GeoServer too:

```
aaime@colossus ~/devel/git-gs (main) $ git diff
diff --git a/src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java b/src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
index b286745372..2957665358 100644
--- a/src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
+++ b/src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
@@ -1313,7 +1313,7 @@ List<CoverageDimensionInfo> getCoverageDimensions(GridSampleDimension[] sampleDi
                         double max = cat.getRange().getMaximum();
 
                         dim.getNullValues().add(min);
-                        if (min != max) {
+                        if (!(Double.isNaN(min) && Double.isNaN(max)) && min != max) {
                             dim.getNullValues().add(max);
                         }
                     }
```

**Review by dromagnoli — APPROVED** [review]
Looks good to me

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 38eca98d08... [GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffIIOMetadataDecoder.java
Auto-merging modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
Auto-merging modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
Auto-merging modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
CONFLICT (content): Merge conflict in modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
Auto-merging modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerResponse.java
Auto-merging modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
CONFLICT (content): Merge conflict in modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
Auto-merging modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
CONFLICT (modify/delete): modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java deleted in HEAD and modified in 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN).  Version 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN) of modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java left in tree.
CONFLICT (modify/delete): modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/indexer.properties deleted in HEAD and modified in 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN).  Version 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN) of modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/indexer.properties left in tree.

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4536-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 38eca98d08399053bc85bbfd3ca709266eaabf58
# Push it to GitHub
git push --set-upstream origin backport-4536-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4536-to-29.x`.

**Comment by aaime** [comment]
The backport to `30.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 38eca98d08... [GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
Auto-merging modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
CONFLICT (content): Merge conflict in modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
Auto-merging modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
CONFLICT (content): Merge conflict in modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
CONFLICT (modify/delete): modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java deleted in HEAD and modified in 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN).  Version 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN) of modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java left in tree.
CONFLICT (modify/delete): modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/indexer.properties deleted in HEAD and modified in 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN).  Version 38eca98d08 ([GEOT-7488] GDAL, GeoTIFF and ImageMosaic ignore nodata when it's NaN) of modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/indexer.properties left in tree.

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-30.x 30.x
# Navigate to the new working tree
cd .worktrees/backport-30.x
# Create a new branch
git switch --create backport-4536-to-30.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 38eca98d08399053bc85bbfd3ca709266eaabf58
# Push it to GitHub
git push --set-upstream origin backport-4536-to-30.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-30.x
```
Then, create a pull request where the `base` branch is `30.x` and the `compare`/`head` branch is `backport-4536-to-30.x`.

**Pull request merged**
