### PR TITLE
[GEOT-7377] Corrected off-by-one-error to find upper left tile

### PR DESCRIPTION
**Pull request by gillesB**
[GEOT-7377](https://osgeo-org.atlassian.net/browse/GEOT-7377) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

There was a off-by-one error in WMTSTileService and WMTSTileFactory whose result was that tiles were found which do not intersect the requested envelope.

An existing test was extended to check the intersections.

Fixes: https://osgeo-org.atlassian.net/browse/GEOT-7377

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project gt-wmts: Fatal error compiling: Illegal/unsupported escape sequence near index 3
[ERROR] C:\Users\gilles.baatz\git\gilles\geotools\modules\extension\wmts\target/generated-sources/.*
```

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by gillesB** [comment]
To explain the changed unit test a bit, I created a visualization.

image


In the first part of `WMTSTileServiceTest.findTilesInExtentUsingLimits()` the bigger yellow envelope is requested.
And the two tiles are returned.
In the second part the smaller yellow envelope is requested. Before the change the same two tiles were returned.
After the change only `wmts_2_1_2` is returned.

(The green envlope is the boundix box of the tile matrix set. The red envelope is the limit of the tile matix set link.)

**Comment by gillesB** [comment]
I have not realized that I broke `WMTSTileFactory4326Test.testGetTileFromCoordinate()` as there was already one broken test in `main` (`WebMapTileServerTest.testGetTile())`.

**Comment by aaime** [comment]
We're looking at the image and are a bit confused. The red "envelope" is... a reprojected rectangle? Maybe towards Lambert or Polar? And why are the top and bottom parts of that envelope not covered by tiles? We would expect to see two more tiles at the top and two at the bottom?

**Comment by gillesB** [comment]
To avoid mistakes from my side I describe in the following in detail how I created the picture.

* I opened QGIS and then dragged the OSM Layer to the active layers.
* Then I switched the QGIS project CRS to EPSG:32633 
  * This is the reason why the OSM layer is "rounded"  
* Afterwards I created `Temporary Scratch Layers` to draw the different polygons in their actual CRS
  * This means the the red and yellow envelops were reprojected by QGIS
  * To create the different polygons I simply copy/pasted the coordinates from the source code of `WMTSTileServiceTest.findTilesInExtentUsingLimits()` respectively from the created Java objects while debugging.

The green layer is:

* `tileMatrixSet.setBbox(new CRSEnvelope("EPSG:32633", -300000, 6400000, 1300000, 8000000))`

The yellow layer is:

* `ReferencedEnvelope requestEnvelope =
                new ReferencedEnvelope(7.1, 12.1, 61.4, 64.6, CRS.decode("EPSG:4326", true));`
* `ReferencedEnvelope requestEnvelope2 =
                new ReferencedEnvelope(12.5, 15.3, 64.3, 66.0, CRS.decode("EPSG:4326", true))`

The red layer is:

```
createLayerWithLimits(
        limits,
        new CRSEnvelope(
                new ReferencedEnvelope(
                        4.4, 14.7, 57.8, 65.3, CRS.decode("CRS:84"))))
```

As for the tiles: 

I just draw `wmts_2_0_2` and `wmts_2_1_2` because those are the only tiles which are returned by both calls to `service.findTilesInExtent()` in the `main` branch.

I hope this clears things up a bit.

**Comment by ianturton** [comment]
I'll check more thoroughly tomorrow but I suspect that this is due to
mixing projections and is probably due to curvature of the sides of your
box.

Ideally you need to provide a single box based request for us to check,
along with a list of expected tiles and observered tiles.

**Comment by gillesB** [comment]
I think the SSCCE in the original Jira Issue is a better example. It uses a real world layer and also only one projection.

**Comment by prusswan** [comment]
I may have encountered a similar issue (through geoserver), from the logs `wmts.client` *thinks* the zoom 0 tile is bounded by the yellow outline (when the actual tile is labelled as 0,0,-1):

image

**Pull request closed without merging**
