### PR TITLE
[GEOT-5882] add extra vendor option displacementMode

### PR DESCRIPTION
**Pull request by nprigour**
An extra SLD vendor option 'displacementMode' is proposed to control the direction a text label is rendered for point and polygon geometry types.
The pull request addresses the improvement proposed in jira issue  [[GEOT-5882]](https://osgeo-org.atlassian.net/browse/GEOT-5882)

Signed-off-by: Nikolaos Pringouris <nprigour@gmail.com>

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
@nprigour please discuss this proposal on the developer mailing list. It needs review by those knowledgeable about SLD.

**Comment by aaime** [comment]
Agreed. In general when pushing a new functionality talk first (on the developer list), implement later :-)

**Comment by nprigour** [comment]
Hi @aaime , @bencaradocdavies ,
Is the developer list the one hosted in sourceforge (https://sourceforge.net/projects/geotools/lists/geotools-devel)?
I just subscribe but cannot find a way to create a new thread! Should I also have a sourceforge account to do so or di I miss something?

**Comment by bencaradocdavies** [comment]
@nprigour once subscribed, send email to geotools-devel@lists.sourceforge.net from your subscribed email address and it will be sent to all subscribers. This creates a new "thread" in the mailing list discussion. The title of the thread will be the subject of your email.

**Comment by aaime** [comment]
Seems to be stuck in discussion on geotools-devel, no further feedback from @nprigour

**Comment by nprigour** [comment]
After discussion in [geotools-devel ](https://sourceforge.net/p/geotools/mailman/message/36162380/) it will be investigated whether code can be improved to consider a more versatile displacement mode functionality considering positions every 45 degrees (one or multiple) and checking each one provided sequentially for every displacement step.

**Comment by aaime** [comment]
@nprigour will you update this pull request?

**Comment by nprigour** [comment]
let it as it is for know. I will try as soon as possible (maybe during this weekend) to update it and see if there are conflicts due to other changes by other contributions. In that case I will close it and recreate it.

**Pull request closed without merging**
