### PR TITLE
Fix compiler errors in SWT module

### PR DESCRIPTION
**Pull request by IanMayo**
Fix some minor package name changes, single method rename.

Submitted after discussion with @moovida

### CODE REVIEW

**Comment by aaime** [comment]
The module is currently out of the build due to persistent lack of a maintainer. Could be brought in if there is anyone interested in keeping the module up (as part of the "-Dall" build, or even as part of the normal build if anyone is willing to do whatever is needed to graduate the module). Are you interested?

In the meantime, verified it builds (Travis won't do this check for us), and merging the changes.

**Comment by moovida** [comment]
@IanMayo , I apologize again for removing this during the last java 11 code sprint thinking that no one would still use it. If you want we can bring it back to life and I can work as backup maintainer for you.

Thanks @aaime

**Comment by IanMayo** [comment]
Yes please @moovida, Debrief still uses it, and Debrief is quite active: 

image

I'm no GeoTools wizard, but I'm happy to take on the maintainer role @aaime . @moovida acting as backup may just save me :-)

**Comment by aaime** [comment]
@IanMayo that's great to hear, can you please subscribed to Geotools devel and user lists then, and send a mail to devel stating that you are interested in maintaining the module?

**Pull request merged**
