### PR TITLE
[GEOT-7244] Constructor GridGeometry2D(Rectangle, Rectangle2D) looses CRS

### PR DESCRIPTION
**Pull request by roarbra**
[GEOT-7244](https://osgeo-org.atlassian.net/browse/GEOT-7244) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

The constructor was added prior to this PR.
This PR will fix a problem were the crs of the incoming userRange was omitted.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by roarbra** [comment]
Why are gt-cql failing?

[Here is the code for encoding a date in ecql](https://github.com/geotools/geotools/blob/471142b13d667f4f9194a8009f0a8885b73935c3/modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java#L101)

[Here is the code for creating the expected value within the code](https://github.com/geotools/geotools/blob/471142b13d667f4f9194a8009f0a8885b73935c3/modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLTemporalPredicateTest.java#L157)

Conclusion: If your test coincidentally starts with a timestamp having .000 for milliseconds it will fail.

**Comment by ianturton** [comment]
Oh, that's nasty

**Comment by aaime** [comment]
@roarbra did you open a ticket for that one?

**Comment by roarbra** [comment]
[Done](https://osgeo-org.atlassian.net/browse/GEOT-7249)

**Comment by aaime** [comment]
Merging, thanks!

**Pull request merged**
