### PR TITLE
Update update_site.sh for the new doc server configuration

### PR DESCRIPTION
**Pull request by tbarsballe**
Preliminary version of update_site.sh for use with the new doc server (pending)

**DO NOT MERGE** until docs.geotools.org has been migrated to the new server.

### CODE REVIEW

**Comment by tbarsballe** [comment]
@jodygarnett - I know we've got a bunch of osgeo tickets for the various server and doc migrations, but do we have an actual GEOT Jira ticket to associate this with yet?

**Comment by jodygarnett** [comment]
GeoTools already was deploying to osgeo? Confused …

**Comment by tbarsballe** [comment]
While it is deployed to osgeo, its on a different server. While we're moving things around, Regina wants to move geotools to the same server as everything else:

> I wanted to move them both to this new server and remove geotools from osgeo6 (which I’m hoping to have it just be dedicated to mail and osgeo lists).

**Comment by aaime** [comment]
@tbarsballe is it still a work in progress?

**Comment by tbarsballe** [comment]
Work in Progress - No, but it is still waiting on the GeoTools doc server to be moved before this should be merged (which is to say, we basically just need to tell Regina we're ready to make the swap then merge this after thats done).

**Comment by tbarsballe** [comment]
Re-opening - this was raised in this week's PMC meeting, previous state still stands. This can be merged whenever we have time to make the appropriate changes on Jenkins and are able to sync up with the OSGeo SAC to get the geotools doc domain switched over to the new location.

**Comment by jodygarnett** [comment]
Ping :)  Check-in with trac to see for a good time to migrate...

**Comment by jodygarnett** [comment]
@tbarsballe can this be closed?

**Comment by tbarsballe** [comment]
Its still valid/waiting on server migration (I still need to get on that).
So no.

**Pull request merged**
