### PR TITLE
[GEOT-6995] StreamingRenderer - Exception when shapefile features (3D points) get loaded into memory and displayed in a 2D coordinate system

### PR DESCRIPTION
**Pull request by ianturton**
[GEOT-6995](https://osgeo-org.atlassian.net/browse/GEOT-6995) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Having a look and... so much going off the rails:
* The CRS claims 2d data, but data returned is 3d + measure
* The feature source is given a FEATURE_2D hint, but it ends up being completely ignored because the map was fed a feature collection, which is not re-queriable (FeatureCollection.subCollection(Query) does not exist!), but just filterable... so the hints that would skip reading the Z and M are never getting to the data source. To add insult to the injury, it also means all DBF attributes are going to be read even if none is used while rendering.

All stems from giving the layer a feature collection instead of a feature source. Take aways:
- Can be fixed easily by using a feature source instead
- FeatureCollection is a pretty broken intermediate object, it could be fixed by adding ``subCollection(Query)``, and then properly implement it around in ContentFeatureCollection and all common wrappers (quite a bit of work yup)
- Given the information we have about the coordiantes is wrong, LiteCoordinateSequence should not trust its inputs and do less efficient code paths for sequences that are mis-matched from the upper level metadata.

**Comment by aaime** [comment]
Pushed a tentative fix at the LiteCoordinateSequence level.
The class was designed in such a way that it would handle dimensions, but not measures... at some point, measures were brought into the picture, possibly by changes in JTS, but without really updating LiteCoordinateSequence to handle measures (just to make it compile). The change adds a little bit of direct support for measures while cloning data.

**Comment by aaime** [comment]
@ianturton what do you think?

**Comment by ianturton** [comment]
looks good to me.

**Pull request merged**
