### PR TITLE
[GEOT-5995] Move MongoDB unsuported module to plugins (backport 19.x)

### PR DESCRIPTION
**Pull request by nmco**
Original PR:
https://github.com/geotools/geotools/pull/1866

### CODE REVIEW

**Comment by rcoup** [comment]
@nmco The mongodb module [pom.xml](https://github.com/geotools/geotools/blob/19.x/modules/plugin/mongodb/pom.xml#L16) still has `   <artifactId>unsupported</artifactId>`, seems to be causing some weirdness with my builds (`mvn dependency:resolve` fails but `mvn install` is happy  🤷‍♀️ )

**Comment by nmco** [comment]
Thanks for the heads up @rcoup I will have a look.

**Comment by rcoup** [comment]
And by "weirdness" I mean an error along these lines:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.geotools:gt-mongodb:[unknown-version] (/src/vendor/geotools/modules/plugin/mongodb/pom.xml) points at org.geotools:plugin instead of org.geotools:unsupported, please verify your project structure @ line 14, column 11
[FATAL] Non-resolvable parent POM for org.geotools:gt-mongodb:[unknown-version]: Could not find artifact org.geotools:unsupported:pom:19-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 11
```

**Comment by nmco** [comment]
Hi @rcoup, in the case you miss it the PRs fixing the parent pom.xml issue have been merged and the issue closed https://osgeo-org.atlassian.net/browse/GEOT-6019.

**Pull request merged**
