### PR TITLE
Remove gt-wfs module [GEOT-5128]

### PR DESCRIPTION
**Pull request by jodygarnett**
The gt-wfs-ng module is available as drop-in replacement. We can also close open issue reported against wfs datastore

### CODE REVIEW

**Comment by jodygarnett** [comment]
@aaime has asked that this hang out a while until he has completed testing wfs-ng against some of the more problematic wfs servers in Europe.

**Comment by aaime** [comment]
On the geoscript ml we have a user reporting that wfs-ng does not work for him, and had to go back to the old wfs module. No details though.

**Comment by jericks** [comment]
Scootie replied with more details.  It appears to be caused by the xpp3 jar.  Here is a portion of the stack trace:

May 28, 2015 9:39:44 AM org.geotools.data.ows.AbstractOpenWebService internalIssueRequest
SEVERE: Failed to execute request http://localhost:8080/geoserver/wfs?REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WFS
Caught: java.lang.LinkageError: loader constraint violation: loader (instance of <bootloader>) previously initiated loading for a different type with name "javax/xml/namespace/QName"
java.lang.LinkageError: loader constraint violation: loader (instance of <bootloader>) previously initiated loading for a different type with name "javax/xml/namespace/QName"
	at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.getXMLSchemaType(XMLGregorianCalendarImpl.java:1930)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.toXMLFormat(XMLGregorianCalendarImpl.java:1770)
	at org.eclipse.emf.ecore.xml.type.internal.XMLCalendar.<clinit>(XMLCalendar.java:191)
	at org.eclipse.xsd.impl.type.XSDDateType.getValue(XSDDateType.java:29)
	at org.eclipse.xsd.impl.type.XSDAnySimpleType.assess(XSDAnySimpleType.java:108)

I hope this helps.
Jared

**Comment by jodygarnett** [comment]
Not sure if it helps me @jericks - but we can report it as a bug against wfs-ng: https://osgeo-org.atlassian.net/browse/GEOS-7144

**Comment by jodygarnett** [comment]
Created (https://osgeo-org.atlassian.net/browse/GEOS-7152) as an issue for wfs-ng.

@NielsCharlier if this is an actual conflict it should be fixable. I do not feel comfortable keeping the original wfs module around as it is very unsupported.

**Comment by jodygarnett** [comment]
The conflict with geoscript has been resolved, unblocking this issue.

@aaime has asked that this pull request be delayed until after the beta.

**Comment by aaime** [comment]
Actually, probably until after the final, we'll have time to review and fix wfs-ng probably not sooner than the end of september

**Comment by jodygarnett** [comment]
putting this on hold until after the code freeze

**Comment by aaime** [comment]
Given the issues popped up in the last two weeks (wfs-ng failing to start at all due to data access factory randomly stealing the scene, and wfs-ng configuration not surviging a restart) I'd say nobody has yet tested wfs-ng in any seriousness... sigh...

**Comment by NielsCharlier** [comment]
Both issues seem to be caused by Adam's complex feature parser. I think they are just minor issues at the surface that unfortunately do cause serious failures in deployment. They should be easily resolved, wfs-ng proves in its unit and integration tests to be quite functional.

**Comment by aaime** [comment]
If anything it shows the plugin did not receive serious manual testing, since casual usage already unhearted two blockers. About unit test coverage, I've just updated cobertura to 2.7 in order to get the module coverage, which is 57%... more than enough for a community module, but it's not exactly telling us what other issues might be lurking in the remaining 43%.

image

**Comment by bencaradocdavies** [comment]
Are we still going to remove gt-wfs? This PR has conflicts.

**Comment by jodygarnett** [comment]
Based on email discussion I am withdrawing this proposal, will factor out abstract datastore and friends into a legacy module.

**Comment by jodygarnett** [comment]
This can now be reconsidered for GeoTools 17

**Comment by jodygarnett** [comment]
Closing this out, will handle as a seperate pull request.

**Pull request closed without merging**
