### PR TITLE
[GEOT-6538] GeoJson module closes input writers

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

This PR adds a wrapper around OutputStreamWriters so that they are not closed.  This allows clients to manage their own writers better.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [X] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [X] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [X] New unit tests have been added covering the changes
- [X] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [X] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [X] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by jnh5y** [comment]
Since this is a very small change in an unsupported module, I haven't entered a ticket. 

Also, others on the mailing list indicated that this module was possible up for removal / replacement.  In light of that, I'm completely fine with other solutions to this issue.

**Comment by aaime** [comment]
+1 from me, I don't see any good reason not to merge this one.

**Comment by aaime** [comment]
Well besides having a Jira ticket for it, that we can refer from the commit message ha!

**Comment by jnh5y** [comment]
> Well besides having a Jira ticket for it, that we can refer from the commit message ha!

Fair enough:).  I added one here: https://osgeo-org.atlassian.net/browse/GEOT-6538.  What else can / should I do?  Thanks for the discussion on the mailing list!

**Pull request merged**
