### PR TITLE
Added a workaround for the reprojecting mosaic test failing

### PR DESCRIPTION
**Pull request by dvntucker**
This will skip the test for now when the expected CRS isn't found. Hopefully will add proper fix in the next release.

### CODE REVIEW

**Comment by aaime** [comment]
This will disable the heterogeneous test constantly, when it's passing the crs is 3857. The mosaic for that test is different than the other two.

**Comment by dvntucker** [comment]
Ok, added an "expectedCRS" parameter to the tests to compensate.

**Comment by jodygarnett** [comment]
Thanks, waiting for build to complete

**Comment by jodygarnett** [comment]
Backported to 16.x

**Pull request merged**
