### PR TITLE
[GEOT-5913] WFS and WMTS: Abstract can not be read

### PR DESCRIPTION
**Pull request by tbarsballe**
https://osgeo-org.atlassian.net/browse/GEOT-5913

Applied proper code formatting to https://github.com/geotools/geotools/pull/1920 on behalf of @matthias24

See that PR for more details.

### CODE REVIEW

**Comment by tbarsballe** [comment]
Formatting passes now, but I'm still seeing test failures:

```
Tests in error: 
  WMTSServiceTest.testDefaultStyleRequired:198 Â» IO Server returned HTTP respons...
```

I will note that everything passed fine for me locally, so I'll reset the CI builds and see if they fail the second time around.

**Comment by bradh** [comment]
I'm seeing this specific test fail intermittently too, with a browser query for https://sampleserver6.arcgisonline.com/arcgis/rest/services/Toronto/ImageServer/WMTS/1.0.0/WMTSCapabilities.xml?REQUEST=GetCapabilities&VERSION=1.0.0&SERVICE=WMTS returning 503.

Should that test be marked Online in any case?

**Comment by tbarsballe** [comment]
Yeah, if its requesting a specific remote server (especially one we don't control) then it should be marked as online and include an "assume" check for connectivity.

Looks like the tests passed the second time around.

**Comment by bradh** [comment]
Create https://osgeo-org.atlassian.net/browse/GEOT-6114 to track the test issue, which is orthogonal to this fix.

**Pull request merged**
