### PR TITLE
[GEOT-7666] Parsing empty Rotation style element throws a ClassCastException

### PR DESCRIPTION
**Pull request by Arxa**
[GEOT-7666](https://osgeo-org.atlassian.net/browse/GEOT-7666) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
A GeoTools PR must have  a GeoTools Jira ticket (which is normally linked to a GeoServer ticket, if there is one, as "blocker")

**Comment by aaime** [comment]
QA failed with a formatting error:

```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.20.0:check (default) on project gt-xsd-sld: The following files had format violations:
Error:      src/test/java/org/geotools/sld/bindings/SLDMockData.java
Error:          @@ -55,7 +55,7 @@
Error:           ····}
Error:           
Error:           ····static·Element·emptySize(Document·document,·Node·parent)·{
Error:          -·······return·element(SLD.SIZE,·document,·parent);
Error:          +········return·element(SLD.SIZE,·document,·parent);
Error:           ····}
Error:           
Error:           ····static·Element·opacity(Document·document,·Node·parent)·{
Error:  Run 'mvn spotless:apply' to fix these violations.
```

The formatted is very fast, and automatically run and applied during any normal maven build.
Also, one can run the full QA suite on a module with ``mvn clean install -Dqa``, best done within the module that has been modified (a full build with QA tools takes a long time, instead). More info about QA tools in [the guide](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (also linked from the checklist).

**Review by aaime — CHANGES_REQUESTED** [review]
Overall looks good. Pay attention to IDE auto-generated javadocs.

**Review by aaime — APPROVED** [review]

**Comment by aaime** [comment]
Good. I've checked the CLA box, as you're covered by GeoSolutions's company-wide CLA.

**Comment by aaime** [comment]
Merged. The automatic backport bot failed, possibly due to the merge commit (try to use "pull --rebase" in the future, we try to keep history as linear as possible). 
Anyways, can you backport the changes to 32.x and 31.x, and make PRs for those as well?

**Comment by Arxa** [comment]
@aaime Done
https://github.com/geotools/geotools/pull/4959 
https://github.com/geotools/geotools/pull/4958

**Pull request merged**
