### PR TITLE
[GEOT-7432] Inclusive comparison for DWithin filtering

### PR DESCRIPTION
**Pull request by bjornharrtell**
[GEOT-7432](https://osgeo-org.atlassian.net/browse/GEOT-7432) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

See https://osgeo-org.atlassian.net/jira/software/c/projects/GEOT/issues/GEOT-7432

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
I can't find a clear indication of whether distance should < or <=, but the in-memory implementation uses JTS, which in turn uses "<=". So the change seems legit. However, as usual, we need a test :rofl: 

Also, please don't remove the checklist, compile it instead.

**Comment by bjornharrtell** [comment]
Thanks @aaime I wasn't sure of the correctness here but since you agree I will continue working on this and add a test.

**Comment by aaime** [comment]
@bjornharrtell while you're dabbling on GeoTools code could you also add a test for this one?

**Comment by bjornharrtell** [comment]
@aaime I'll try!

**Comment by bjornharrtell** [comment]
I did try some weeks ago but was unable to get online tests to work and had some other development setup issues, unfortunately. I'm willing to make another attempt at some point in the future.

**Pull request closed without merging**
