### PR TITLE
[Backport 29.x] Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0

### PR DESCRIPTION
**Pull request by aaime**
Backport #4628
 **Authored by:** @dependabot[bot]

### CODE REVIEW

**Review by mprins — COMMENTED** [review]
there seems to be a build error in the docs module (that this PR does not affect:

```

init:
     [echo] Build directory is /home/runner/work/geotools/geotools/docs/target and project version is 29-SNAPSHOT

index:

sphinx:
     [echo] Running sphinx-build -D release=29-SNAPSHOT -q -W --keep-going -j auto -b html -d "/home/runner/work/geotools/geotools/docs/target/index/doctrees" . "/home/runner/work/geotools/geotools/docs/target/index/html"
     [exec] /home/runner/work/geotools/geotools/docs/common.py:77: SyntaxWarning: invalid escape sequence '\.'
     [exec]   branch =  re.sub('\..*', '', re.sub('-.*', '', version))
     [exec] 
     [exec] Sphinx version error:
     [exec] The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```

**Comment by aaime** [comment]
@jodygarnett do you have any clue as to why the docs are failing specifically on 29.x?
I don't see any reference to this "applehelp" contrib ...

**Comment by aaime** [comment]
Interestingly enough, it's building fine for me locally, I should have the latest sphinx too:

```
> sphinx-build --version
sphinx-build 7.2.6
```

**Comment by aaime** [comment]
Looks like stealing some of the python setup from main fixes the issue.

**Pull request merged**
