### PR TITLE
[GEOT-4636] Upgrade PostgreSQL JDBC library

### PR DESCRIPTION
**Pull request by aaime**
Tested locally the jdbc-postgis module, full pass, the epsg-postgresql one, for which I've built an online test, and the gt-imagemosaic-jdbc one, limited to the postgis and pgraster online tests.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Can this now be merged @aaime ?

**Comment by ianturton** [comment]
Looks good to me

**Comment by aaime** [comment]
Yep, no objection to merge, I'm just unable to follow up right now if something goes pear shaped after the merge

**Comment by ianturton** [comment]
The online build is currently having issues that I'll continue to look at if this doesn't solve them - it can't make them worse :-)

**Pull request merged**
