### PR TITLE
MemoryDataStore thread safety for internal collections

### PR DESCRIPTION
**Pull request by fgdrf**
If a Reader is iterating through the collection and a Writer (e.g. from Datastream) uses a Transaction to write SimpleFeatures the reader can get ConcurrentModificationException if not finished meanwhile. That can break rendering (BasicFeatureRenderer in uDig).

Implications : The reader might work on a slightly out-of-date DataSet, depending on the amount of data has been written in between.

### CODE REVIEW

**Comment by fgdrf** [comment]
Origin pull request was https://github.com/geotools/geotools/pull/960 but splitted into this one and for GEOT-5256 (removeSchema Support https://github.com/geotools/geotools/pull/1003)

**Comment by fgdrf** [comment]
@jodygarnett Is there a chance to get it into codebase before LocationTech Summit at EclipseCon next week? Would be great if we could upgrade uDig to latest 14-SNAPSHOT during codespring.

**Comment by fgdrf** [comment]
Finally squashed commits into a single one, now its ready for review.

**Comment by jodygarnett** [comment]
Built locally and merged

**Comment by jodygarnett** [comment]
Merged as https://github.com/geotools/geotools/commit/679e7108d8aa8778fcb5e2ab84d120ec9d8b253a

**Comment by fgdrf** [comment]
Thanks a lot! I guess you merged locally and not with github ui. In between I reset the branch and modified the commit-message ("Thread-safety for MemoryDataStore" is much better than the old one "testCase MemoryDataStore and ConcurrentModificationException's"). Now its on master and I'm fine with it!

**Pull request closed without merging**
