### PR TITLE
[GEOT-7300] Filter capabilities does not support PropertyIsNil filters

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOT-7300](https://osgeo-org.atlassian.net/browse/GEOT-7300) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR adds PropertyIsNil filters to the filter Capabilities and fixes a ClassCastException when PropertyIsNil filters are supported.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by sikeoka** [comment]
The downstream build had an unrelated Java heap space error twice.

**Comment by aaime** [comment]
Hum... I'm unsure about the side effects of this change. PropertyIsNil is not well supported across GeoTools.
I guess that using Capabilites/CapabilitiesFilterSplitter isolates the changes to the few parts of GeoTools actually using those classes (the bulk is using FilterCapabilities/PostPreProcessFilterSplittingVisitor instead, and throws Exceptions when PropertyIsNil is provided to the visitors).

That said, for example, ElasticSearch is likely going to be affected, as it uses CapabilitiesFilterSplitter but FilterToElastic throws an exception is PropertyIsNil is provided. The other bits that might be affected are wfs-ng (maybe in a good way!) and jdbcconfig (also in a good way, although I don't see PropertyIsNil being used, Predicates works with PropertyIsNull instead).

**Comment by sikeoka** [comment]
There shouldn't be any side effects unless a module is adding PropertyIsNil to its filter capabilities even though it isn't supposed to be supporting it and even then, there won't be any side effects except when a PropertyIsNil filter is passed to the module.  This change is intended for jdbcconfig since it does implement support for PropertyIsNil.  I noticed that it had a unit test that said it was testing PropertyIsNil but was actually testing PropertyIsNull and changing the test to PropertyIsNil ran into this problem.

**Comment by aaime** [comment]
@sikeoka makes sense. Wondering what's putting PropertyIsNil in the path to JDBCConfig though? 
As indicated above, Predicates (used to build catalog filters) seems to be using PropertyIsNull instead.

**Comment by sikeoka** [comment]
It looks like PropertyIsNil isn't actually used anywhere at all outside of unit tests.  This PR shouldn't break anything and would be necessary if you ever decided to start using PropertyIsNil more but I could just remove the PropertyIsNil test from jdbcconfig for now if you prefer to do that.

**Pull request closed without merging**
