### PR TITLE
Equation of time in minutes of time

### PR DESCRIPTION
**Pull request by jarmalo**
Github: "Choose two branches to see what’s changed or to start a new pull request." ???

Hello, on my serach for a function to calculate the eqt i have found your repository, and a eqt function. But i understand it what you mean. (I have work in JavaScript with eqt, Java is new to me).

https://github.com/geotools/geotools/blob/master/modules/library/referencing/src/main/java/org/geotools/nature/SunRelativePosition.java

You wrote:
> 274 * @param t number of Julian centuries since J2000.
> 275 * @return Equation of time in minutes of time.

I like the row 275, but i understand the row 274. "number of Julian centuries"??? "centuries"??? I think the function needed a day (in a sunyear)? (eqt is still days dependent).

My question is simple: How can I use the function with a timestamp (UTC)? If I have the eqt for a day in UTC (longitude 0 °), I can continue to calculate in my script.     
What does "t" have to be exactly, and how can I arrange this with a timestamp (UTC)?

Sorry for my request, but they seem to have exactly what I'm looking for.    
It would be nice if you could help me with that.

### CODE REVIEW

**Comment by bradh** [comment]
This doesn't appear to be a valid PR. If you still have a question, perhaps the geotools-users mailing list would be useful.

**Comment by jarmalo** [comment]
Sorry, i see, you have no Issue tab. *confused*

The Email "user list" send back:

> The GeoTools user email list requires that you be subscribed prior to submitting an email.
> 
> While this message is automatically generated; real humans are available if you have any question getting started: %(listowner)

???

**Comment by jarmalo** [comment]
My Email: 
I have tested it, but ...
 
```
return etime;
 
long timestamp = 1549798471; // actuall Unix timestamp from yet in seconds
System.out.println(equationOfTime(timestamp)); // 9.90335105619834E22
```
 
The eqt from today is -14.23 minutes.

What does "t" have to be exactly, and how can I arrange this with a timestamp (UTC)?

**Comment by bradh** [comment]
https://sourceforge.net/projects/geotools/lists/geotools-gt2-users

**Pull request closed without merging**
