### PR TITLE
Add SQL error message to insertion error message

### PR DESCRIPTION
**Pull request by mac9416**
I got `Error inserting features` when I just needed to expand a column width. Adding the underlying SQLException message would have helped me avoid searching the source for the error message, attaching a debugger (a little cumbersome in my environment), and re-running the code to reproduce the issue.

I see there's precedent [here](https://github.com/geotools/geotools/blob/376585cd7517451c9a53846c6cc3c392e8e1fdb3/modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java#L2171), in the same file, for appending the underlying message.

```java
} catch (SQLException e) {
    throw new RuntimeException("Unable to obtain connection: " + e.getMessage(), e);
}
```

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer.

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

_I'm not sure if this is a core or extension module?_

- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by aaime** [comment]
In the case of GeoServer, the exceptions pop up to the service level and their message is reported to the client. Are we sure it may not contain sensitive information? Otherwise logging the message would be a more secure way to make the information available.

**Comment by mac9416** [comment]
That's a fair concern. In the case of my application, I'm just going to get the exception's `cause` and log its message. That's probably a viable workaround for most folks.

I can modify this PR to use logging, if you think that would be a potential good solution.

**Comment by aaime** [comment]
Yes please. :-D

**Comment by aaime** [comment]
@mac9416 can you update the PR? Otherwise I'm afraid I'll have to close it for inactivity (we're beyond fully booked, it's unlikely that we'll find time to update it in our spare time).

**Comment by mac9416** [comment]
@aaime thanks for checking back in! I'm going to close it for now, since I've had to move on to unrelated work. If I'm back in the same area of code, I'll re-open the PR.

**Pull request closed without merging**
