### PR TITLE
GEOT-6403 :: graphic-resize NullPointerException

### PR DESCRIPTION
**Pull request by tixvieira**
Made this new PR for this bug.

Closed the old one: #2632

### CODE REVIEW

**Comment by aaime** [comment]
Better, but there are still two problems:

- The PRs should always start targeting the master branch (will roll out a checklist like we did no GeoServer so that these rules are evident on PR opening)
- I have removed your changes and run the new test... it passed. So, it's not really testing the issue at hand, please check what's going on and write a test that would cause the NPE reported in the ticket when run without the fixes.

**Comment by tixvieira** [comment]
With the old code it crashes on the test:
`[INFO] Running org.geotools.renderer.label.LabelPainterTest
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! - in org.geotools.renderer.label.LabelPainterTest
[ERROR] testResizeGraphicWithMark2DGraphicResizeStrech(org.geotools.renderer.label.LabelPainterTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError
        at org.geotools.renderer.label.LabelPainterTest.testResizeGraphicWithMark2DGraphicResizeStrech(LabelPainterTest.java:156)`

With the new code it passes!

Do you want us to do the PR in the master?

**Comment by aaime** [comment]
@tixvieira I removed your change and the test passes just fine locally. Here is what I've done:
1) Checked out the PR
2) Removed the LabelPainter changes, keeping the test
3) Run the build in the renderer module, no failure

See here (with proof of fix removal):

```
aaime@colossus ~/devel/git-gt/modules/library/render ((9e946e1d29...)) mvn clean install -nsu
....
[INFO] --- maven-install-plugin:2.4:install (default-install) @ gt-render ---
[INFO] Installing /home/aaime/devel/git-gt/modules/library/render/target/gt-render-22-SNAPSHOT.jar to /home/aaime/.m2/repository/org/geotools/gt-render/22-SNAPSHOT/gt-render-22-SNAPSHOT.jar
[INFO] Installing /home/aaime/devel/git-gt/modules/library/render/pom.xml to /home/aaime/.m2/repository/org/geotools/gt-render/22-SNAPSHOT/gt-render-22-SNAPSHOT.pom
[INFO] Installing /home/aaime/devel/git-gt/modules/library/render/target/gt-render-22-SNAPSHOT-tests.jar to /home/aaime/.m2/repository/org/geotools/gt-render/22-SNAPSHOT/gt-render-22-SNAPSHOT-tests.jar
[INFO] Installing /home/aaime/devel/git-gt/modules/library/render/target/gt-render-22-SNAPSHOT-sources.jar to /home/aaime/.m2/repository/org/geotools/gt-render/22-SNAPSHOT/gt-render-22-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2019-12-09T12:32:02+01:00
[INFO] ------------------------------------------------------------------------

aaime@colossus ~/devel/git-gt/modules/library/render ((9e946e1d29...)) $ git diff
diff --git a/modules/library/render/src/main/java/org/geotools/renderer/label/LabelPainter.java b/modules/library/render/src/main/java/org/geotools/renderer/label/LabelPainter.java
index 05dd1ce966..ca25f1e39d 100644
--- a/modules/library/render/src/main/java/org/geotools/renderer/label/LabelPainter.java
+++ b/modules/library/render/src/main/java/org/geotools/renderer/label/LabelPainter.java
@@ -427,11 +427,6 @@ public class LabelPainter {
             return null;
         }
 
-        double roundedWidth = Math.round(width);
-        double roundedHeight = Math.round(height);
-        width = roundedWidth != 0 ? roundedWidth : Math.ceil(width);
-        height = roundedHeight != 0 ? roundedHeight : Math.ceil(height);
-
         if (graphic instanceof MarkStyle2D) {
             MarkStyle2D mark = (MarkStyle2D) graphic;
```

Are you saying the issue is platform dependent maybe? I've built locally, on Linux, with both Java 8 and Java 11, results are the same, that new test does not fail.

And yes, the PR must be on master first (we barely have time to do reviews, sorry).

**Comment by aaime** [comment]
@tixvieira can you fix the PR so that the test actually fails if the code fix is removed? See my comment above.

**Comment by aaime** [comment]
Gave it another go... this time managed to reproduce, not sure what happened at the first round.
Anyways, the null return is actually legit in case of negative margin, so added more tests and made sure the painter does not NPE in that case. And targeted master branch first.
Closing this PR, it's superceded by https://github.com/geotools/geotools/pull/2786
@tixvieira want to have a look before I merge?

**Comment by tixvieira** [comment]
Hi @aaime ,

Thanks for the replies.
In the past months i was not been able to do this fix, but i like at the code, and it seems fine.
You guys understand the whole logic before it gets the the "resizeGraphic" method, so the main problem it's probably fixed you that approach.
Our team talked about it, that the problem is solved with our code, but the main problem seems to be before enter the method. But we are not so familiar with geotools code :)

Thank you,
Tiago Vieira

**Pull request closed without merging**
