### PR TITLE
confirm YSLD and CQL literal color handling [GEOT-5704]

### PR DESCRIPTION
**Pull request by jodygarnett**
https://osgeo-org.atlassian.net/browse/GEOT-5704

### CODE REVIEW

**Comment by aaime** [comment]
I cannot comment on the substance of the changes, that's for the YSLD moduler maintainer to do, but the Travis failure is legit, the code was not built by maven before doing the PR and has a formatting issue:

``
[ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-cql: Found 1 non-complying files, failing build -> [Help 1]
``

**Comment by tbarsballe** [comment]
Please rebuild to apply formatting rules and fix the merge conflicts.

**Comment by aaime** [comment]
@jodygarnett what should we do about this one?

**Comment by tbarsballe** [comment]
Still failing on the same formatting issue as before:
```
[ERROR] Found 1 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn fmt:format"
[ERROR] Non complying file: /home/travis/build/geotools/geotools/modules/library/cql/src/test/java/org/geotools/filter/text/cql2/FilterToCQLTest.java
[INFO] STARTED build of project org.geotools.xsd:gt-xsd-gml2
[INFO] FAILURE build of project org.geotools:gt-cql
```

**Comment by jodygarnett** [comment]
Committed the changed formatting, checking GEOT-5704 this PR confirms the issue cannot be reproduced...

**Pull request merged**
