### PR TITLE
MacOS CI build from GitHub?

### PR DESCRIPTION
**Pull request by aaime**
Interesting enough, GitHub provides a CI build for th OSX environment too... is it something we're interested into? Here is a PR to see how that goes.

### CODE REVIEW

**Comment by aaime** [comment]
@tbarsballe @jodygarnett interesting failure on OSX:

```
[INFO] Running org.geotools.gce.imagemosaic.ImageMosaicReaderTest
2019-12-28 08:48:56.531 java[1506:29824] Persistent UI failed to open file file://localhost/Users/runner/Library/Saved%20Application%20State/net.java.openjdk.cmd.savedState/window_1.data: No such file or directory (2)
[/Users/runner/runners/2.163.1/work/geotools/geotools/modules/plugin/imagemosaic/target/test-classes/org/geotools/gce/imagemosaic/test-data/rbgFileView/global_mosaic_0.prj, /Users/runner/runners/2.163.1/work/geotools/geotools/modules/plugin/imagemosaic/target/test-classes/org/geotools/gce/imagemosaic/test-data/rbgFileView/global_mosaic_0.pgw]
[ERROR] Tests run: 91, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 18.851 s <<< FAILURE! - in org.geotools.gce.imagemosaic.ImageMosaicReaderTest
[ERROR] testOverviewSupportFiles(org.geotools.gce.imagemosaic.ImageMosaicReaderTest)  Time elapsed: 0.054 s  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<2>
	at org.geotools.gce.imagemosaic.ImageMosaicReaderTest.testOverviewSupportFiles(ImageMosaicReaderTest.java:4989)

[ERROR] testGIFSupportFiles(org.geotools.gce.imagemosaic.ImageMosaicReaderTest)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: expected:<12> but was:<6>
	at org.geotools.gce.imagemosaic.ImageMosaicReaderTest.testGIFSupportFiles(ImageMosaicReaderTest.java:4945)
```

The funny thing is, those tests already have OSX specific behaviors, and that's why they are failing:
*  First failure: https://github.com/geotools/geotools/blob/master/modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java#L4989
* Second failure: https://github.com/geotools/geotools/blob/master/modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java#L4945

Does that ring any bell to you?

**Comment by tbarsballe** [comment]
A CI Build on github would be a nice alternative to standing up our own Jenkins env.

As for the test failure, that does look kind if familiar. I do recall someone else running into tests where a Mac-specific workaround was no longer necessary, although I don't know the specifics, and  I'm pretty sure this was in a fork or in stratus.

Last time I ran the tests locally on Mac + Java 8 (sometime in October) I'm pretty sure they passed.

Doing my own testing:
Running on Java 11 on Mac (latest OS version) today, I see the same failures as you posted here.
Running on Java 8 on Mac, I also see the same failures.

 I'm pretty sure these failures have something to do with the specific OS version (Catalina I believe), although I have no way of testing that. Probably makes the most sense to support the latest update, so I think the tests can be changed. If someone has a system they haven't updated to Mac OS Catalina yet, it would probably be worthwhile to test there first though.

**Comment by aaime** [comment]
@tbarsballe we should probably ask on the devel list and see if there is anyone that has the right OS version, but I'm not sure how to word it.

**Comment by tbarsballe** [comment]
I'll send a message to devel asking about this

**Comment by tbarsballe** [comment]
Based on email discussion, the workaround in ImageMosaicTest is no longer necessary - everyone who tested it reported test failures (with the "normal" test result), and had results from a variety of Mac OS versions (10.13 and 10.15), and both Java 8 and Java 11.

I've removed the workaround - lets see if the Mac OS CI passes this time around

**Comment by tbarsballe** [comment]
Now failing on gt-render:
```
[ERROR] Failures: 
[ERROR]   LabelDisplacementModeTest.testMultiLineLabelDisplacementY:469 Images are visibly different, found 1911 different pixels, against a threshold of 1100
You can add -Dorg.geotools.image.test.interactive=true to show a dialog comparing them (requires GUI support)
[INFO] 
[ERROR] Tests run: 947, Failures: 1, Errors: 0, Skipped: 6
```

That test passes fine for me, but I know it can be a bit finicky depending on the graphics environment.

**Comment by aaime** [comment]
That test already had extra tolerance for JAVA11, using the same for OSX (finger crossed).

**Comment by aaime** [comment]
Nice, now passing on the OSX integration build, merging

**Pull request merged**
