### PR TITLE
GEOT-5773 avoid NPE in GridCoverageRenderer when colormodel is null

### PR DESCRIPTION
**Pull request by jdries**
@dromagnoli 
This can occur with non-byte images. (Remote sensing images commonly use shorts as data type, both in netcdf and geotiff files.)

### CODE REVIEW

**Comment by dromagnoli** [comment]
Hi @jdries 
The PR looks good to me. Thanks for the fix and test
I think that the current travis failure is due to https://osgeo-org.atlassian.net/browse/GEOT-5784
so you have my +1 since it's an unrelated issue, hopefully.

**Comment by dvntucker** [comment]
Looks like the build failure was unrelated.

**Comment by simboss** [comment]
Does this one need a backport? @dromagnoli ?

**Comment by dromagnoli** [comment]
@dvntucker can you backport that and update the JIRA accordingly?

**Comment by jdries** [comment]
@dvntucker Is there still a chance of backporting this bugfix to the 16.x branch?

**Comment by aaime** [comment]
A note, the 16.x branch is "dead", there are no more planned releases on it (there is one in progress right now, but it's already built, just need announcements)

**Comment by jdries** [comment]
Is a backport into 17.x an option then? (I'm upgrading my setup to that version now.)

**Pull request merged**
