### PR TITLE
[GEOT-7670] Fix synchronization between DataStoreFinder and DataAccessFinder

### PR DESCRIPTION
**Pull request by elahrvivaz**
[GEOT-7670](https://osgeo-org.atlassian.net/browse/GEOT-7670) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This changes DataStoreFinder and DataAccessFinder to synchronize on a common object (DataAccessFinder.class) to avoid potential thread deadlocks.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by elahrvivaz** [comment]
I didn't add a unit test for this as the interaction required to trigger it is fairly complex (see the ticket for a full description), and it didn't seem feasible to reliably recreate it in a unit test.

**Comment by jodygarnett** [comment]
Make a comment when you have the downstream PR ready and indicate that both need to be merged at the same time.

**Comment by elahrvivaz** [comment]
Downstream PR in geoserver that needs to be merged at the same time: https://github.com/geoserver/geoserver/pull/7983

**Comment by jodygarnett** [comment]
@elahrvivaz just to be clear is this change covered by testing in the downstream pull-request? How can I test if this change does something :) 

We are pretty strict about requiring a test case and could make an exception if the change is covered somehow automatically.

context: What we seek to avoid is the previous situations where the project team was overwhelmed by changes that required manual testing, and then manual testing again each time we made a release to see if a problem was re-introduced. The project has been far more stable and sustainable since we ask for test coverage.

**Comment by elahrvivaz** [comment]
@jodygarnett no, as mentioned above I didn't add a unit test for this as the interaction required to trigger it is fairly complex (details in the ticket), and it didn't seem feasible to reliably recreate it in a unit test. I could probably create a test case by creating a mock data store factory, but since both DataStore/AccessFinder keep static global state I'd need to run that in a separate jvm from other tests (is there a good place to do that?). I was hoping a code review + all the other tests that use DataStore/AccessFinder would be good enough. The only logic change was switching from `public static synchronized` signatures to `synchronized (DataAccessFinder.class)` blocks.

**Comment by jodygarnett** [comment]
Thinking recently @aaime added some methods register and unregistered for tests cases. It was done to avoid a META_INF/services entry slowing down all the tests.

Could that help with writing a test case? Something like:

```
try {
  DataAccessFinder.registerFactrory(factory);
  // test via data access finder and data store finder?
} finally {
    DataAccessFinder.deregisterFactrory(factory);
}
```

Something?

**Comment by jodygarnett** [comment]
@aaime any suggestions on making this testable? Or should we accept as is ...

The change does make sense to me.

**Comment by elahrvivaz** [comment]
I'll try to come up with a test!

**Comment by elahrvivaz** [comment]
FYI, the included test will probably cause issues if tests are ever run in parallel, due to the global variables in DataStore/AccessFinder... I couldn't find a way around that. But it does consistently cause a deadlock on main, while passing on this branch. I also couldn't find a way to break the deadlock and just have a failed test (on main) - it seems from some quick googling that there is no way to kill/stop/interrupt a thread waiting on a native synchronized block in java.

**Comment by jodygarnett** [comment]
Nice work, on the test.

aside: We have similar scary tests resetting the entire CRS system (to test between forceXY order or not). Even that has resulted in little build instability over time. This kind of thing can be very frustrating when missing `finally` but has otherwise been okay.

**Review by jodygarnett — CHANGES_REQUESTED** [review]

**Comment by aaime** [comment]
@jodygarnett are you satisfied with the changes?

**Comment by aaime** [comment]
Well... looks good to me at least. Merging.

**Comment by sikeoka** [comment]
This PR may be causing QA failures in GeoServer?
```
20:48:21,717 [INFO] -------------------------------------------------------------
Warning: 717 [WARNING] COMPILATION WARNING : 
20:48:21,717 [INFO] -------------------------------------------------------------
Warning: 717 [WARNING] /home/runner/work/geoserver/geoserver/src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java:[177,24] registerFactrory(org.geotools.api.data.DataStoreFactorySpi) in org.geotools.api.data.DataStoreFinder has been deprecated
Warning: 717 [WARNING] /home/runner/work/geoserver/geoserver/src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java:[182,24] deregisterFactrory(org.geotools.api.data.DataStoreFactorySpi) in org.geotools.api.data.DataStoreFinder has been deprecated
20:48:21,717 [INFO] 2 warnings 
20:48:21,717 [INFO] -------------------------------------------------------------
20:48:21,717 [INFO] -------------------------------------------------------------
Error: 1,717 [ERROR] COMPILATION ERROR : 
20:48:21,717 [INFO] -------------------------------------------------------------
Error: 1,717 [ERROR] /home/runner/work/geoserver/geoserver/src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java: warnings found and -Werror specified
```

**Comment by aaime** [comment]
Yes, it does, I've followed up with a fix in GeoServer (linked above)

**Pull request merged**
