### PR TITLE
 ComplexDataTypeBinding encode override - GEOT-4934

### PR DESCRIPTION
**Pull request by afabiani**
https://jira.codehaus.org/browse/GEOT-4934

From Jira: The ComplexDataTypeBinding ignores completely the data attribute of hte Type.
Since the attribute data is not recognized as a property of the binding type, we need to envisage the override of the "encode" method.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Any update on this @afabiani ? It is getting close to feature freeze and I would not like to see (what appears to be a lot of work) suffer bit-rot.

**Comment by jodygarnett** [comment]
@afabiani now is the time?

**Comment by aaime** [comment]
Closing, it has been superseded by a already merged pull request

**Comment by bradh** [comment]
@afabiani Can you remember if you still need this branch for anything?

**Pull request closed without merging**
