### PR TITLE
[GEOT-7641] Support the "Sweep" parameter in the geostationary projections

### PR DESCRIPTION
**Pull request by ajhoffma**
A fix to the geostationary projection in geotools to allow setting the sweep
axis as appropriate for GOES. The WKT parser only allows parameters
that can be parsed as doubles so I didn't add the sweep_axis as a parameter
with values x,y (which doesn't seem to be done anywhere anyway). We could fix
that, but it's a larger change. Instead, I added a sweep parameter that's
either a 0 (x) or a 1 (y).

All the math is copied over from PROJ of course, as it was before, but now it's
copied from a newer version of PROJ (5.2 instead of 4.9).

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Review by mprins — CHANGES_REQUESTED** [review]
please make sure your code is valid java and at least compiles

**Comment by mprins** [comment]
You only need to follow the steps outlined in https://docs.geotools.org/latest/developer/procedures/contribute.html

**Comment by ajhoffma** [comment]
> please make sure your code is valid java and at least compiles

Done, commits were in a weird state for some reason.

**Comment by aaime** [comment]
Looks like it wasn't build by maven before issuing the PR (among other things, it auto-reformats to the required style):

```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.20.0:check (default) on project gt-referencing: The following files had format violations:
Error:      src/main/java/org/geotools/referencing/operation/projection/GeostationarySatellite.java
Error:          @@ -21,8 +21,6 @@
Error:           
Error:           import·java.awt.geom.Point2D;
Error:           import·java.util.Collection;
Error:          -import·java.util.Objects;
Error:          -
Error:           import·org.geotools.api.geometry.Bounds;
Error:           import·org.geotools.api.parameter.GeneralParameterDescriptor;
Error:           import·org.geotools.api.parameter.ParameterDescriptor;
Error:          @@ -114,6 +112,7 @@
Error:           ····/**
Error:           ·····*·Transforms·these·coordinates·to·the·initialization·vector·for·calculating·the·satellite·view
Error:           ·····*·vector.
Error:          +·····*
Error:           ·····*·@param·x·The·X·coordinate·on·Earth.
Error:           ·····*·@param·y·The·Y·coordinate·on·Earth.
Error:           ·····*·@param·yz·A·point·whose·location·is·set·to·the·Y·and·Z·initializers·of·the·view·vector.
Error:  Run 'mvn spotless:apply' to fix these violations.
Error:  -> [Help 1]
```

**Review by aaime — CHANGES_REQUESTED** [review]
Changes look good, please make sure the QA build gives you a green (it's possible to run the QA machinery on the local computer, the PR checklist has a link to docs)

**Pull request merged**
