### PR TITLE
[GEOT-7440] Update maven plugin versions

### PR DESCRIPTION
**Pull request by bradh**
[GEOT-7440](https://osgeo-org.atlassian.net/browse/GEOT-7440) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This is a general update to newer versions of maven dependencies. 

Notably not included is an upgrade of spotless + formatter. That changes significant number of files (albeit mostly pretty small changes), and will be handled under https://osgeo-org.atlassian.net/browse/GEOT-7439

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [N/A] New unit tests have been added covering the changes.
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Review by mprins — DISMISSED** [review]
In the Maven vocabulary plugins are not dependencies, as such I think the title of this PR should be changed to use "Maven plugins" instead

**Comment by bradh** [comment]
@mprins Agree that is better. Have updated the JIRA ticket, PR title, and commit message.

**Review by mprins — APPROVED** [review]

**Comment by aaime** [comment]
Uh oh, I'm guessing this is the cause for the new failures on the build server? 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:aggregate (default-cli) on project modules: An error has occurred in Javadoc report generation:
[ERROR] Exit code: 1
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://javaee.github.io/javaee-spec/javadocs/ are in the unnamed module.
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/AcknowledgementType.java>:107: warning - Tag @see: reference not found: #setTimeStamp(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/BriefRecordType.java>:92: warning - Tag @see: reference not found: #setType(String)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:114: warning - Tag @see: reference not found: net.opengis.cat.csw20.Csw20Package#getGetRecordsType_AbstractQuery()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:156: warning - Tag @see: reference not found: #isSetMaxRecords()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:157: warning - Tag @see: reference not found: #unsetMaxRecords()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:158: warning - Tag @see: reference not found: #setMaxRecords(BigInteger)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/QueryType.java>:85: warning - Tag @see: reference not found: #setElementName(QName)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/QueryType.java>:127: warning - Tag @see: reference not found: #setSortBy(SortBy)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/RecordType.java>:38: warning - Tag @link: reference not found: net.opengis.cat.csw._2._0.EmptyType
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/RecordType.java>:46: warning - Tag @see: reference not found: net.opengis.cat.csw._2._0._0Package#getRecordType_AnyText()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/RequestStatusType.java>:51: warning - Tag @see: reference not found: #setTimestamp(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/SearchResultsType.java>:25: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/SearchResultsType.java>:179: warning - Tag @see: reference not found: #setExpires(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/AcknowledgementType.java>:107: warning - Tag @see: reference not found: #setTimeStamp(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/impl/BriefRecordTypeImpl.java>:74: warning - Tag @see: reference not found: #getSpatial()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/BriefRecordType.java>:92: warning - Tag @see: reference not found: #setType(String)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/impl/DCMIRecordTypeImpl.java>:40: warning - invalid usage of tag {@link #getDCElement()()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/impl/DCMIRecordTypeImpl.java>:40: warning - invalid usage of tag {@link #getDCElement()()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:156: warning - Tag @see: reference not found: #isSetMaxRecords()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:157: warning - Tag @see: reference not found: #unsetMaxRecords()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:158: warning - Tag @see: reference not found: #setMaxRecords(BigInteger)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/GetRecordsType.java>:114: warning - Tag @see: reference not found: net.opengis.cat.csw20.Csw20Package#getGetRecordsType_AbstractQuery()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/QueryType.java>:85: warning - Tag @see: reference not found: #setElementName(QName)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/QueryType.java>:127: warning - Tag @see: reference not found: #setSortBy(SortBy)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/impl/RecordTypeImpl.java>:49: warning - Tag @see: reference not found: #getSpatial()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/RecordType.java>:46: warning - Tag @see: reference not found: net.opengis.cat.csw._2._0._0Package#getRecordType_AnyText()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/RequestStatusType.java>:51: warning - Tag @see: reference not found: #setTimestamp(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/SearchResultsType.java>:179: warning - Tag @see: reference not found: #setExpires(XMLGregorianCalendar)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/AbstractAdhocQueryExpressionType.java>:112: warning - Tag @see: reference not found: #setAliases(List)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/AbstractAdhocQueryExpressionType.java>:128: warning - Tag @see: reference not found: #setTypeNames(List)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/ComparisonOperatorsType.java>:26: warning - Tag @link: reference not found: net.opengis.fes20.ComparisonOperatorsType#getComparisonOperator<em>Comparison Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/ComparisonOperatorType.java>:38: warning - Tag @see: reference not found: #setName(Object)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:138: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:138: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:184: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:184: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:4179: warning - Tag @link: reference not found: net.opengis.fes20.ComparisonOperatorsType#getComparisonOperator<em>Comparison Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:5920: warning - Tag @link: reference not found: net.opengis.fes20.SpatialOperatorsType#getSpatialOperator<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:6057: warning - Tag @link: reference not found: net.opengis.fes20.TemporalOperatorsType#getTemporalOperator<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:4179: warning - Tag @link: reference not found: net.opengis.fes20.ComparisonOperatorsType#getComparisonOperator<em>Comparison Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:4183: warning - Tag @see: reference not found: net.opengis.fes20.ComparisonOperatorsType#getComparisonOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:5920: warning - Tag @link: reference not found: net.opengis.fes20.SpatialOperatorsType#getSpatialOperator<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:5924: warning - Tag @see: reference not found: net.opengis.fes20.SpatialOperatorsType#getSpatialOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:6057: warning - Tag @link: reference not found: net.opengis.fes20.TemporalOperatorsType#getTemporalOperator<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:6061: warning - Tag @see: reference not found: net.opengis.fes20.TemporalOperatorsType#getTemporalOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/SpatialOperatorsType.java>:23: warning - Tag @link: reference not found: net.opengis.fes20.SpatialOperatorsType#getSpatialOperator<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/SpatialOperatorType.java>:66: warning - Tag @see: reference not found: #setName(Object)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/TemporalOperatorsType.java>:23: warning - Tag @link: reference not found: net.opengis.fes20.TemporalOperatorsType#getTemporalOperator<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/AbstractAdhocQueryExpressionType.java>:112: warning - Tag @see: reference not found: #setAliases(List)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/AbstractAdhocQueryExpressionType.java>:128: warning - Tag @see: reference not found: #setTypeNames(List)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/ComparisonOperatorsTypeImpl.java>:37: warning - Tag @link: reference not found: net.opengis.fes20.impl.ComparisonOperatorsTypeImpl#getComparisonOperator<em>Comparison Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/ComparisonOperatorType.java>:38: warning - Tag @see: reference not found: #setName(Object)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:4183: warning - Tag @see: reference not found: net.opengis.fes20.ComparisonOperatorsType#getComparisonOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:5924: warning - Tag @see: reference not found: net.opengis.fes20.SpatialOperatorsType#getSpatialOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/Fes20Package.java>:6061: warning - Tag @see: reference not found: net.opengis.fes20.TemporalOperatorsType#getTemporalOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/library/api/src/main/java/org/geotools/api/filter/capability/ScalarCapabilities.java>:53: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/library/api/src/main/java/org/geotools/api/filter/capability/ScalarCapabilities.java>:77: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/library/api/src/main/java/org/geotools/api/filter/capability/SpatialCapabilities.java>:52: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/SpatialOperatorsTypeImpl.java>:35: warning - Tag @link: reference not found: net.opengis.fes20.impl.SpatialOperatorsTypeImpl#getSpatialOperator<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/SpatialOperatorsTypeImpl.java>:43: warning - Tag @link: reference not found: #getSpatialOperator()<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/SpatialOperatorsTypeImpl.java>:43: warning - Tag @link: reference not found: #getSpatialOperator()<em>Spatial Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/SpatialOperatorsTypeImpl.java>:46: warning - Tag @see: reference not found: #getSpatialOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/SpatialOperatorType.java>:66: warning - Tag @see: reference not found: #setName(Object)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/TemporalOperatorsTypeImpl.java>:35: warning - Tag @link: reference not found: net.opengis.fes20.impl.TemporalOperatorsTypeImpl#getTemporalOperator<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/TemporalOperatorsTypeImpl.java>:43: warning - Tag @link: reference not found: #getTemporalOperator()<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/TemporalOperatorsTypeImpl.java>:43: warning - Tag @link: reference not found: #getTemporalOperator()<em>Temporal Operator</em>
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.fes/src/net/opengis/fes20/impl/TemporalOperatorsTypeImpl.java>:46: warning - Tag @see: reference not found: #getTemporalOperator()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:48: warning - Tag @see: reference not found: #setLimits(GridLimitsType)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:49: warning - Tag @see: reference not found: net.opengis.gml.Gml4wcsPackage#getGridType_Limits()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:73: warning - Tag @see: reference not found: #setAxisName(String)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:48: warning - Tag @see: reference not found: #setLimits(GridLimitsType)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:49: warning - Tag @see: reference not found: net.opengis.gml.Gml4wcsPackage#getGridType_Limits()
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wcs/src/net/opengis/gml/GridType.java>:73: warning - Tag @see: reference not found: #setAxisName(String)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/AffinePlacementType.java>:30: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:96: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:97: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:99: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:100: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:102: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:102: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:103: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:103: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:105: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:105: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:107: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:107: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:108: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:108: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:110: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:110: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:166: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:166: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:212: warning - invalid usage of tag <
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.wmts/src/net/opengis/gml311/Gml311Package.java>:212: warning - invalid usage of tag >
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows10/OperationsMetadataType.java>:91: warning - Tag @see: reference not found: #setExtendedCapabilities(EObject)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows10/OperationsMetadataType.java>:91: warning - Tag @see: reference not found: #setExtendedCapabilities(EObject)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows11/OperationsMetadataType.java>:89: warning - Tag @see: reference not found: #setExtendedCapabilities(EObject)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows11/OperationsMetadataType.java>:89: warning - Tag @see: reference not found: #setExtendedCapabilities(EObject)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows20/AcceptFormatsType.java>:44: warning - Tag @see: reference not found: #setOutputFormat(String)
[ERROR] <https://build.geoserver.org/job/geotools-main/ws/modules/ogc/net.opengis.ows/src/net/opengis/ows20/AcceptLanguagesType.java>:39: warning - Tag @see: reference not found: #setLanguage(String)
[ERROR] Command line was: /var/lib/jenkins/tools/hudson.model.JDK/OpenJDK_11.0.4/jdk-11.0.4+11/bin/javadoc -J-Xmx1536m -Xdoclint:none @options @packages
```

**Comment by bradh** [comment]
I can partly reproduce (warnings, not errors) with `mvn javadoc:javadoc`. Will fix or revert.

**Comment by bradh** [comment]
https://github.com/geotools/geotools/pull/4486 to revert. Fixes to follow later.

**Pull request merged**
