### PR TITLE
[GEOT-7001] XmlComplexFeatureParser gives wrong name for ComplexAttribute

### PR DESCRIPTION
**Pull request by roarbra**
[GEOT-7001](https://osgeo-org.atlassian.net/browse/GEOT-7001) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

When accessing a WFS with a complex structure a single feature shouldn't have properties with names other than those reported by a call to getSchema().

That is the basic of my added test in KartverketStedsnavnDataStoreOnlineTest.

Unfortunately a lot of tests were based on the wrong assumption about how to name complex attributes.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by roarbra** [comment]
I'm not that familiar with the GeoServer codebase, but it seems to ignore complex attributes regardless of my change.
I will have a look at the documentation, but I don't see how it fits in with my code change. However I do see that it violates quite a lot of the original test's, so I can see your concern.

**Comment by aaime** [comment]
@roarbra using GeoServer was just a quick way to test the parsing and re-encoding, all the actual machinery is in GeoTools, but to try that out, one has to write some code to wire the bits together.

**Comment by roarbra** [comment]
@aaime I've looked at a solution to write out the features using org.geotools.xsd.Encoder, but without any luck. It doesn't seem to like complex features either.

I've added an example to docs, and wonder if that could be useful to show how my fix makes the code more readable.

**Comment by taba90** [comment]
@aaime The code modifications seems legit to me and are providing a fix for the parser. 
For what is seems to me before this fix, although the GML object property model was respected in the Feature structure, the parser was creating Feature attributes with the wrong name (equals to the Type name instead of using the descriptor name as should be done).

**Comment by aaime** [comment]
@roarbra merged, feel free to backport as you see fit.

**Pull request merged**
