### PR TITLE
[GEOT-5524] Incorrect detection of GRIB files with WMO header (master)

### PR DESCRIPTION
**Pull request by bencaradocdavies**
https://osgeo-org.atlassian.net/browse/GEOT-5524

This pull request targets master.

### CODE REVIEW

**Comment by dromagnoli** [comment]
+1 on merging that.

**Comment by bencaradocdavies** [comment]
Thanks @dromagnoli for the quick review.

**Comment by simboss** [comment]
Thx for this work Ben!

**Comment by bencaradocdavies** [comment]
You are welcome, @simboss. Credit also to client-of-a-client who isolated the problem back in May. Open source wins again.

**Comment by bencaradocdavies** [comment]
And thanks also to @dromagnoli, who wrote the original test fixture for the System property implementation, which still passes with the new implementation.  :-)

**Pull request merged**
