### PR TITLE
Add test to ensure fix of NPE during MySQL version check

### PR DESCRIPTION
**Pull request by nprigour**
test case added for #2033  fix in order to allow back-porting to geotools 19.x

Signed-off-by: Nikolaos Pringouris <nprigour@gmail.com>

### CODE REVIEW

**Comment by tbarsballe** [comment]
Closing and re-opening in an attempt to fix the Travis CI failure.

**Comment by tbarsballe** [comment]
Remaining travis failure appears to be legitimate - test failure in gt-jdbc-mysql
This needs to be fixed before this PR can be merged.

**Comment by nprigour** [comment]
Hi @tbarsballe ,

Probably it was something related to formatting of the file where the new test was added. I run 

> mvn fmt:format

 and assume format has been fixed now

**Comment by aaime** [comment]
@nprigour just info for next time, formatting happens in a normal maven build too, so as long as you do a "mvn install" before committing, your code will be properly formatted.

**Comment by aaime** [comment]
@nprigour you have two choices:
* Wait on a core developer (very scarce) spare time for backports. It's not just a cherry-pick, we have to run builds before committing. Time to completion is unpredictable
* Do pull requests of your own to do the backports, allowing core devs to just verify build success on Travis/Appveyor and hit the merge button

**Comment by nprigour** [comment]
So @aaime if I go for option 2 then should I just create a new PR (enclosing #2033 & #2044 changes) in the normal way (master branch) or against the 19.x branch?

**Comment by aaime** [comment]
Against the 20.x branch and 19.x branch

**Pull request merged**
