### PR TITLE
[GEOT-5307] Fixes to Footprint behavior

### PR DESCRIPTION
**Pull request by tbarsballe**
Two minor, related imageMosaic fixes:
* [GEOT-5307] Retain source images when extractin alpha channel
* Catch exceptions thrown by SidecarFootprintProvider implementations. I am not sure if this one actually causes problems, but one of the implementations did throw an exception when I was stepping through it in the debugger, so it is at least possible.

### CODE REVIEW

**Comment by aaime** [comment]
I believe you forgot to commit the tests?

**Comment by tbarsballe** [comment]
A test case for the first issue exists here: https://github.com/tbarsballe/geotools/commit/b4c54b5f3997aaf03b945d5a36a4206cbffa5b9f
However, it is waiting on another similar bug before it will actually pass; see https://osgeo-org.atlassian.net/browse/GEOT-5306

**Comment by tbarsballe** [comment]
I don't have a test for the second one, as I am not sure it can cause problems during normal excecution, at least not in a way that would be visible to a test case (any exceptions thrown get caught by the outer catch block; this could cause a provider to be skipped, but so far has only occured on the last provider in the list)

**Comment by aaime** [comment]
We cannot merge without a test case. Can you create one that only fails with the specific fix done here?

**Comment by aaime** [comment]
And oh, the commit messages should be in the form "[GEOT-XYWZ] title of the ticket"

**Comment by tbarsballe** [comment]
Sure, I will create one. It is a bit awkward that this will be a subset of the GEOT-5306 test case, but I guess it is worth it so we can merge now, in case GEOT-5306 doesn't get fixed anytime soon.

**Comment by tbarsballe** [comment]
I can rebase to update the commit messages as well; at time of commit the GEOT ticket didn't exist yet.

**Comment by tbarsballe** [comment]
Updated with a test case; squashed, rebased, and renamed commit.

**Comment by tbarsballe** [comment]
Updated test case; looks like image byte values behave differently on different systems :P

**Comment by aaime** [comment]
Looks good to me, again, best to also have @dromagnoli opinion

**Comment by dromagnoli** [comment]
Looks good to me too.

**Pull request merged**
