### PR TITLE
[GEOT-6783] - Activate unsupported gt-arcgisrest with -Dall

### PR DESCRIPTION
**Pull request by roarbra**
Activate gt-arcgisrest with -Dall.

Fixes some issues to make the code compile and tests to run.

# Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [ x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [x ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by bradh** [comment]
@roarbra Have you discussed this with Luca?

CI failures look unrelated - will kick those in a bit.

**Comment by roarbra** [comment]
Hi,

No, I haven't discussed it with anybody. I just started to look at the
functionality right now.

See no reason why it shouldn't be activated by -Dall.

Regards,

Roar Brænden

man. 4. jan. 2021 kl. 10:02 skrev Brad Hards <notifications@github.com>:

**Comment by bradh** [comment]
I think it is a work-in-progress, so discussing it with the author is probably appropriate. 

Also, the JDK11 test failure looks legitimate.

**Comment by bradh** [comment]
@lmorandini Can you take a look when you get back?

**Comment by aaime** [comment]
The "-Dall" is an old tradition of the GeoTools project. Unsupported modules should not be in the build, in theory. In practice, all unsupported modules used by GeoServer are in the build, without parameters. The "-Dall" parameter adds extra modules that are supposedly maintained, but do not pass some of the other graduation ticks. Refactors in the code should not break them, it's the responsibility of those doing the refactor to handle it. However, if you can show the module has nobody behind it (in other words, if @lmorandini does not answer), then we can also argue the module has lost its maintainer, and kick it out of the build. Gray area, I know.

**Comment by aaime** [comment]
Ah doh, sorry, misread the PR, thouth it was the other one about commons httpclient. Then my comments needs to be flipped. If we want the module in the build, we need someone to look after it (check PRs against it, answer questions on the list, at a minimum, extra points for fixing bugs, but we de-facto don't require it anymore, as existing maintainers are streatched to the point of the making bug fixing impossible, too many modules on too few hands). If @lmorandini is not up to the task, then @roarbra will have to take that role, in order to merge this PR.

**Comment by roarbra** [comment]
> I think it is a work-in-progress, so discussing it with the author is probably appropriate.
> 
> Also, the JDK11 test failure looks legitimate.

It's using a library powermock that have some issues with JDK 11. Not certain I have time to look at that.

**Comment by lmorandini** [comment]
This module is not orphaned, I made changes as late as August. I will look into this issue shortly: @roarbra, does the Java 11 issue affects only the master branch, or 24.x as well?

**Comment by roarbra** [comment]
> This module is not orphaned, I made changes as late as August. I will look into this issue shortly: @roarbra, does the Java 11 issue affects only the master branch, or 24.x as well?

I think it's in both 23.x and master. I did find some resources through SO, but I can't find them now. It wasn't an obvious fix, and I'm not familiar with powermock, so it's hard for me to fix.

**Comment by bradh** [comment]
I don't think its (just) powermock. I think its related to javax ws changes (removal) between 8 and 11. So we probably need to update the dependencies to pull in a WS impl. I'm taking a look at this now.

**Comment by aaime** [comment]
Confirming all branches, 23.x, 24.x and master, must build with JDK11 too. Pheraphs that's why the module is not in the build (it would not pass it, JDK11 build success is mandatory both on the Jenkins server and on PR checks).

**Pull request closed without merging**
