### PR TITLE
GEOT-6312 no alpha channel in JPEG

### PR DESCRIPTION
**Pull request by NielsCharlier**

### CODE REVIEW

**Comment by dromagnoli** [comment]
@NielsCharlier  
Looks good to me. +1 on merging it

**Comment by NielsCharlier** [comment]
Thanks @dromagnoli

**Comment by dromagnoli** [comment]
@NielsCharlier: Are you also going to backport that?

**Comment by NielsCharlier** [comment]
I can do that, if you recommend it

**Comment by dromagnoli** [comment]
Yes, please. 
I think they have very similar code so the same problem can occur on 21.x too.

**Pull request merged**
