### PR TITLE
Fixes for GEOT-4946, GEOT-5026, and GEOT-5045

### PR DESCRIPTION
**Pull request by williamvoor**

### CODE REVIEW

**Comment by aaime** [comment]
@jdeolive, how are we doing here?

**Comment by williamvoor** [comment]
I have updated this patch as per Justin's suggestions.

**Comment by jdeolive** [comment]
Looks great William! Thanks for the work on this one.

**Comment by jdeolive** [comment]
@aaime What's the current state of back ports? Back port to 13.x and 12.x if stable enough?

**Comment by aaime** [comment]
If they are bugfixes yep, you can backport without asking (unless we're doing a release like the next day.... but I don't think we are releasing from those branches until next month, don't we?)

**Pull request merged**
