### PR TITLE
[GEOT-7442] Make ErrorProne run on Windows

### PR DESCRIPTION
**Pull request by bestrauss**
[GEOT-7442](https://osgeo-org.atlassian.net/browse/GEOT-7442) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  
Changes to file `pom.xml` to make `ErrorProne` run on Windows, where file names, including `${project.build.directory}`, contain backslashes.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [N/A] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [N/A] New unit tests have been added covering the changes.
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [N/A] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [N/A] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [N/A] Bug fixes and small new features are presented as a single commit.
- [N/A] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by bradh** [comment]
Have restarted the failed CI check - looked unrelated.

**Comment by bestrauss** [comment]
@bradh Thanks!

**Comment by bestrauss** [comment]
@aaime Here's the ErrorProne/Windows PR, ready.

**Review by mprins — COMMENTED** [review]
Using build-helper-maven-plugin is almost always a hack either to work around some setup error breaking maven conventions or buggy behaviour in a jdk or plugin. Doing this for all build environments seems wrong, if at all it should only change the value on broken windows shells

**Comment by bestrauss** [comment]
@mprins 

I agree that preferably, the problem should be solved in ErrorProne. Developers over there have been aware of the issue since June 2021: https://github.com/google/error-prone/issues/2394

In the meantime, in `geoserver` a workaround has been merged in March 2023: https://github.com/geoserver/geoserver/pull/6605

The given solution changes the value only if it contains backslashes. Unix style paths remain unchanged.

**Comment by bestrauss** [comment]
I have simplified the changes of file `pom.xml`. Only one line is changed.

> `${project.build.directory}/generated-sources/.*`

is changed to 

> `\Q${project.build.directory}\E/generated-sources/.*`

This solution was used in `geoserver`, too.

**Comment by aaime** [comment]
Merged, thanks!

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply bbf360bbf6... [GEOT-7442] Make ErrorProne run on Windows
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4479-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick bbf360bbf65de1a29597101835bd504b4428d132
# Push it to GitHub
git push --set-upstream origin backport-4479-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4479-to-29.x`.

**Comment by aaime** [comment]
The backport to `28.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply bbf360bbf6... [GEOT-7442] Make ErrorProne run on Windows
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-28.x 28.x
# Navigate to the new working tree
cd .worktrees/backport-28.x
# Create a new branch
git switch --create backport-4479-to-28.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick bbf360bbf65de1a29597101835bd504b4428d132
# Push it to GitHub
git push --set-upstream origin backport-4479-to-28.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-28.x
```
Then, create a pull request where the `base` branch is `28.x` and the `compare`/`head` branch is `backport-4479-to-28.x`.

**Pull request merged**
