### PR TITLE
[GEOT-7457] Handle empty FlatGeobuf when spatial filtering

### PR DESCRIPTION
**Pull request by bjornharrtell**
[GEOT-7457](https://osgeo-org.atlassian.net/browse/GEOT-7457) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@aaime this should resolve what you initially reported at https://github.com/flatgeobuf/flatgeobuf/issues/312.

**Comment by aaime** [comment]
@bjornharrtell seems you coded it against an old "main" branch, FilterFactory2 is no more.
Read about the "org.opengis" removal work in the upgrade guide:
https://docs.geotools.org/stable/userguide/welcome/upgrade.html#geotools-30-x

**Comment by bjornharrtell** [comment]
@aaime ah :) I had troubles running the test after the rebase and saw that they were in need of some cleanup so that is done here now too.. but I don't think it should be a single commit.

**Comment by bjornharrtell** [comment]
I think the Downstream integration build (GeoWebCache and GeoServer) / build (pull_request) failure is not due to this PR.

**Comment by aaime** [comment]
Yeah looks like some issue building mapfish with Gradle (mapfish 3?)... @jodygarnett  looks like a repository caching issue of sorts. Does it make any sense to you?

**Comment by aaime** [comment]
The downstream build failure is indeed unrelated, merging.

**Comment by aaime** [comment]
The backport to `28.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 21cc04a999... [GEOT-7457] Clean up tests
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[backport-4493-to-28.x 03fa0844e5] [GEOT-7457] Handle empty FlatGeobuf when spatial filtering
 Author: Björn Harrtell <bjorn@wololo.org>
 Date: Thu Sep 28 22:30:18 2023 +0200
 3 files changed, 51 insertions(+), 12 deletions(-)
 create mode 100644 modules/unsupported/flatgeobuf/src/test/resources/org/geotools/data/flatgeobuf/empty.fgb
Auto-merging modules/unsupported/flatgeobuf/pom.xml
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java
CONFLICT (content): Merge conflict in modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDirectoryDataStoreTest.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-28.x 28.x
# Navigate to the new working tree
cd .worktrees/backport-28.x
# Create a new branch
git switch --create backport-4493-to-28.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 6858998a00775b84502bc7feeae524972a16da46,21cc04a9995448906942cea27d7faeb44f6ee8fc
# Push it to GitHub
git push --set-upstream origin backport-4493-to-28.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-28.x
```
Then, create a pull request where the `base` branch is `28.x` and the `compare`/`head` branch is `backport-4493-to-28.x`.

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 21cc04a999... [GEOT-7457] Clean up tests
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[backport-4493-to-29.x bbe60dfd04] [GEOT-7457] Handle empty FlatGeobuf when spatial filtering
 Author: Björn Harrtell <bjorn@wololo.org>
 Date: Thu Sep 28 22:30:18 2023 +0200
 3 files changed, 51 insertions(+), 12 deletions(-)
 create mode 100644 modules/unsupported/flatgeobuf/src/test/resources/org/geotools/data/flatgeobuf/empty.fgb
Auto-merging modules/unsupported/flatgeobuf/pom.xml
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java
CONFLICT (content): Merge conflict in modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
Auto-merging modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDirectoryDataStoreTest.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4493-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 6858998a00775b84502bc7feeae524972a16da46,21cc04a9995448906942cea27d7faeb44f6ee8fc
# Push it to GitHub
git push --set-upstream origin backport-4493-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4493-to-29.x`.

**Pull request merged**
