### PR TITLE
Upgrade to jts-core 1.14 [GEOT-5813] 

### PR DESCRIPTION
**Pull request by jodygarnett**
pull request resolves:
- https://osgeo-org.atlassian.net/browse/GEOT-5813 Upgrade to JTS 1.14
- https://osgeo-org.atlassian.net/browse/GEOT-3942 Transitive dependency version conflict on xerces

### CODE REVIEW

**Comment by jodygarnett** [comment]
Note this is not available in maven central yet; should we deploy to our repo?

**Comment by aaime** [comment]
Mind, the build is failing on a test:

````
Running org.geotools.geometry.jts.coordinatesequence.CoordinateSequencesTest
Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec <<< FAILURE! - in org.geotools.geometry.jts.coordinatesequence.CoordinateSequencesTest
testCoordinateDimensionPointLite1D(org.geotools.geometry.jts.coordinatesequence.CoordinateSequencesTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.geotools.geometry.jts.coordinatesequence.CoordinateSequencesTest.testCoordinateDimensionPointLite1D(CoordinateSequencesTest.java:29)
````

**Comment by tbarsballe** [comment]
Artifacts are now available at https://repo.boundlessgeo.com/main/com/vividsolutions/jts-core/1.14.0/

**Comment by mprins** [comment]
actually the artifacts are available in Maven Central, see:
  - https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.vividsolutions%22
  - http://repo1.maven.org/maven2/com/vividsolutions/jts-core/1.14.0/

**Comment by bencaradocdavies** [comment]
The Travis failure was not a timeout. See @aaime's comment above.

**Comment by tbarsballe** [comment]
@jodygarnett - Any update on the test failure? It would be nice to get this in before code freeze.

**Comment by jodygarnett** [comment]
I have not had a chance to look at it since foss4g, will look at it tomorrow.

**Comment by jodygarnett** [comment]
Dug into the regression, a factory method incorrectly handled the logic around 1 dimensional coordinate sequences. Reported to the JTS project here - https://github.com/locationtech/jts/issues/135

**Comment by jodygarnett** [comment]
Looks like a similar patch is needed for GML2. 

Jts issues seems unlikely to go anywhere.

**Comment by jodygarnett** [comment]
Additional commits to avoid pulling in jts as a transitive dependency.

**Comment by jodygarnett** [comment]
Integration tests:

* [x] geowebcache
* [ ] geoserver

**Pull request merged**
