### PR TITLE
[GEOT-6263] GMLFilterFeature/SubHandlerPolygon tamper with input data

### PR DESCRIPTION
**Pull request by bestrauss**
Easy bugfix with new test, This time clean, without sourcecode-formatting.

- GMLFilterFeature used to remove certain whitespace characters in feature attributes
- SubHandlerPolygon used to reverse CCW shell- and CW hole-LineStrings of Polygons

Both ways to tamper with input-data are demonstrated by the new test which will fail as long as the bugs are not fixed. The test creates two features, generates GML, parses the GML and compares attributes of the features.

### CODE REVIEW

**Comment by aaime** [comment]
Verified GeoServer builds fine with these changes.

**Comment by bestrauss** [comment]
> I think the changes are good, building the downstream projects (gwc and geoserver) to double check.
> This PR modifies more than one non test file, so we go out of the "small change" permissions and need you to sing a CLA to OSGeo for the contribution to be accepted. It's a good thing to do anyways since you're pushing other changes as well.
> See:
> 
>     * https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md
> 
>     * http://docs.geotools.org/latest/developer/procedures/contribution_license.html

I sent a signed license document to info@osgeo.org on 04.04.2016, 16:16. I forwarded one more copy just now.

**Comment by aaime** [comment]
The OSGeo secretary collects the CLAs, we don't receive them directly. Checking the records for 2016 (OSGeo keeps a database) I don't see anyone with your name...  (unless it was a company CLA?)
@astroidex could you confirm reception of said mail (assuming Astrid can be cc'ed from here, which I'm not sure)

**Comment by aaime** [comment]
@bestrauss looks like @astroidex is away from office, if you send me the CLA I'll make this one move on.

**Comment by aaime** [comment]
Got the CLA on file, merging, sorry for the wait!

**Pull request merged**
