### PR TITLE
more dynamic stroke-dasharray

### PR DESCRIPTION
**Pull request by wumpz**
Allow to read the dasharray completly from database, instead of getting each numerical part separately from database.

### CODE REVIEW

**Comment by bradh** [comment]
Note the conflict.

**Comment by wumpz** [comment]
Sorry again, wrong start.

**Comment by wumpz** [comment]
Sorry, but I am not able to create a pull request using your 16.1 tag. Shouldnt that be possible?

**Comment by wumpz** [comment]
I did not change the file mentioned. If you compare my changes to Geotools 16.1 (Tag), there will only be one commit to merge. Nevertheless do I have to change my commit using 16.x or could you help me creating a pull request using the used tag?

**Comment by wumpz** [comment]
created another pull request using 16.x as a base ...

**Comment by wumpz** [comment]
Look at PR #1465.

**Pull request closed without merging**
