### PR TITLE
Attempt at getting more stable GitHub actions results

### PR DESCRIPTION
**Pull request by aaime**
* Networking tweak based on suggestions from: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
* Switch from Zulu to AdoptOpenJDK (cause I believe we use the latter more, and cannot reproduce issues locally using it)
* Split the Linux build job in 3 separate ones, if one fails it can be restarted in isolation.

# Checklist

Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md)
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [ ] The changes are not causing two modules to share the same Java packages (to avoid [Java 9+ split package](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed) issues)
- [ ] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by aaime** [comment]
Closing a re-opeining a few times as a cheap way to restart all builds. Sorry for the noise :-D

**Comment by aaime** [comment]
Not seeing anymore jar download issues (progress) but the JDK 11 keeps on failing with these two:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project gt-jdbc-h2: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/geotools/geotools/modules/plugin/jdbc/jdbc-h2/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project gt-coverage: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/geotools/geotools/modules/library/coverage/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
```

Both tests failing open local ports. One module fails on coverage serialization, which uses SerializableRenderedImage, which in turn tries to open a little RMI server on any free port (it opens a server socket on port "0", meaning, any free port).
The other is a H2 test starting H2 in server mode, which opens port 9092, finding it busy. 
The same is not happening with JDK 8 though, not sure why....

**Comment by mprins** [comment]
> Not seeing anymore jar download issues (progress) 

but the cached .m2 directory is used unless the hash of all the pom files is changed, so restarting the same build doesn't mean all that much wrt download problems I think

**Comment by aaime** [comment]
@mprins right... suggestions?

**Comment by aaime** [comment]
I'm modifying the description of the project in the main pom as a way to change the hash of the poms. Please do not merge :D

**Comment by aaime** [comment]
Nothing I've tried seems to make those two tests pass. At this point, I guess I'll have to do like with GeoServer, create a "linux-github-build" variable and turn those two tests off when it's set up.

**Comment by aaime** [comment]
Now it's failing on downstream checks, when the metastore remover is trying to open a TCP port for the H2 database. Weird, but oh well, not necessary to open that port either:
https://github.com/GeoWebCache/geowebcache/pull/956

**Comment by aaime** [comment]
Finally green. Merging so that we can try it out on a larger set of PRs.

**Pull request merged**
