### PR TITLE
Enable PMD checks on test sources too

### PR DESCRIPTION
**Pull request by aaime**
Besides enabling the PMD checks on test sources, and solving or suppressing the issues, the following are included:

* Removal of the validation module
* Disabled PMD checks on the gt-arcsde test sources, waiting on feedback on its removal on gt-devel
* PMD checks for JUnit3 removal are disabled on the modules using heavily OnlineTest, which is still based on JUnit 3. The trick is to have two configuration files for PMD, one having just the JUnit3 checks, which is not used in the JDBC modules, as well as SOLR, GeoPkg, MongoDB.

# Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by bradh** [comment]
QA check thinks there is a format issue:

```
 Error:  Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.14.0:check (default) on project gt-jdbc: You have 1 PMD violation. For more details see: /home/runner/work/geotools/geotools/modules/library/jdbc/target/pmd.xml -> [Help 1]
Error:  Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gt-wfs-ng: Found 1 non-complying files, failing build -> [Help 1]
```

**Comment by aaime** [comment]
Uh oh, looks like I forgot to cleanup wgs-ng... though it was also based on JUnit3, but in fact, its online tests are JUnit4. Oh well, will fix next week.

**Comment by jodygarnett** [comment]
Is any review feedback useful at all? Or is this a case of the only review that matters is PMD running its tests :)

**Comment by aaime** [comment]
QA tests are still failing, missed gt-wfs-ng, so not read to merge.

@jodygarnett I'm confident enough with the tests, wherever tests actually run. What worries me are modules where tests do not run, e.g.: SOLR, MongoDB, ElasticSearch, WFS-NG to name a few (but there are others, e.g., teradata, sap-hana)

**Comment by aaime** [comment]
Branch ready, now includes removal of both gt-validation and gt-arcsde

**Pull request merged**
