### PR TITLE
[Backport 30.x] [GEOT-7579] FlatGeobuf handle java.util.Date and iso correctness

### PR DESCRIPTION
**Pull request by aaime**
[GEOT-7579](https://osgeo-org.atlassian.net/browse/GEOT-7579) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Backport #4768
 **Authored by:** @bjornharrtell

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Hmm it's something flaky about the timestamps serialization... I saw it earlier and cut off fraction on seconds to fix but pops up here. Strange... I should have a look.

**Comment by bjornharrtell** [comment]
To clarify I think it's in the tests rather than in actual logic the flakyness exists.

**Comment by bjornharrtell** [comment]
@aaime I'm worried this flakyness can happen randomly regardless of backport/java versions etc.

**Comment by aaime** [comment]
Yes, looks like it's random. Ouch, we don't need another random failure. Could you rework the test so that this does not happen=

**Pull request merged**
