### PR TITLE
Netcdf: support aggregation, exception on runtime dimension (GEOT-5510), improve date parsing (GEOT-5509), [GEOT-5528] NetCDF time variable is expected to be increasing (not decreasing)

### PR DESCRIPTION
**Pull request by NielsCharlier**
https://osgeo-org.atlassian.net/browse/GEOT-5509
https://osgeo-org.atlassian.net/browse/GEOT-5510
https://osgeo-org.atlassian.net/browse/GEOT-5528

In future I hope we can aim for one PR per Jira issue.

### CODE REVIEW

**Comment by simboss** [comment]
JIRA?

**Comment by NielsCharlier** [comment]
https://osgeo-org.atlassian.net/browse/GEOT-5509
https://osgeo-org.atlassian.net/browse/GEOT-5510

**Comment by jodygarnett** [comment]
Assume this is held up on code-freeze

**Comment by bencaradocdavies** [comment]
@NielsCharlier I restarted the Travis CI build.

**Comment by NielsCharlier** [comment]
@bencaradocdavies I made the suggested changes

**Comment by bencaradocdavies** [comment]
@simboss and @dromagnoli apologies in advance as this one is a bit tangled with too many Jira issues in one PR and individual commits that lack Jira tags. The changes look good to me, the test coverage is excellent, and the changes also include updated licence information for the examples pulled in from NetCDF-Java. As you might have guessed, @NielsCharlier has been thrown in at the deep end with NcML aggregations; hopefully future fixes will be a bit more separable and easier to review.

@simboss and @dromagnoli I will merge this now but if you have any concerns (other than those I mentioned above) please let us know and I am happy to back out any changes that you do not like.

**Comment by simboss** [comment]
I don't see anything dramatic, the changes are widespread but isolated, the test files are small enough.

I asked daniele to do a quick review next week just in case.

**Comment by dromagnoli** [comment]
It looks good to me too.
Thanks for these fixes.

**Pull request merged**
