### PR TITLE
[GEOT-5240] Transforming feature source does not honor naming convent…

### PR DESCRIPTION
**Pull request by ridethepenguin**
...ion on FID

### CODE REVIEW

**Comment by aaime** [comment]
Looks good, just one minor issue, the copyright year was not updated

**Comment by ridethepenguin** [comment]
@aaime Damn, I keep forgetting it :-(

`TransformFeatureSourceTest` is missing the header altogether, what should I do about it?

**Comment by aaime** [comment]
Add it, check in the history how old it is

**Comment by ridethepenguin** [comment]
Copyright headers added/updated.

**Pull request merged**
