### PR TITLE
[GEOT-7556] Just build javadocs for modules, and mvn javadoc doclint config

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-7556](https://osgeo-org.atlassian.net/browse/GEOT-7556) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Follow on to https://github.com/geotools/geotools/pull/4779 as we can only test in Jenkins.

This PR is adding both a fix and a GitHub workflow check so javadocs do not break build.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by jodygarnett** [comment]
The assembly works here, my hope is it will work on Jenkins as well. This is my last attempt for the day.

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 4707c54310... [GEOT-7556] Just build javadocs for modules, and use maven javadoc doclint configuration option
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
CONFLICT (modify/delete): .github/workflows/assembly.yml deleted in HEAD and modified in 4707c54310 ([GEOT-7556] Just build javadocs for modules, and use maven javadoc doclint configuration option).  Version 4707c54310 ([GEOT-7556] Just build javadocs for modules, and use maven javadoc doclint configuration option) of .github/workflows/assembly.yml left in tree.
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4796-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 4707c5431094deafc8a0481e1d49676ae68a68ba
# Push it to GitHub
git push --set-upstream origin backport-4796-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4796-to-29.x`.

**Comment by aaime** [comment]
The backport to `30.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 4707c54310... [GEOT-7556] Just build javadocs for modules, and use maven javadoc doclint configuration option
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging .github/workflows/assembly.yml
CONFLICT (content): Merge conflict in .github/workflows/assembly.yml
Auto-merging pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-30.x 30.x
# Navigate to the new working tree
cd .worktrees/backport-30.x
# Create a new branch
git switch --create backport-4796-to-30.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 4707c5431094deafc8a0481e1d49676ae68a68ba
# Push it to GitHub
git push --set-upstream origin backport-4796-to-30.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-30.x
```
Then, create a pull request where the `base` branch is `30.x` and the `compare`/`head` branch is `backport-4796-to-30.x`.

**Comment by aaime** [comment]
The backport to `31.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 4707c54310... [GEOT-7556] Just build javadocs for modules, and use maven javadoc doclint configuration option
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging .github/workflows/assembly.yml
CONFLICT (content): Merge conflict in .github/workflows/assembly.yml
Auto-merging pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-31.x 31.x
# Navigate to the new working tree
cd .worktrees/backport-31.x
# Create a new branch
git switch --create backport-4796-to-31.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 4707c5431094deafc8a0481e1d49676ae68a68ba
# Push it to GitHub
git push --set-upstream origin backport-4796-to-31.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-31.x
```
Then, create a pull request where the `base` branch is `31.x` and the `compare`/`head` branch is `backport-4796-to-31.x`.

**Pull request merged**
