### PR TITLE
[SEDONA-125] Add support to EPSG:9377 (MAGNA-SIRGAS / Origen-Nacional - Colombia)

### PR DESCRIPTION
**Pull request by dersteppenwolf**
[SEDONA-125](https://osgeo-org.atlassian.net/browse/SEDONA-125) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [ ] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [ ] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by ianturton** [comment]
Please don't delete the check list from the PR template, they all need to
be checked for us to accept the changes.

Are you sure that this CRS is missing? I'm on my phone just now so can't
check easily but I can't see why it would be missing if this is a regular
epsg code.

**Review by mprins — CHANGES_REQUESTED** [review]
Available on https://epsg.io/9377 and https://apps.epsg.org/api/v1/ProjectedCoordRefSystem/9377 but not on https://spatialreference.org/ref/?&search=9377
As far as I can tell this is a new (June 2020) CRS

This file is a fallback/workaround for things missing in the official dataset which are occisionally updated, the last time being https://github.com/geotools/geotools/pull/2479 when GeoTools was updated to v9.6 (current version is v10.075

Please do a complete upgrade instead of the EPSG libraries instead as it is available in the official repository.

**Comment by aaime** [comment]
Updating the EPSG database requires following these steps:
https://github.com/geotools/geotools/blob/main/modules/plugin/epsg-hsql/src/main/resources/org/geotools/referencing/factory/epsg/hsql/UpdateEPSGDatabase.txt

Under normal circumstances, it requires a day or two. However the upgrade to version 10, they changed the structure of tables, meaning SQL queries will have to be updated too, following this guide (I did not evaluate how big a change that is):  https://drive.tiny.cloud/1/4m326iu12oa8re9cjiadxonharclteqb4mumfxj71zsttwkx/995e4d18-4cbb-490d-b7d1-3b9258778bdd

**Comment by aaime** [comment]
I have reinstated the checklist. Failing to satisfy the requirements will result in the PR being ignored.

**Pull request closed without merging**
