### PR TITLE
[GEOT-7485] Double Check ReferencedEnvelope against Rectangle2D.Double() expectations

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOT-7485](https://osgeo-org.atlassian.net/browse/GEOT-7485) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

Checked the following:

* [x] rectangle(rectangle,crs)
* [x] setFrameFromCenter
* [x] setFrameFromDiagonal

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
Looks like a more complete replacement for https://github.com/geotools/geotools/pull/4542 ?

**Comment by jodygarnett** [comment]
> Looks like a more complete replacement for #4542 ?

Huh? This is #4542

**Comment by aaime** [comment]
Sorry, wrong link... this is the right one: https://github.com/geotools/geotools/pull/4539

**Comment by jodygarnett** [comment]
That is correct @aaime this replaces #4539 - indeed I found some additional problems when writing a test case testing against Rectangle.2D behaviour to avoid futher regressions).

**Comment by aaime** [comment]
Looks good to me, merging and queuing for backport

**Comment by aaime** [comment]
The backport to `30.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 6785d01d04... [GEOT-748] Double Check ReferencedEnvelope against Rectangle2D.Double behaviour
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
Auto-merging modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
CONFLICT (content): Merge conflict in modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-30.x 30.x
# Navigate to the new working tree
cd .worktrees/backport-30.x
# Create a new branch
git switch --create backport-4542-to-30.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 6785d01d044b8b5c5b9ce54144110bb88c222691
# Push it to GitHub
git push --set-upstream origin backport-4542-to-30.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-30.x
```
Then, create a pull request where the `base` branch is `30.x` and the `compare`/`head` branch is `backport-4542-to-30.x`.

**Comment by aaime** [comment]
Thinking out loud, I'd have a look at the tests for the old, replaced classes, and see if there is anything else that's worth testing.

Also, bummer, the automatic backport to 30.x failed....

**Comment by jodygarnett** [comment]
In this case the methods were previously part of Java AWT Rectangle; so there were no old replaced classes we could borrow tests from.

**Pull request merged**
