### PR TITLE
centralise JUnit versioning and bump to 4.13.1

### PR DESCRIPTION
**Pull request by ianturton**
Dependabot want's to upgrade JUnit to 4.13.1 and this showed up that there were poms that had their own version tags that conflicted with the main pom. This PR fixes that.
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):
- [ ] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Review by mprins — APPROVED** [review]

**Review by bradh — APPROVED** [review]
The change looks fine, but I wonder if you want to get the ones in `doc/` as well?

**Comment by ianturton** [comment]
The ones in Docs are more standalone as people copy those directly in to their own projects so I've left them,

**Comment by bradh** [comment]
> The ones in Docs are more standalone as people copy those directly in to their own projects so I've left the

Valid. So probably "make consistent" is more appropriate than centralising.

**Comment by mprins** [comment]
Seems the upgrade brings up some deprecation warnings, mostly for:
`<T>assertThat(T,org.hamcrest.Matcher<? super T>) in org.junit.Assert has been deprecated`

https://travis-ci.org/github/geotools/geotools/jobs/735333705#L3068 and down

**Comment by ianturton** [comment]
Well that will teach me to try to do a quick fix before breakfast!

**Comment by aaime** [comment]
Awesome, thanks @ianturton

**Pull request merged**
