### PR TITLE
[GEOT-5397] fixed org.geotools.styling.FeatureTypeStyleImpl.clone()

### PR DESCRIPTION
**Pull request by bestrauss**
and added new test: org.geotools.styling.FeatureTypeStyleImplTest

### CODE REVIEW

**Comment by aaime** [comment]
Looking good minus two buglets in copyright headers, the FeatureTypeStyleImpl one should say 2002 - 2016, the test being new just 2016

**Comment by jodygarnett** [comment]
@bestrauss I think you have combined two fixes by accident, this one for FeatureTypeStyle clone ... and a second issue with ECQL handling of ID?

Can you issue these as two seperate pull requests?

**Comment by bencaradocdavies** [comment]
@bestrauss please resubmit as two separate pull requests as @jodygarnett requested.

**Comment by bestrauss** [comment]
@jodygarnett, @bencaradocdavies I resubmitted two separate pull requests

**Pull request closed without merging**
