### PR TITLE
[GEOT-7226] ParameterTypeFactoryTest fails for certain locales

### PR DESCRIPTION
**Pull request by roarbra**
[GEOT-7226](https://osgeo-org.atlassian.net/browse/GEOT-7226) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

The test fails in newer JDK for certain locales, because of the minus character being used.

I've included a function that creates an expectation in accordance with the locale of the user.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [X] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [X] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [X] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by jodygarnett** [comment]
The bug report indicates this fails for "norwegian and some other nordic locales" is there any way to have the test case cover this scenario?

**Comment by roarbra** [comment]
Such a test case would be more appropriate where the Filter parsing / encoding is handled. This bug was intoduced because of a change in default handling of filter's. It would be interesting to expand this test in WFS to see what implications this change have for different server and client configurations.

**Comment by aaime** [comment]
@jodygarnett @roarbra I believe the test can be modified to run over different locales using a parameterized test:
https://www.tutorialspoint.com/junit/junit_parameterized_test.htm

There are a number of examples in the code base too:

```
git grep "@Parameterized"
library/main/src/test/java/org/geotools/feature/visitor/AverageVisitorTest.java:    @Parameterized.Parameters
library/main/src/test/java/org/geotools/feature/visitor/EqualAreaListVisitorTest.java:        @Parameterized.Parameter public int numClasses;
library/main/src/test/java/org/geotools/feature/visitor/EqualAreaListVisitorTest.java:        @Parameterized.Parameter(1)
library/main/src/test/java/org/geotools/feature/visitor/EqualAreaListVisitorTest.java:        @Parameterized.Parameters(name = "Classes: {0}, Tolerance {1}")
library/main/src/test/java/org/geotools/feature/visitor/MedianVisitorTest.java:    @Parameterized.Parameters
library/main/src/test/java/org/geotools/feature/visitor/SumAreaVisitorTest.java:    @Parameterized.Parameters
library/main/src/test/java/org/geotools/feature/visitor/SumVisitorTest.java:    @Parameterized.Parameters
library/main/src/test/java/org/geotools/filter/function/EqualAreaFunctionTest.java:        @Parameterized.Parameter public int numClasses;
library/main/src/test/java/org/geotools/filter/function/EqualAreaFunctionTest.java:        @Parameterized.Parameter(1)
library/main/src/test/java/org/geotools/filter/function/EqualAreaFunctionTest.java:        @Parameterized.Parameters(name = "Classes: {0}, Tolerance {1}")
library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java:    @Parameterized.Parameters(name = "{0}")
library/metadata/src/test/java/org/geotools/util/UnitFormatRoundTripTest.java:    @Parameterized.Parameters(name = "{index}: {0}")
library/render/src/test/java/org/geotools/renderer/lite/ZOrderTest.java:    @Parameterized.Parameters
plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFUnitParserTest.java:        @Parameterized.Parameters(name = "{index}: {0} -> {1}")
unsupported/geojson-core/src/test/java/com/bedatadriven/jackson/datatype/jts/LineStringTest.java:    @Parameterized.Parameters(name = "{0}")
unsupported/geojson-core/src/test/java/com/bedatadriven/jackson/datatype/jts/PointTest.java:    @Parameterized.Parameters
unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java:    @Parameterized.Parameters(name = "{0}")
unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/GeoJSONWriteTest.java:    @Parameterized.Parameters(name = "{0}")
unsupported/gml-geometry-streaming/src/test/java/org/geotools/gml/stream/XmlStreamGeometryReaderParameterizedTest.java:    @Parameterized.Parameters(name = "GML file: {0}")
```

I agree it would be preferable to have it run with a bunch of well-known problematic locales (as well as common ones).
In theory, it could be run in all locales, but it might take too much time to do so.

**Comment by roarbra** [comment]
I've introduced Parameterized locale. For the moment just English and Norwegian.

**Comment by aaime** [comment]
Looks good to me, thanks. Merging and backporting.

**Pull request merged**
