### PR TITLE
[24.x backport][GEOT-6778] Upgrade to JTS Topology Suite 1.18.0

### PR DESCRIPTION
**Pull request by mprins**
backports #3295 to 24.x

# Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x] The changes are not breaking the build in downstream projects using SNAPSHOT dependencies, GeoWebCache and GeoServer (there is an automatic PR check verifying this, check this when it turns green).

The following are required only for core and extension modules (they are welcomed, but not required, for unsupported modules):

- [x] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [ ] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Documentation has been updated accordingly.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.

### CODE REVIEW

**Comment by aaime** [comment]
Think @jnh5y had an objection against backporting JTS upgrades, as a previous upgrade caused API incompatibilities in the stable series (which is no a no go, in general). Unless this time the JTS release has less changes, or is otherwise not likely to contain API changes?

**Comment by mprins** [comment]
feel free to close.

there are some API changes listed in https://github.com/locationtech/jts/releases/tag/jts-1.18.0 but it seems these changes do not concern GeoTools code (otherwise the builds would have failed) so there is no API change in GeoTools.
The changes to `GeometryPrecisionReducer` are not an API change but an improvement/bugfix that may lead to different behaviour in some (exceptional) cases

If users rely on a transitive dependency from GeoTools they're doing it wrong IMHO; I mean if you use JTS in your code (that means you use classes not imported by GeoTools) you should add JTS to your project's dependency list, so you stay in control of the dependencies you use.

but as he said: https://github.com/geotools/geotools/pull/3295#discussion_r549461931

**Comment by jodygarnett** [comment]
Thanks for the PR, I think we can merge this later in January once the main branch has enjoyed JTS 1.18 for a bit.

**Comment by jodygarnett** [comment]
Oh wait, I am reminded that this jts 1.18.0:
- removed a couple things
- needed `buffer(0)` added in one spot

So we should not backport.... closing.

**Comment by aaime** [comment]
I'm not sure on the part that people should control their dependencies... I mean, it's a good practice, but if GeoTools is updated to a JTS version that requires an API change, it's going to be modified to use the different API. At that point the downstream project either adapts, or you'll start getting weird exceptions at runtime (non existing methods called by GT code compiled agains the other JTS version).

**Pull request closed without merging**
