### PR TITLE
[GEOT-7441] Upgrade sortpom plugin

### PR DESCRIPTION
**Pull request by bradh**
[GEOT-7441](https://osgeo-org.atlassian.net/browse/GEOT-7441) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

The sortpom plugin is lagging behind current. See https://github.com/Ekryd/sortpom#news

Note there are two breaking changes, which cause our POM files to change. I think its an improvement though.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [N/A] New unit tests have been added covering the changes.
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Comment by aaime** [comment]
No objection here, but we need uniformity, the upgrade should be backported to 29.x and maybe also 28.x (one more release of it is still a possibility, either due to some sponsoring or maybe due to security-related findings down the road, as our recent history shows).  That will help avoiding conflicts in backports.

**Comment by bradh** [comment]
> No objection here, but we need uniformity, the upgrade should be backported to 29.x and maybe also 28.x (one more release of it is still a possibility, either due to some sponsoring or maybe due to security-related findings down the road, as our recent history shows). That will help avoiding conflicts in backports.

I've added the labels, but expect that the JDK11Test part will conflict, and I'll need to do it manually.

**Comment by bradh** [comment]
Failing SAP HANA test - see https://github.com/geotools/geotools/pull/4482#issuecomment-1723132523

**Comment by aaime** [comment]
Looks good, thanks!

**Comment by aaime** [comment]
The backport to `28.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply d1fcda7ba2... [GEOT-7441] Upgrade sortpom plugin
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging docs/pom.xml
Auto-merging modules/extension/app-schema/app-schema/pom.xml
Auto-merging modules/extension/complex/pom.xml
Auto-merging modules/extension/wms/pom.xml
Auto-merging modules/extension/xsd/xsd-core/pom.xml
Auto-merging modules/extension/xsd/xsd-filter/pom.xml
Auto-merging modules/extension/xsd/xsd-gml3/pom.xml
Auto-merging modules/extension/ysld/pom.xml
Auto-merging modules/library/coverage/pom.xml
Auto-merging modules/library/cql/pom.xml
Auto-merging modules/library/http/pom.xml
Auto-merging modules/library/jdbc/pom.xml
Auto-merging modules/library/main/pom.xml
Auto-merging modules/library/referencing/pom.xml
Auto-merging modules/library/render/pom.xml
Auto-merging modules/plugin/coverage-multidim/netcdf/pom.xml
Auto-merging modules/plugin/http-commons/pom.xml
Auto-merging modules/plugin/imageio-ext-gdal/pom.xml
Auto-merging modules/plugin/imagemosaic/pom.xml
Auto-merging modules/plugin/jdbc/jdbc-h2/pom.xml
CONFLICT (content): Merge conflict in modules/plugin/jdbc/jdbc-h2/pom.xml
Auto-merging modules/unsupported/cql2/pom.xml
Auto-merging modules/unsupported/elasticsearch/pom.xml
Auto-merging modules/unsupported/mbtiles/pom.xml
Auto-merging modules/unsupported/ogr/ogr-core/pom.xml
Auto-merging modules/unsupported/process-raster/pom.xml
Auto-merging modules/unsupported/solr/pom.xml
Auto-merging modules/unsupported/wps/pom.xml
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml
Auto-merging release/pom.xml
CONFLICT (content): Merge conflict in release/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-28.x 28.x
# Navigate to the new working tree
cd .worktrees/backport-28.x
# Create a new branch
git switch --create backport-4476-to-28.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick d1fcda7ba22d0549390ea6abba7e3d83046c568f
# Push it to GitHub
git push --set-upstream origin backport-4476-to-28.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-28.x
```
Then, create a pull request where the `base` branch is `28.x` and the `compare`/`head` branch is `backport-4476-to-28.x`.

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply d1fcda7ba2... [GEOT-7441] Upgrade sortpom plugin
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging docs/pom.xml
Auto-merging modules/extension/app-schema/app-schema/pom.xml
Auto-merging modules/extension/complex/pom.xml
Auto-merging modules/extension/wms/pom.xml
Auto-merging modules/extension/xsd/xsd-core/pom.xml
Auto-merging modules/extension/xsd/xsd-filter/pom.xml
Auto-merging modules/extension/xsd/xsd-gml3/pom.xml
Auto-merging modules/extension/ysld/pom.xml
Auto-merging modules/library/coverage/pom.xml
Auto-merging modules/library/cql/pom.xml
Auto-merging modules/library/http/pom.xml
Auto-merging modules/library/jdbc/pom.xml
Auto-merging modules/library/main/pom.xml
Auto-merging modules/library/referencing/pom.xml
Auto-merging modules/library/render/pom.xml
Auto-merging modules/plugin/coverage-multidim/netcdf/pom.xml
Auto-merging modules/plugin/http-commons/pom.xml
Auto-merging modules/plugin/imageio-ext-gdal/pom.xml
Auto-merging modules/plugin/imagemosaic/pom.xml
Auto-merging modules/plugin/jdbc/jdbc-h2/pom.xml
Auto-merging modules/unsupported/cql2/pom.xml
Auto-merging modules/unsupported/elasticsearch/pom.xml
Auto-merging modules/unsupported/mbtiles/pom.xml
Auto-merging modules/unsupported/ogr/ogr-core/pom.xml
Auto-merging modules/unsupported/process-raster/pom.xml
Auto-merging modules/unsupported/solr/pom.xml
Auto-merging modules/unsupported/wps/pom.xml
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml
Auto-merging release/pom.xml
CONFLICT (content): Merge conflict in release/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4476-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick d1fcda7ba22d0549390ea6abba7e3d83046c568f
# Push it to GitHub
git push --set-upstream origin backport-4476-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4476-to-29.x`.

**Comment by aaime** [comment]
@turingtestfail could you do a 29.x backport too?

**Pull request merged**
