### PR TITLE
[GEOT-7387] Improve URL checking

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOT-7387](https://osgeo-org.atlassian.net/browse/GEOT-7387) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)

This PR contains the following changes:
1. Blocks URLs with invalid escape sequences which can interfere with normalization.
2. Blocks URLs with URL encoded percent and slash characters which can interfere with normalization.
3. Blocks URLs if all applicable normalization attempts fail.
4. StyledShapePainter uses URLCheckers for SLD GraphicLegend links.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [x] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if change is visible to end users).
- [x] There is an issue in [GeoTools Jira](https://osgeo-org.atlassian.net/projects/GEOT) (except for changes not visible to end users). 
- [x] Commit message(s) must be in the form ``[GEOT-XYZW] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] The commit targets a single objective (if multiple focuses cannot be avoided, each one is in its own commit, and has a separate ticket describing it).

### CODE REVIEW

**Review by aaime — APPROVED** [review]
Looks good to me (failing tests aside)

**Comment by sikeoka** [comment]
I merged the test fix from main so the tests all passed.

**Comment by aaime** [comment]
The backport to `28.x` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit 09a90626a5e3ab007583c99991a157b2d9c2a21e is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-4362-to-28.x efeb57631d] [GEOT-7387] Improve URL checking
 Author: Steve Ikeoka <steve.ikeoka@gdit.com>
 Date: Wed Jun 28 13:19:55 2023 -0700
 4 files changed, 107 insertions(+), 5 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-28.x 28.x
# Navigate to the new working tree
cd .worktrees/backport-28.x
# Create a new branch
git switch --create backport-4362-to-28.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 8531299e373856b7ecf3f74c12df6ebb79b584bc,09a90626a5e3ab007583c99991a157b2d9c2a21e
# Push it to GitHub
git push --set-upstream origin backport-4362-to-28.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-28.x
```
Then, create a pull request where the `base` branch is `28.x` and the `compare`/`head` branch is `backport-4362-to-28.x`.

**Comment by aaime** [comment]
The backport to `29.x` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit 09a90626a5e3ab007583c99991a157b2d9c2a21e is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-4362-to-29.x e8040c7801] [GEOT-7387] Improve URL checking
 Author: Steve Ikeoka <steve.ikeoka@gdit.com>
 Date: Wed Jun 28 13:19:55 2023 -0700
 4 files changed, 107 insertions(+), 5 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-29.x 29.x
# Navigate to the new working tree
cd .worktrees/backport-29.x
# Create a new branch
git switch --create backport-4362-to-29.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 8531299e373856b7ecf3f74c12df6ebb79b584bc,09a90626a5e3ab007583c99991a157b2d9c2a21e
# Push it to GitHub
git push --set-upstream origin backport-4362-to-29.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-29.x
```
Then, create a pull request where the `base` branch is `29.x` and the `compare`/`head` branch is `backport-4362-to-29.x`.

**Pull request merged**
